### ISSUE TITLE
Add in a way to delete an APD draft

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1021]
If an APD is started by accident or no longer needed, there should be a way to remove that from the state user's queue by deleting it.

**Comment by mgwalker** [comment]
@jeromeleecms @NAretakis In the pilot, the eAPD system will not be creating records, so we can delete whatever we want.  In the future, though, we may not be able to delete things.  I'm hesitant to add functionality to really delete APDs now because I'm concerned we won't remember to change the behavior in the future if eAPD ends up being a system of record.

How would you feel about an in-between solution where there's UX to "delete" an APD, but what we really do is change its status in the database and then just don't display it?  It has the same apparent effect for users, but the underlying data still exists in the eAPD database.  It feels safer to me for a future where eAPD may be a system of record.

Alternatively, we could document somewhere that APDs are permanently deleted and that we need to revisit that behavior in the future.

**Comment by NAretakis** [comment]
For the pilot, since it is not a system of record, I don't think we have to worry about it. But, I like the in-between solution as something for us to look at doing (keeping it lightweight), as this is really something we'll thoroughly explore in layer two (as we work through the various statuses of APDs, and what those mean).

**Comment by jeromeleecms** [comment]
In other systems I've built/worked on, we had an "Archive" flag for many of the fields - that way nothing was ever deleted (and didn't have to worry about cascading deletes within the database). If the archive was ticked on, it just wouldn't display. Would that work?

**Comment by mgwalker** [comment]
Marking it as archived would be super lightweight.  I'm 💯 in favor of that as a solution!

**Comment by NAretakis** [comment]
Sold. Let’s do it.
