### ISSUE TITLE
Focused review of the Help Text within the Activity Portion of the App

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1027]
Target areas which may interrupt flow / data entry integrity + evaluate feedback from usability testing for the Activity portion of the App

### This task is done when...
- [x] Inventory the section (in progress)
- [x] Compare with usability testing feedback
- [x] Review my inventory with SMEs (Nick or Jerome)
- [x] Edit the yaml and work through via PR until consensus

That checklist was originally in a comment on #953. That was closed because it was not an actively managed issue and what it was addressing on should emerge from this work, as well.

**Comment by jameshupp** [comment]
A couple things discussed for this that aren't in #1056, just noting here so I have a quick reference fo creating subsequent issues on them:
- whether the "Add" button language works properly for the look and function of the buttons
- eliminating start dates for milestones and/or adjusting the label away from "milestones" because milestones don't feel like things with ranges to me, but again does that shift require design changes?
- section titling: how do we feel about existing case choices (when it's title, when it's sentence, etc.)

**Comment by jameshupp** [comment]
Done!
