### ISSUE TITLE
Focused Review of the Language within the Dashboard

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1028]
Review the Dashboard language and statuses for provide clarity + evaluate content from the Round 7 (and subsequent) usability testing.

### This task is done when...
 - [ ] The dashboard introduces _what_ the app is, not just how to use it, per testing feedback.
 - [ ] The dashboard fulfills the app's design principles.
 - [ ] Product has reviewed any changes.

**Comment by NAretakis** [comment]
related to #1029 , this issue is likely obsolete, once #1029 is resolved.

**Comment by jameshupp** [comment]
A couple notes here:

* The yaml suggests a `subheader`. It's blank. When I populate it, it does not populate to the page. (This is not super surprising to me.) I think it should. @mgwalker 
* We've talked about calling this the APD Builder, right? So if we put `HITECH APD Builder` in the `title` field, how's that sound? Too many capital letters? Should we downplay HITECH so it's easier to fold in other APDs, too? I have assumed it's a specific use case and we'll have to make other significant changes if we ever want to support other APDs but just wanted to see what folks thought. My thinking is a subhead is a great place to say this is the dashboard or homepage, and it makes it easier to accomplish what this issue is about, which is telling people _what the thing is_, which is not just this page but the whole app. (I think this might be for @jeromeleecms and might actually be a longer conversation between us. I don't mean to get radical here!)
* If that title makes sense, we may need a slightly different label in the upper left with the state image? Or is _that_ where we need to retitle? It strikes me as not an intuitive place for the app title to live on what constitutes a homepage. I expect the largest, boldest text on the page, right at the top of the main body column, to be the title of the app. (This is an @austinhernandez question.)
* The `helpText` on this page does not recognize line breaks. I don't want to make a super long intro here, but I do think if we want to tell people both what the app _is_ and what they're seeing on this page, we're going to need some separation. There may be other visual ways to achieve that (also for Austin).

**Comment by mgwalker** [comment]
The only thing in `stateDashboard.yaml` currently being used is the `none` key.  So...  that's a true thing.  😬  What would the subheader be, in the context of the new design in #1378?  (That is, is the subheader reflected by something already in the design or would it be a new piece?)

Re: the `helpText`, we'll make it recognize line breaks.

**Comment by jameshupp** [comment]
Based on conversation today:

* `subheader` isn't relevant anymore, since the actual title of the app will be in the app header. There's a larger long-term conversation I think is worth having about making the shape of the YAML feel more meaningful, but I wouldn't expect to address that in layer 1.
* The title is what it already is: `CMS HITECH APD`. Because it'll be in the app header, we can use the YAML `title` _for this page_ in the way it's used now: to talk about what's on this page.
* Nothing need change about the state image and text.
* I do want helpText to recognize line breaks. :) I'll just start a PR addressing this issue to improve the text on the page, then I'll tag someone else in on that.

**Comment by NAretakis** [comment]
can we close this issue?

**Comment by jameshupp** [comment]
Sorry, I forgot to follow up on the open PR on this. I will close that out and that will close this.
