### ISSUE TITLE
State Dashboard (fancy)

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1029]
Revisit dashboard based on round 7 of usability testing. 

Synthesis: https://docs.google.com/document/d/1yoY6zHBwAGZwYPjSzxSkCaAo2EnemA9x1sbC5xptmTw/edit#

**Comment by lauraponce** [comment]
Inspired by Ron's card design on #726 here is an updated version of the dashboard. With the vertical history, more of the details can be included (which was feedback we heard in testing). There is a quick view of the current status for all of the documents/contracts and then clicking the collapsable arrow will display the full history.

<img width="555" alt="screen shot 2018-10-15 at 9 43 35 pm" src="https://user-images.githubusercontent.com/21222704/46993322-72525a80-d0c3-11e8-899c-59bde303c3ac.png">
 
@jeromeleecms thoughts on this format for the statuses?

**Comment by lauraponce** [comment]
Some more background/history on the progression of the dashboard wireframes: #383 and #676

**Comment by lauraponce** [comment]
Building off the original version with just some minor updates, here's another version. This would need some content help to figure out the right terminology, but the gist of it is here:

![screen shot 2018-10-17 at 3 48 38 pm](https://user-images.githubusercontent.com/21222704/47120602-279c2400-d224-11e8-9c21-52aee0f0a742.png)

This includes some more context and details around each of the steps, e.g. it wouldn't just say "awaiting state reply" — it would clearly show that it's in the review stage and within the review stage, we are waiting for the state respone. There are also details around who performed the last action and when with clear calls to action by the current status for what the state user can do next. @jeromeleecms @NAretakis

**Comment by lauraponce** [comment]
As far as the type of information and level of detail that we should be displaying in the dashboard, does this seem right, @NAretakis and @jeromeleecms? If so, I'll work on handing it off to Jen for the visual design refinements and James for the content.

**Comment by jenniferthibault** [comment]
My updates here fall into two themes:
- Finding an interaction pattern that feels successful for the Status section
- Finding possible improvements to the interface using my newbie goggles :)

## Interaction pattern for the Status section
In all the prototypes linked below, try out the open/close action works for the APD that has an alert. (that's the only thing i hooked up for now since I was focusing on this interaction specifically).

Based on the above designs and feedback, I was looking for:
- a pattern with a layout that gave us space to explain each phase on the progress bar
- something that wouldn't create weird empty space if one item was expanded
- a pattern that kept the status summary, any required actions, and the document title link always visible. This helped keep the list scannable and action-oriented. 

### [ 💻  Concept A: right-hand panel](https://gsa.invisionapp.com/share/APOR646YFN2#/327331547_Status-A_Closed)

![status-a](https://user-images.githubusercontent.com/11636908/47435148-f6ff4180-d771-11e8-9786-9d646a3549ae.gif)

The interaction, which uses a right-hand panel to expand the details feels the most successful to me in terms of the criteria I was aiming for above. You might recognize this interaction as a common one from some email inbox designs. It treats the list items as a responsive table that collapses to expand details, and gives us a good amount of space for readable text, without making empty space.

## Newbie goggle feedback
- Having two separate phases for "Submitted" and "Received" seemed like it was taking up a lot of real estate for what is essentially one step on the user's side. I explored instead having a "Document created" phase on the timeline, which is the step where a document would stay from the time it's started until it's submitted. This replaces the "Draft" stage I saw in the live dashboard.
![screen shot 2018-10-24 at 10 02 55 am](https://user-images.githubusercontent.com/11636908/47436108-dc2dcc80-d773-11e8-8b89-2c37aa8fadc6.png)



- I tried creating more space for text to explain what's happening behind the scenes at each stage, but would definitely like help making sure that it's accurate from @jeromeleecms & @NAretakis , and @jameshupp's  sharp brain here. It would be extra neat if we had a past/present/future tense variation for each stage that would change based on where the doc is in the process so that it reflects the status as accurately as possible

_________
## Other concepts
The cutting room floor! In case it's helpful to see what else I explored, and why I think it doesn't feel as strong as Concept A above.

### [ 💻  Concept B, cards with overlay](https://gsa.invisionapp.com/share/APOR646YFN2#/327331545_Status-B_Closed)
This explored @lauraponce's card mockups, but instead of pushing down the content below, the expanded content lays over the rest. The change in shape of this layout felt nice, but overall the grid layout makes it harder to tell what order the documents are sorted in. I'm also not sure exactly how well this would work accessibility use cases.

### [ 💻  Concept C, horizontal format cards](https://gsa.invisionapp.com/share/APOR646YFN2#/327331541_Status-C_Closed)
An iteration on the small cards to keep the scannable ordered list feeling when all panels are closed. This felt _ok_, but the 5-stage timeline meant that text boxes inside the expanded card were pretty narrow and cramped.

### [ 💻  Concept D, accordion panels](https://gsa.invisionapp.com/share/APOR646YFN2#/327331543_Status-D_Closed)
An iteration on the horizontal cards that returns uses an accordion panel, which I notices is user frequently on the site. This also felt _ok_, but not great and had the same narrow text field problem as Concept C.

This is a lot! Glad to talk through any questions, demo the interaction prototypes with a group, or discuss here.

**Comment by jenniferthibault** [comment]
Great question — re: the sidebar and the document list on the dashboard. I hadn't gotten that far yet, @lauraponce has any thinking been done so far about the relationship of these two elements? I'm not immediately bothered by having an MVP with this type of nav redundancy at this point, since it's giving people two ways into what they're looking for most. We can test to see if there's other things people try to get to frequently from the dashboard that could inform changes to the nav.

@jameshupp I've started a [Google Doc](https://docs.google.com/document/d/1E9AunXbN2E_BWc12Ag8uuEJzcOZ5RrF24et7w1m78T4/edit#) where we can work on content. 

Heads up @hbillings — anything here strike you as complicated to the point of maybe needing to walk it back before moving forward to a dev issue?

**Comment by hbillings** [comment]
@jenniferthibault this is definitely a case for getting our grid sorted out before we move forward with any more layout work! Do you think maybe we could find some time tomorrow so you can demo for me? I'm curious how you see the first and second stages of the GIF transitioning, because I can think of a few ways that could work (some trickier to build than others).

**Comment by hbillings** [comment]
After chatting with @jenniferthibault this morning, I think this is 👍. It would be marginally easier to implement just the expanded view, with the first element selected by default, but we decided the impact on usability outweighs the slight effort savings.

Jen, one thing I just thought of is that we could possibly do a slick little slide transition between the collapsed and expanded view pretty easily.

**Comment by jenniferthibault** [comment]
I like the sound of that @hbillings !! I pulled the interaction design into a front-endy issue in https://github.com/18F/cms-hitech-apd/issues/1075 to get you started.

We'll keep working on the specific content of the stages here and will make a second implementation issue when that's ready.

**Comment by lauraponce** [comment]
@jenniferthibault re: the left nav on the dashboard — we haven't isolated it in testing to get feedback on it specifically, but in general, people seemed to notice it and point it out as a way they could click into their APDs. It seemed to catch their attention because it was there, but they did notice other paths to open their docs from the dashboard.

The reason why the nav ended up on the dashboard in the first place was for visual consistency with the left navigation in the app, but since the nav elements change anyway, it might not be so consistent! I captured this as part of what we want to learn in testing the dashboard in #1070.

**Comment by jenniferthibault** [comment]
Talking with @lauraponce yesterday (this was right after you dropped off @jameshupp , sorry!) we have an idea for this feature that might walk it back a little to get closer to a real MVP state.

If we consider MVP for this dashboard as the ability to see your documents, create a new one, and understand _at a high level_ where they are in the process, that could simplify the above designs to this (Where the "create new" still lives in the sidebar):

![screen shot 2018-11-01 at 10 25 35 am](https://user-images.githubusercontent.com/11636908/47857627-77e8b980-ddc0-11e8-94a3-37178f46a365.png)

**Open questions:**
- How do folks feel about walking this back and considering the expanded panel with more functionality a later iteration?
- @jameshupp did I accurately bring in your comments about stage vs status in from the working [content doc](https://docs.google.com/document/d/1E9AunXbN2E_BWc12Ag8uuEJzcOZ5RrF24et7w1m78T4/edit?ts=5bd9eb8a#heading=h.hwoxct9ij30i) and the [document flow mural](https://app.mural.co/t/gsa6/m/gsa6/1540576639730/98e9cb36a85619864c28a397648ed67e18defdee)? Thinking we can consider the first text in the status field the Stage, and the text after the colon the Status within that stage.
  - Any changes to the names?

**Comment by jameshupp** [comment]
Stage vs. status distinction: check.

Names: I was trying to break it down more granularly than this, but I think you're right about MVP. That said, a couple questions:

* Is there a flag for `Awaiting state response` if the analyst leaves questions or comments? Or because the first version doesn't have that level of capability within it, do we have to pull back from that for notifying them? If CMS is going to have the ability to mark the status of the APD for things that happen outside the app (since it'll be necessary for the approval stage), we could still provide a flag here, but we don't have to.
* So no action dates, right? I.e., if the status is submitted, nothing says the date of submission?

If that's how minimal we're going, I think the stage/status distinction starts to be more confusing than it needs to be. Something like this...

```
Draft in progress
Submitted
Under review
Reviewed, in clearance
Decision: approved
Decision: denied
Withdrawn
```

Comments on these:
* `Created` doesn't mean much, since it's evident by the fact that the thing appears in the list, so I want to be clear that this is before any submission. `Draft in progress` is wordier than just `Draft` but given the space I think it's a bit clearer.
* `Review` could read as a request/command; `Under review` (or if you need shorter, `In review`) is clearer that it's in CMS's hands.
* `Reviewed, in clearance` feels like a bit much, but it sounded from our walkthrough conversation like clearance is not necessarily something the states will know. So I want to specify that it's a stage after at least the initial review is done.
* `Decision: denied` sounds harsh to me, but I think "denied" is a better word than "disapproved".

**Comment by jenniferthibault** [comment]
@jameshupp to your questions:

`Is there a flag for Awaiting state response if the analyst leaves questions or comments?` 
 - That's my understanding: if MVP is defined as create & submit, responding to questions falls outside that scope. I _think_ withdrawing also falls outside of that scope, but could be wrong. @jeromeleecms could I get your check on this understanding of where we're going for MVP?

`So no action dates, right?`
 - Also my understanding. 

If my understanding of the above sounds right, our version ready to move to implementation will be:

![dashboard-mvp](https://user-images.githubusercontent.com/11636908/48003743-4aac4c00-e0dd-11e8-8f05-996542a13f0e.png)

**Comment by NAretakis** [comment]
So, MVP will have create &  submit as functionality. But #1081 should let CMS-users manually select additional statuses for the other possible options. #1081 is a temporary thing so that we can actually use all of these statuses on the dashboard for states. Eventually, it will be more automated. Does that make sense?

**Comment by jenniferthibault** [comment]
Yes exactly! I'm going to carry over the rest of the labels James selected above into #1081 as what's available to choose from in that dropdown.

**Comment by jeromeleecms** [comment]
@jenniferthibault The withdrawal functionality was built into the system (reference #849). We would expect the system to change the status to withdrawn, if the state requests it. We should be keeping it in the system unless it actually interferes with our path to MVP.

@jameshupp For the language, we do want a status which notes that the state needs to respond to comments. For the status `Under Review`, it could be construed as misleading since the APD may not yet be being reviewed. If it's Pending `CMS Analyst` (or something like that), it's more accurate.

**Comment by jenniferthibault** [comment]
@jeromeleecms makes sense on withdrawn 👍 

For under review/pending CMS analyst : if it's not yet being reviewed, could the analyst keep it in `Submitted` ?

**Comment by jeromeleecms** [comment]
@jenniferthibault For the state dashboard, I would lean towards the blanket `Pending CMS Analyst.` Analyst don't always pick things up right away because of their existing workload and that extra bit of granularity may have the unintended consequence of causing people to contact the analyst (or others) to ask why their APD hasn't been reviewed yet. I like transparency, but not so much at the cost of potentially creating more work that will further delay a review from getting started. We can always revisit this conversation after MVP if the granularity actually is a value add to the process.

For the Federal side, I would say we keep it the same for MVP for this status (the other parts of the workflow we should use the dropdown). I don't see any particular value for distinguishing between `submitted` vs `pending/under review` unless there is a strong demand for an operational metrics that show the time between Submission Received -> Start of Review. But we can push that conversation to #816.

**Comment by mgwalker** [comment]
One point of clarification on `withdrawn`, the functionality in the app right now is to withdraw the app from review, so that the state can edit it again.  We had discussed that there's a second "kind" of withdrawal, where the APD is essentially closed without review.

I just want to make sure we differentiate between those states.

For MVP, are we saying the document flow in the app is `draft -> submitted -> under review -> clerance -> decision`, and we won't show within the app that it has been sent back for state response?  I wonder if we should display that as a status so that state users can see on the dashboard that CMS is still waiting on them to do something, even if they can't do it in the app.

**Comment by jeromeleecms** [comment]
That's a great point @mgwalker. Do we want to document the future state workflow (like how we did the current state workflow) through another working session?

**Comment by jeromeleecms** [comment]
Couple items:

1) Withdrawn status - keep current functionality for MVP. For future enhancements, allow delete of draft. 
2) State Dashboard Statuses

- `Draft in progress` (State Action)
- `Submitted` (State Action)
- `Pending: CMS Review` (CMS Action)
- `Pending: State Response` (State Action)
- `Reviewed, in clearance` (CMS Action)
- `Decision: approved` (CMS Action)
- `Decision: denied` (CMS Action)
- `Withdrawn` (State Action)

Only CMS Actions should appear on the dropdown for #1081. State Actions will be driven by the certify and submit buttons within the application. 

Pending would be the oscillating status set by CMS review and State Response during the review back and forth.

**Comment by nkkl** [comment]
I would suggest, based on the length of conversation here, that we aggressively simplify for the MVP. How few states can we get to?

**Comment by jeromeleecms** [comment]
Closing this, but will be available for future people in case.
