### ISSUE TITLE
Fix the max width of the left nav

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1038]
When the page width increases, the left nav width also continues to increase with it. Can we limit the left nav at a certain point (it looks like 300px would work) so that it doesn't continue to grow and take up real estate of the page? 

![screen shot 2018-09-26 at 10 39 33 am](https://user-images.githubusercontent.com/21222704/46098327-fecec480-c178-11e8-9747-8583e2ecad9a.png)

**Comment by hbillings** [comment]
Okay, it looks like we're using a homegrown grid pattern, which means:
a) doing responsive design of any kind is going to suck
b) controlling max-widths becomes a fragile thing because suddenly you're doing it on a case-by-case basis rather than using general rules.

We _really_ should be using a standard grid for this, so I'm going to look into what Basscss provides and see if that's helpful. Implementing a one-off grid system is just going to cause us (and future devs) pain down the road.
