### ISSUE TITLE
Synthesize state research findings and share with team

### ISSUE THREAD

**Issue by nicoleslaw** [18F/cms-hitech-apd#104]
Depends on #105

**Comment by nicoleslaw** [comment]
@lauraponce Should we do some mini-synthesis of the interviews before I go, or do you want to wait til you've done onsite research?

**Comment by lauraponce** [comment]
@nicoleslaw I'd love to do this while you're here if you have time. It might be good for Ron to join in as well. 

We should have enough data now with the 5 interviews to start synthesizing. I can start pulling in the stuff we highlighted in the notes docs into a mural so that we can affinitizing. https://app.mural.ly/t/gsa6/m/gsa6/1517598622931/94f500cda7f9a5285b822bb447048254e3698a2a

I am still curious to hear more about what you were talking about with the synthesis you did with Amber in case that would work for this project!
