### ISSUE TITLE
Add total cost of the contract to the "Private Contractor Costs" portion of the tool

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1040]
We need to add a data element to include total cost of the contract within the contractor section.

![image](https://user-images.githubusercontent.com/34279968/46317409-c0297780-c587-11e8-8966-a8673387c3a4.png)

The individual FFY cost would still need to be captured.

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
 ** Don't forget to fill out the LABEL and MILESTONE before submitting. If the issue is for the CURRENT SPRINT, add it to the PROJECT. If the issue is a BUG, FUTURE ENHANCEMENT, or OUTSIDE OF THE CURRENT SPRINT, do not add it to the PROJECT (then delete this line) **

**Comment by mgwalker** [comment]
Should we just collect FFY costs, but calculate and display the total?  Or do we need to capture the total separately?

**Comment by nkkl** [comment]
Let's get design eyes on this too. @lauraponce @jameshupp to start, and pull in Jen as appropriate.

**Comment by jeromeleecms** [comment]
The total cost needs to be separate and does not require any extra math to be done to it. 

For example: A contract could be $100,000 over 5 years. And then the state would report how much they need: $10,000 for FFY 2018 and $20,000 for FFY 2019 and we would know that there is still $70,000 remaining on the contract.

The reasoning here is we don't want to have states just report their current needs without giving us details into the overall need/cost which could put an activity/project at risk. Tracking this total cost is import because if the scope/term/cost changes, it triggers and IAPD update (per our regs). 

Super fancy future enhancement would be to track the cost of the contract during the lifespan (requested vs expended), but we don't have the data fields for this and that def. doesn't move us to MVP.

**Comment by mgwalker** [comment]
This sounds straightforward.  I can mock up some stuff in code and paste it here if that's helpful as a place to start talking @lauraponce @jameshupp.  Or else I can stay out of the way and let y'all work.

**Comment by lauraponce** [comment]
To make sure I'm understanding what numbers are needed in this section, there should be a total cost of the contract (which can span several years and is not limited by the years the APD covers) and the amount of the contract being spent on the two years the APD covers (in this case, 2018 and 2019). Is that correct, @NAretakis?

If so, I could picture that fitting into the Cost row as FFY1 cost, FFY2 cost, and total cost of the contract as the third input field since they are all related monetary amounts. @jenniferthibault does that sound right to you or would you like some more time on this to mock up a more involved concept? 

![screen shot 2018-11-19 at 11 35 44 am](https://user-images.githubusercontent.com/21222704/48730452-41e46b80-ebef-11e8-91cc-42129a1f60e3.png)


@jameshupp is there a better way to describe the total cost of the contract for the label of that input field?

**Comment by lauraponce** [comment]
Based on our conversation, here are the two options I think we talked about:

### A - with all the field labels
![screen shot 2018-11-19 at 2 28 13 pm](https://user-images.githubusercontent.com/21222704/48738954-63e9e800-ec07-11e8-95a9-8977ffe825d8.png)

________________________________________________________________________________________

### B - without the extra field labels
![screen shot 2018-11-19 at 2 28 43 pm](https://user-images.githubusercontent.com/21222704/48738964-68160580-ec07-11e8-8c5e-d8b370f7a708.png)

@jameshupp / @NAretakis preferences?

**Comment by lauraponce** [comment]
@jenniferthibault looking at this from the examples I posted right after you, does it make sense what is being asked with these labels? We had a quick sync about it and @jameshupp helped us come up with the labels, but we wanted to see what it looked like with the secondary field label above and without it to see which way is easy to understand without being cluttered.

**Comment by NAretakis** [comment]
Preference for A - with all the field labels. Looks great!

**Comment by mgwalker** [comment]
Pulling this one into development now.  Thanks y'all!
