### ISSUE TITLE
Add a length of activity section and remove the start date for subsequent milestones

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1041]
Add a start date and end date for activities; Subsequent milestones will only be a single completion date. 

![image](https://user-images.githubusercontent.com/34279968/46318172-73936b80-c58a-11e8-9879-36b388fa9dda.png)

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
 ** Don't forget to fill out the LABEL and MILESTONE before submitting. If the issue is for the CURRENT SPRINT, add it to the PROJECT. If the issue is a BUG, FUTURE ENHANCEMENT, or OUTSIDE OF THE CURRENT SPRINT, do not add it to the PROJECT (then delete this line) **

**Comment by mgwalker** [comment]
So that fancy date range picker Bren added would apply to the whole activity, and then milestones would just have expected end dates?

Can we get a design task on this as well to figure out where the activity date range component would go?  I assume we'd just drop it somewhere in the activity overview panel, but 🤷‍♂️!

**Comment by mgwalker** [comment]
@lauraponce ☝️ Welcome your input too.  😄  Maybe we don't need a whole task for design, we can just talk it out here.

**Comment by jeromeleecms** [comment]
@mgwalker That's right. We "circled" where we thought the date range would fit -- but certainly open to suggestions!

**Comment by mgwalker** [comment]
Oh!  Doh.  I saw the big blue circle and it didn't even click for me what it meant.  Thanks, that makes perfect sense!

**Comment by mgwalker** [comment]
This also has a backend component.  The activity model will need date ranges added.  The milestone model currently has fields for planned start and end dates, and actual start and end dates.  For the sake of keeping the model clean, I think we should remove the start dates and the "actual" end date, since it's never used.  It seems that the actual end date might end up in the summary of _previous_ activities somewhere, but that is a separate model.

**Comment by nkkl** [comment]
Let's tag this with the design label too, since we want design team eyes on this before we jump to code. :)
