### ISSUE TITLE
Build out the text box sizing updates

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1050]
Creating this from design issue #1030 

There will be four sizes for the text boxes where state users input content: extra small, small, medium, and large.

All of the text boxes should have a text area max width of 652px and the heights are:

Extra small: 100px
Small: 200px
Medium: 400px
Large: 800px 

Each of the boxes will be scrollable if the amount of content exceeds the space in the box.

For the sections in the app, here are the text box size designations:

**Program summary**
- Program intro - large
- HIT overview - medium
- HIE - medium
- MMIS - medium

**Results of previous activities**
- Previous activities summary - medium

**Program activities**
- Activity overview - extra small
- Activity description - large
- Statement of alternative considerations - medium
- Performance measures and benchmarks - goals - small
- Roadmap - small
- In-house cost - description - small
- Non-personnel - description - small
- Private contractor costs - description - medium
- Cost allocation methodology description - medium
- Other funding description - medium
- Standards and conditions - small

**Assurances and compliance**
- Federal citations - extra small

**Comment by lauraponce** [comment]
Question for who picks up this issue next — considering the most common screen resolution width is 768, should the max height be below 768 (instead of 800)? Jerome and I chatted about this and wanted a dev's perspective on it.

**Comment by jenniferthibault** [comment]
Catching up on this & #1030. Good stuff!

The norm I'm familiar with for text areas (seen here in the [US Web Design System practices](https://designsystem.digital.gov/components/form-controls/#text-input)) is to set a starting height, then let users adjust the viewable space to make it larger when they need to via the little drag & release triangle in the lower right hand corner of the field. These come as browser-standard for text areas, but @hbillings pointed out that we're using divs here, which may have accessibility concerns. (Want to discuss more about this @hbillings ?)

If we keep going this way to make the initial adjustment I think you're right that an 800px height setting for largest is too much vertical space. Since 100px is also relatively a lot of space in a ~700px tall experience, and the single-line text inputs will be even smaller, I'd suggest a slight re-labeling:

- Small: 100px (6.25rem)
- Medium: 200px (12.5rem)
- Large: 400px (25rem)
- Extra large: 600px (37.5rem)

**Comment by hbillings** [comment]
To expound further on the `div`/`input` point @jenniferthibault raised, the rich text boxes we're currently using are all rendered as `div`s instead of `textarea`s or `input`s. This is less than ideal for screen readers, in particular, because we have to use ARIA attributes to re-create the native HTML functionality of `textarea` and `input` elements. This would be less of an issue if ARIA attributes were supported reliably, but screen readers vary widely in their capabilities to understand and correctly parse ARIA tags. I _think_ we're using some kind of plugin to generate the rich text editors, so this _might_ be as simple as swapping it for a plugin that renders better markup (I haven't dug into the code, so I'm not sure how much control we have over the markup in this particular plugin). Another option could be to drop the RTE for MVP.

I'd like to do a full [accessibility audit](https://accessibility.18f.gov/checklist/) in the near future to determine the severity of some of these issues.
