### ISSUE TITLE
Layer 1 State Dashboard

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1110]
If all we have is the APD tool (not being able to submit the APD through the application itself), what does the dashboard look like? 

### This task is done when...
- [x] Design is updated to reflect the following functionality:
     - [x] Users can find an existing document and edit it from the dashboard
     - [x] Users can create a new APD from the dashboard
     - [x] Users understand what's possible in the current status of the app, and what next steps will be required

**Comment by jenniferthibault** [comment]
Updated criteria above to reflect my understanding

**Comment by jenniferthibault** [comment]
Here's what I'd propose for the new dashboard design that reflects only the ability to create & edit APDs in the system:


**An empty state before users have created any documents:**

![dashboard-layer1-null](https://user-images.githubusercontent.com/11636908/48501559-79c46b00-e80b-11e8-9652-da3d0030a734.png)
- Added a text field as an introduction to the product. @jameshupp need you here for content!
- Created microcopy for the null/empty list state (also @jameshupp !) 
- I moved the "Create new" button to be more grouped more centrally to where the list is

**Once documents have been created:**

![dashboard-layer1](https://user-images.githubusercontent.com/11636908/48501261-dbd0a080-e80a-11e8-999e-00901920d335.png)

- I think we should take up a good amount of space for each document in the list, since otherwise it's be pretty sparse and could look unfinished.

**Comment by jameshupp** [comment]
Clarifying questions:

- Are there "documents" other than APDs here? If so, then that label's great. If not, `Your APDs` or `[state name] APDs` would be better.
- Do docs ever expire from the list? If either "someday but not yet" or "no", then that's that. If "yes" we might even want to title it `[state name] APDs submitted since YYYY` or `[state name] APDs applicable to YYYY-YYYY`.

Beyond that:
- This default placeholder copy is good, again as long as `documents` is as specific as we want to get. Otherwise let's say `APDs` instead. We can spell out `Advanced Planning Document(s)` in the intro. I want to make sure users have as much specificity as we can give them about what they're looking at.
- Once we get those first two questions answered, I'll draft intro copy.

**Comment by jenniferthibault** [comment]
My understanding, with ~95% certainty:

`Are there "documents" other than APDs here?' 
  - Nope, or maybe "someday but not yet"
`Do docs ever expire from the list?`
  - Either "someday but not yet" or "no" :) 

👍 to using more specificity, I'll use `You have not created any APDs.` in the null state.

**Comment by lauraponce** [comment]
I was under the assumption that for layer 1 dashboard we'll want to have both APDs and contracts in the list. Or are we moving that into layer 2 functionality and keeping layer 1 to just the APDs for simplicity? @NAretakis can you add your two cents on this one?

For expiring docs from the list, agreed that it's a someday, but not yet. We actually have an issue to track this work for figuring out what to do in #842.

**Comment by NAretakis** [comment]
Layer 1 dashboard can just be APDs for simplicity (APD builder layer). 
Layer 2 should include contracts (as separate rows within the dashboard). 

For expiring docs, it is "someday, but not yet". And a big running list of docs is good.

**Comment by NAretakis** [comment]
We're very close on this. All we need to do is remove the status fields from view, and move the create button, does that seem right @jenniferthibault 

If so, are we ready to close this issue and spin up a dev issue to do those things?

Current dashboard is below:
![image](https://user-images.githubusercontent.com/34281281/48718961-a0065400-ebd9-11e8-9ce3-66728a363985.png)

**Comment by jenniferthibault** [comment]
Almost! The third checkbox in the issue description above is still outstanding. We need @jameshupp 's final text to place in the mockups [above](https://github.com/18F/cms-hitech-apd/issues/1110#issuecomment-438754757) that will address that need.

If we close this now, then that outstanding text will be a blocker for devs to implement

**Comment by jameshupp** [comment]
Is this ... too long? It feels long, but it doesn't feel like too much information.

`Use the eAPD to build and manage your state’s Advanced Planning Documents. Follow the instructions to enter relevant information. Save your work in progress and come back to a draft at any time. When you’re finished, submit to CMS. Each APD your state has created in the eAPD will be listed here for you to review, edit, or check for status updates from CMS.`

**Comment by jenniferthibault** [comment]
It's not too long at all! Takes up the exact same amount of space as in the mockup above. I'm not sure it entirely does what we need it to do at this point though — here's where I see openings:

- `When you're finished, submit to CMS` — Where and how? (In layer 1, "submitting" is not a step users can take in the app.)

- `or check for status updates from CMS.` — This functionality also isn't possible in layer 1

Does that line up with other folks' expectations?

**Comment by NAretakis** [comment]
@jenniferthibault this looks good. "When you're finished..." is good to include for now, and we'll probably just make a minor edit when we know what will actually happen when someone is finished. 

For the status update piece, we won't have that as part of layer 1. So, our options are to put it in now as placeholder text, or leave it out since it doesn't come into play for layer 1.

**Comment by jameshupp** [comment]
Okay, reordered just a bit, given these updates (apologies, got myself a bit out of order on what was possible when).

`Use the eAPD to build and manage your state’s Advanced Planning Documents. Follow the instructions to enter relevant information. Save your work in progress and come back to a draft at any time. Each APD your state creates in the eAPD will be listed here for you to review or edit. To submit an APD, open it and select Save as PDF, then send the document to CMS just like you've done before.`

**Comment by jenniferthibault** [comment]
With this text in place:

![dashboard-layer1-null](https://user-images.githubusercontent.com/11636908/48806440-52c4d800-ece8-11e8-90e6-0e60ab4d19f1.png)

![dashboard-layer1](https://user-images.githubusercontent.com/11636908/48806441-52c4d800-ece8-11e8-9e7e-6c3c47953dd6.png)

Ready for moving to development?

**Comment by NAretakis** [comment]
Looks great. Ready to move forward. When we get to fancy dashboard, this will be perfect for us to build upon.

**Comment by jenniferthibault** [comment]
Moved to implementation in #1161 🎉

**Comment by NAretakis** [comment]
closing this issue, as this work has been handed to the dev team in #1161
