### ISSUE TITLE
Make form layouts more consistent between sections

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cms-hitech-apd#1116]
Carried forward from #1082

Challenges with the current style and implementation:
- Current arrangement of labels & fields isn't predictable — slightly undermines the confidence in the experience and makes it hard to scan
- The same information is styled with different layouts in different parts of the form (sometimes the label is above the field, sometimes beside it)
- Text areas have arbitrary widths

![screen shot 2018-11-09 at 6 52 10 pm](https://user-images.githubusercontent.com/11636908/48294180-c47f6500-e450-11e8-831a-901c3c0c0a24.png)
![screen shot 2018-11-09 at 6 53 11 pm](https://user-images.githubusercontent.com/11636908/48294181-c47f6500-e450-11e8-8184-19ee9923380f.png)

### This task is done when...
 - [ ] A consistent design layout and pattern has been defined
 - [ ] That pattern has been created in symbols in the Sketch files
 - [ ] Each instance where a change is needed has been identified and mocked up by design
 - [ ] An implementation issue has been created for the development team (that includes adding the pattern to storybook as a criteria for "done")

**Comment by hbillings** [comment]
Some specifics of form layout weirdness I noticed:

This bold div text should be a fieldset legend because it refers to grouped checkboxes:
<img width="617" alt="screen shot 2018-11-26 at 5 28 47 pm" src="https://user-images.githubusercontent.com/509309/49115202-5eb81900-f257-11e8-85cf-d1754a9fc877.png">

These numbered inputs should be ordered list items, and the radio buttons should be grouped in a fieldset with a legend (the legend could be set to `sr-only` to make it only available to screen readers):
<img width="569" alt="screen shot 2018-11-26 at 5 41 31 pm" src="https://user-images.githubusercontent.com/509309/49115215-6f688f00-f257-11e8-903c-ddebc31d95cd.png">

This pattern should incorporate the text in the "Benchmarks" place as a heading or label rather than just hanging out in a div:
<img width="411" alt="screen shot 2018-11-26 at 5 53 49 pm" src="https://user-images.githubusercontent.com/509309/49115286-a5a60e80-f257-11e8-9378-1299355a38db.png">

This pattern should be broken out of the table it's in (the table is only used for layout, which is not a semantic use of tables):
<img width="525" alt="screen shot 2018-11-26 at 5 55 39 pm" src="https://user-images.githubusercontent.com/509309/49115386-e6058c80-f257-11e8-9f2b-00383d278776.png">

**Comment by NAretakis** [comment]
OBSOLETE
