### ISSUE TITLE
Alignment issues in the Executive Summary

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1136]
The columns move independently and don't line up as the width of the browser is resized:

<img width="637" alt="screen shot 2018-11-16 at 4 31 03 pm" src="https://user-images.githubusercontent.com/21222704/48653916-753fb400-e9bd-11e8-8165-b776147a3df0.png">

**Comment by hbillings** [comment]
The FFY data is currently in two rows of divs. It should be in a table instead, because a screen reader is going to see this as, "FFY 2019 / FFY 2020 / Total / $650,000 / $650,000 / $1.3M."

One fix for this bug would be to stick the FFY data in a table, and then give the table a set number of columns to take up. That would probably size them all the same under most circumstances.

(One thing we should fix while we're in there is that these elements should all be text elements. “Core Activity 1” should probably be an H4; “Program Administration” should probably be an H5.)

**Comment by jeromeleecms** [comment]
This should be migrated into a table and it will solve the alignment issue.

**Comment by NAretakis** [comment]
This will be resolved as part of #1457.
