### ISSUE TITLE
Previous Activity Federal totals is not summing HIT+HIE+MMIS. 

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1140]
Previous activity section Federal Totals section is not summing HIT+HIE+MMIS. It is just summing MMIS amounts.

![image](https://user-images.githubusercontent.com/34281281/48714231-7811f300-ebcf-11e8-987a-6e69c5465a32.png)
![image](https://user-images.githubusercontent.com/34281281/48714316-b3142680-ebcf-11e8-8f2e-bfb9de9fd01e.png)

FFP Approved in the section below should read: $1,028
FFP Actuals in the section below should read: $626

![image](https://user-images.githubusercontent.com/34281281/48714205-692b4080-ebcf-11e8-8a36-bdb8370a308f.png)

### This task is done when...
 - [ ] bug is squashed

**Comment by mgwalker** [comment]
I assumed that table was just for MMIS since it's under the MMIS header.  @jenniferthibault if this table is supposed to represent a grand total, should it get its own header?

See screenshot here: https://github.com/18F/cms-hitech-apd/pull/1129

Also I just realized I was premature in merging that pull request.  😬  I saw it was approved and went for it.  Sorry for not waiting for design and product to weigh in, could have prevented this bug from showing up.

**Comment by NAretakis** [comment]
All good. The table should be a Grand Total, so maybe Grand Total header should cover it. We'll eventually come back and test this, but if we do Grand Total that sums everything, that should get us in good shape.

**Comment by jenniferthibault** [comment]
Ah, I also misunderstood the logic and thought it was only for the MMIS table.

Adding a specific header that replaces the top row could help, as you both were describing. Here's what that could look like:

![screen shot 2018-11-19 at 11 44 59 am](https://user-images.githubusercontent.com/11636908/48723615-15cbe900-ebf5-11e8-8ebd-79018b95f81f.png)
