### ISSUE TITLE
Refine the language around attachments

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1142]
### To-do

- [ ] Clarify when/where/how to add attachments

### Background
During the [8th round of usability testing](https://docs.google.com/document/d/1F8deUxl2zuNiXoKHv05cu4o3oueqP7Te9girOcsyEw8/edit), some state users were unclear about when and how to add attachments. Currently, people are able to add a contract attachment in the Private Contractor Costs section, and they can add pictures within the rich text boxes by clicking the image icon. 

Some of what we heard was:

> Is there a way for us to add attachments that go along with the narrative?

> I would like to add attachments for each section.

**Comment by jameshupp** [comment]
Two questions for when I'm able to pick up this issue.

1. It sounds from the research quotes like people would like to be able to add attachments more frequently than the app currently allows. It's not in the plans for layer one to do that, right? This is just about providing more clarity?
1. If the issue was confined to confusion about how to do this when appropriate, I'll focus just on the ones where it _is_ possible. If people thought it should be but it wasn't, we might want to add some content in those other sections to clarify that it's _not_ possible. Are there sections where that was an issue?

**Comment by beparticular** [comment]
Closing, not in Cake Layer 2 and specific to this test.
