### ISSUE TITLE
Update content inconsistencies with terminology and refine some language (from round 8) 

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1145]
### Background

From the [8th round of testing](https://docs.google.com/document/d/1F8deUxl2zuNiXoKHv05cu4o3oueqP7Te9girOcsyEw8/edit), state users brought up some inconsistencies with the language and pointed out some areas of confusion.

### This task is done when...
 - [ ] When should we use the term "project" vs "program"? The app seems to use them interchangeably in some places. 
 - [ ] In the In-House Cost Categories section, there is a Salary Amount box that counts benefits as part of the salary. This wasn't clear to users because there is nothing telling them that. How can this be clarified?
- [ ] People used the phrases "save as" and "print out" when talking about turning the APD into an exportable doc. What is the clearest way to refer to saving and printing so that it makes sense to the most people?

**Comment by jameshupp** [comment]
I'm just gonna leave comments here about each of the checkboxes.

1. The project vs program distinction really comes down to one section, `Key Personnel...`. That section uses `project` repeatedly, but it's clearly about people involved in activities covered by the APD. Those activities are _Program Activities_ so I think we can switch to `program` without any trouble. The one exception: there is a definition of `key personnel` that reads as somewhat technical. Is this first sentence set in stone, or can we change `project` to `program` here @NAretakis?

> Key personnel are individuals involved with all activities within this APD, or are involved with governance, coordination, stakeholder decision-making, oversight, and/or **project** performance. 

2. Two solutions for how to clarify that salary includes benefits. Either call it `total compensation` or write a helpText note to specify that benefits are included in salary. The first option is more direct so it's my preference, but it could still leave people confused on whether things like bonuses and leave time are included (as opposed to health care and retirement contributions, which certainly are). Better to try one of these options rather than nothing, but open to input about which. Also looking for input from Nick/Jerome here, if they know the answer.

3. Currently says `Save as PDF`. This feels right to me. That it is printable will be immediately apparent when they click the button, but I'd rather not make anyone feel like they're committing to that act without seeing how it's going to render. This does raise a question for me: does the app force the print dialogue to select PDF as the target for the print operation? Or is that just because my computer is not connected to a printer and that's my default? @mgwalker

**Comment by mgwalker** [comment]
3 - Because you don't have a printer.  We can only make the dialog pop up, we can't control anything else about it.

**Comment by jeromeleecms** [comment]
1. Good pickup @jameshupp! This term out of some of our regulations (and mirrored later down in the Standards & Conditions portion of the app). How about something like this:

> Key personnel are individuals involved with all activities within this APD, or are **directly** involved with governance, coordination, stakeholder decision-making, oversight, and/or **performance of the activities impact on the state's Medicaid program.**

This second part of the sentence expands the concept of the Key Personnel outside of the APD, but keeps it grounded on the activities' affect on Medicaid (as a program).

2.  The current APD template, refers to this as "Cost with Benefits." Can we rename the form label and include the help text which explains what "Benefits" are/are not?

**Comment by jameshupp** [comment]
Thinking about this in context just a little more, I think we need to add a bit to the instructions alongside the second change. The `Cost with Benefits` (or `Salary` as it is now): is that total across any number of FTEs? Or is that per FTE? I assume it's total, since it'd be hard to figure that out for partial FTEs, but I want to be sure.

Once this is set I'll add the appropriate contextualizing info to the helpText at the start of the section and PR the changes.

**Comment by jeromeleecms** [comment]
@jameshupp I think I get what you are asking... but if I'm way off base, I think a 2 minute chat can clarify this.

So in the current form:

![image](https://user-images.githubusercontent.com/34279968/54291399-ba3db680-4569-11e9-9ecb-7eefa71ec7b6.png)

The `Salary` (or whatever future name we choose) is per FTE and the app will calculate the total cost based on the number in the FTE column.

![image](https://user-images.githubusercontent.com/34279968/54291443-c7f33c00-4569-11e9-82b8-01a1c67d857b.png)

I vaguely remember in user testing that this was a confusing point. A state tried to put in the total cost for all FTE's in first field and then the number of FTE's associated with that cost (which made the calculated number way bigger that they were intending).
