### ISSUE TITLE
Comparative analysis of similar apps and interfaces

### ISSUE THREAD

**Issue by nicoleslaw** [18F/cms-hitech-apd#115]
Compiling screenshots here: https://drive.google.com/drive/folders/1TvRBUU8FBfOmCYvTygEmn11DX2LIiTeg

**Comment by nicoleslaw** [comment]
Maybe useful for us! http://harmony.intuit.com/

**Comment by lauraponce** [comment]
So far, some of the apps that have come up as being useful for comparison are:

- TurboTax
- Google docs/forms
- Editorially 
- Dropbox Paper 
- Airbnb (for the hosts)
- C2
- FOIA portal

**Comment by nicoleslaw** [comment]
Sharing here for @brendansudol too: Added Editorially and Dropbox Paper screenshots to our [comparative analysis folder](https://drive.google.com/drive/folders/1TvRBUU8FBfOmCYvTygEmn11DX2LIiTeg). I had to scrape the Editorially ones from Google images, but I think you’ll get the idea.

**Comment by lauraponce** [comment]
The [comparative analysis](https://docs.google.com/document/d/1LDfKqYH-Ynp8o2rai30n9C-nwTPL-0U_ASLaPg4hObI/edit?usp=sharing) is just about done! The one section I wasn't able to fill out is the alerts section. @nicoleslaw since you're more familiar with Dropbox Paper, can you add a few notes about how the alerts work in the doc? I couldn't quite figure it out from the screenshots.

**Comment by nicoleslaw** [comment]
All set on that section! I wish I could emoji-anything to your message 😄  ✅
