### ISSUE TITLE
Create prototyping sandbox

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#122]
@brendansudol / @mgwalker to stub out more

**Comment by mgwalker** [comment]
I think the intention here is we need a place where the app is deployed in a not-necessarily-stable condition, without the rigors we apply to pull requests into `master`.  @brendansudol what was your thought?

It might be that we just need to do manual deploys into personal sandbox accounts to solve this (only slightly more complicated for Brendan 😬 ).  If we deploy on every push to a non-master branch, we'll end up stomping on each other's deploys.  If we setup a staging branch and deploy from that, we should probably have rigorous status checks on that - otherwise the status failures build up and then we have a gazillion things to fix before we can merge to master.  (We should consider having staging/release deploys anyway, so we can have a "frozen" app for user testing - don't want features or behaviors changing halfway through!)

**Comment by brendansudol** [comment]
my thoughts are: a super simple, lightweight React site, made with `create-react-app` so we don't have to futz with js config, that's hosted on Federalist and allows to quickly experiment with half-baked UI ideas / experiments for validating hypotheses; things will mostly get thrown away, but some stuff may get migrated into our main app

i got this set up here: https://github.com/18F/cms-hitech-sandbox

here's the [url](https://federalist-proxy.app.cloud.gov/site/18f/cms-hitech-sandbox/) and here's an [example page](https://federalist-proxy.app.cloud.gov/site/18f/cms-hitech-sandbox/#/example) 💥
