### ISSUE TITLE
Issue warning to user if APD has been edited, prior to leaving the APD creation page

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1237]
From the conversation in #1226, the app currently tracks whether or not changes have been made to the  app content and a Boolean `dirty` which indicates if the content of the APD has changed. 

If a user tries to leave the app before saving & `dirty` reports that the APD has changed, than the system should prompt the user that leaving the page will result in changes not being saved.

This functionality should only be on if the APD is in draft/editable. It should not be available to users once the APD has been submitted or a decision on the APD has been made.

### This task is done when...
 - [ ] Any action that navigates away from the APD creation page should issue a warning that the user will save any unsaved changes
 - [ ] Warning is consistent with design system

**Comment by jenniferthibault** [comment]
A question for Future Greg, the @mgwalker of tomorrow:

Instead of warning someone that their changes haven't been saved before they navigate away, what would it take to "auto-save" the progress after a user made a new change in the APD? That way, we might be able to prevent from loss caused by both browser events and app events, AND not have to warn people.

What are the complexity/dev time tradeoffs of that solution instead of warnings?

I was about to ask these questions in the PR #1322 , but figure they'll be easier to find here later.

**Comment by mgwalker** [comment]
@lauraponce also suggested that!  We discussed this briefly in Slack and in the pilot planning part of some of the working time yesterday.  The summary, from memory, which is questionably trustworthy:

- Automatic saves introduce a potential problem if multiple users are simultaneously editing an APD because saves are "last in wins" (that is, the most recent save overwrites everything before it)
- We will not support simultaneous editing for the pilot, but we also won't make it technically impossible

So I think we didn't answer this question in particular, but it seems like it's okay to have automatic saves given the second point.

@brendansudol and I talked about auto-saving before (assuming a world where there is either only a single editor at a time, or where changes are synced between editors in realtime - my ideal!), and we had a few thoughts about when an auto save might happen:

- **on a timer, maybe every few seconds**
   - because we do a "dirty" check before actually sending anything to the API and because we only send the changes, this shouldn't be very disruptive
    - however, it would also capture a bunch of edits that maybe the user didn't want saved, in a way that might feel unpredictable or arbitrary
    - pretty easy, because we just need to setup a global timer
- **whenever a field is blurred**
   - this one is harder because we'd have to hook the blur events for all the editable fields; we wrap a lot of those is our custom components but not all of them
   - hard just because I'm not sure I'd ever be comfortable that we'd hooked up all the fields 😬
- **whenever anything is changed**
   - this one creates a *LOT* of network traffic because every keypress in a textbox would send stuff to the API
   - we can mitigate the network traffic by "debouncing" the API calls; that is, only send them every few seconds, and only send the most recent one
   - has the same problem of potentially capturing edits that the user didn't want, but if it's continuous (instead of a timer), that feels like it fits my mental model of modern document editor behavior
   - really easy because we already capture every change, down to the keypress - so we'd just add the API call and be done
- **when the user navigates away**
   - if they navigate away on a browser event, we actually can't - there's no guarantee that the browser will send our API request
   - I'd call this one impossible

So if we were to implement automatic saves, I'd probably suggest "whenever anything is changed" for now with a healthy debounce in there to prevent sending gobs and gobs of network traffic.  We might also want to revisit our save notification - right now it's a pop-up toast, but that'd get obnoxious if it popped up every few seconds.  Maybe a "last saved" timestamp somewhere?  Perhaps on the sidebar?

**Comment by jenniferthibault** [comment]
@mgwalker thank you so much for all of this!! And sorry to have asked you to recap a conversation that happened yesterday. 

It sounds like you & Laura went through these options and decided that the "warn before exiting" was the more appropriate option for this point pre-pilot than any auto-saving, is that right?

If so, I am not trying to second guess that, I am good just knowing that we've talked through the options before assuming exit warnings were the "right" way to go. 👍

**Comment by mgwalker** [comment]
I don't think we actually came back to answering whether to auto-save or to keep the warning prompts, just that we wouldn't support simultaneous editors.

**Comment by jenniferthibault** [comment]
GOT IT! We're not operating on a lot of research/usability data at this point (and Laura is OOO today), so I think we should go with our first hypothesis — @jeromeleecms or @NAretakis do you have a preference for direction between the warnings or auto-saving based on Greg's info above?

**Comment by NAretakis** [comment]
I think it seems simpler to just go with the warnings, especially for the pilot.  I do think we can come up with an auto-saving option that will work, but I think it is a little tied to multiple users, various status, etc. Not to mention, our users to date are used to having a "save" button. 

Long way of saying, I think warnings are good for the pilot, and then maybe with layer2, we look at implementing an auto-save option.
