### ISSUE TITLE
Make dashboard page reflect eAPD Builder concept using CMS Design System styles

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cms-hitech-apd#1268]
_Part of #1250_

For completion of Layer 1, the site will be positioned as an eAPD builder tool. In order to get the dashboard page to reflect this functionality accurately, we could make slight temporary tweaks to reign back some of the status & interaction features we were thinking about previously. 

While doing this, we also have the opportunity to update the page's styles and layouts to use the [CMS Design System](https://design.cms.gov/) styles.

### This task is done when...
 - [x] We agree on a new mockup of the dashboard page
 - [ ] A new issue has been created for development changes for the concept.

 **Current dashboard page:**
![screen shot 2019-02-06 at 11 08 34 pm](https://user-images.githubusercontent.com/11636908/52389985-2c4f4700-2a64-11e9-9d90-885d8067a34b.png)

**Comment by jenniferthibault** [comment]
A few ideas:
- Given that we won't have a large backlog of APDs for the pilot & layer 1, I think we can safely drop the side nav here, and only use one top navigation.
- If we add a little more structure to the text, the instructions are easier to spot!
- We can use the [Review pattern](https://design.cms.gov/patterns/review/) from the CMS design system for the list of documents here (woo!) I'm not sure if it would let us customize it to use the document icon with it – if that adds complexity I'd love to discuss other tactics @hbillings 
- The design system doesn't stipulate a standard footer, so I grabbed the basics from a quick scan of other HHS/CMS sites. We can edit this in the future once we have more clear needs.
- The gray rectangle is a placeholder for either a site title or branding, when we know what that should be


![layer 1 dashboard - design system](https://user-images.githubusercontent.com/11636908/53917882-9511eb00-4033-11e9-9e87-0c4d6e2d9ea3.png)

Thoughts @NAretakis @jeromeleecms @lauraponce @hbillings ?

**Comment by mgwalker** [comment]
Whoa, that is lovely.

**Comment by jeromeleecms** [comment]
@jenniferthibault Nice and clean!

1) Header - do we need to have a consistent header after a user logs in to the app (I saw you indicated a one layer nav)? Right now, we have "Manage My Account", "My Dashboard", and "Logout" but if/when we add new apps how would the header scale? I couldn't find any design pattern in the CMS design system, but the USDS 2.0 beta has this guidance: https://v2.designsystem.digital.gov/components/headers/

Or would we keep adding the buttons to the top? (Or follow the new nav structure in the header mockup) 

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/d882cf9b-df89-4a34-894d-a8dd60f93f75)

2) All in favor of dropping the side bar too. I think the dashboard should only contain active documents / submissions and a list of all documents (active and previously submitted) can be contained in their own page (related to my question about 1 on how we would scale the options)

3) I'm good with the review design pattern too. The red button on the current page is great for warning users. but really pulls your attention away from the help text (which, yes is easier to spot!). 

4) Also poking around, I found this about the footer in the USDS design system: https://v2.designsystem.digital.gov/components/footers/ (Not trying to split our adoption of the CMS design system, but since the CMS design system borrows heavily from the USDS v1...)

**Comment by lauraponce** [comment]
Love this new dashboard!

A couple questions that I have are:

- What does Edit do/where does it take you? Does it let you edit the APD and open it up or is it to edit the name of the APD?  
- Would Remove delete the APD in one step? Or should there be any "are you sures" or undos in place? I feel like having one or the other would be a good safety net since it could be clicked by mistake.
- What does Create new do/where does it take you? On the old (current) version of the dashboard, clicking Create new adds a new entry in the APD list then immediately drops you off in the builder. 

Maybe a smoother experience would be: 

Select `Create new` --> new entry is added to list where it can be named --> can select the APD from the list to go into the builder but doesn't automatically take you there

**Comment by jenniferthibault** [comment]
Thanks all for the great feedback! Discussion and a few questions (❓) below

To @jeromeleecms 's points: 

**1. Header / top navigation:**
I've been sort of dancing around this, since the design system doesn't have a recommendation or pattern for it. It has also seemed like the area we've been adding buttons to is acting like it should be a nav, but the way we've been adding buttons is more as-needed than driven by plans for scale. I don't really know much about how this app intends to scale, so can't answer all of those questions at this point. Feels like I should split that into another smaller issue so we can figure it out without holding up the dashboard here!

**2. + 3.** ✅ 

**4. Footers**
Yes, the [US Web Design System](https://v2.designsystem.digital.gov/components/footers/) does have a suggested footer pattern! ❓**But do we know what needs to go in a full footer?**

When looking for patterns, my approach so far has been:
 - 1. Check the CMS Design system. If no, 
 - 2. Check other CMS / HHS / sites and look for something formally consistent across them. If no:
 - 3. Use the most simple version of any common items across the above. If there are no commonalities:
 - 4. Make something custom.
But I could change that to make looking to the USWDS layouts the preferred step 4, I think that would make sense and would be better than custom! The CMS Design system was based off of the USWDS, so it would still be in the family, even if we aren't importing the USWDS code to make it work. 

___

To @lauraponce's questions: 

**1. Edit**
Yes, I'd imagined that it takes you into the builder, but I think your instincts are quite right that it's different than how the pattern behaves in the add/edit mockups, and moving you between pages should feel different than editing something on the same page. Let's try going back to having the title be the link into editing the APD in the form builder.

![Screen Shot 2019-03-08 at 7 49 42 PM](https://user-images.githubusercontent.com/11636908/54063597-5ae34d80-41db-11e9-951b-d0db40349058.png)


**2. Remove**
Also a good flag! I could see how `Remove` might also sound like you're removing it from view, and not actually deleting it. We can use a few other signals to tell people they're in the DANGER ZONE. I wonder if using the word is "Delete" is enough — and I'd like to usability test this before adding something heavier, like an interaction to confirm. 

![Screen Shot 2019-03-08 at 7 50 04 PM](https://user-images.githubusercontent.com/11636908/54063609-70587780-41db-11e9-9b83-5e6953a34cbe.png)

**3. Create new**
I had imagined that it did the same thing as before (makes a new one and immediately drops you into the form builder) which is why the button position is at the top instead of the bottom of the list. 
❓ This makes me wonder — how are APDs named? Are they named by our system automatically? Or are users supposed to be able to name them manually at this point? This design was assuming the system named them automatically.

**Comment by mgwalker** [comment]
They are named automatically, using a format like `(state abbreviation)-(creation date)-HITECH-APD`, so eg `NY-2019-03-11-HITECH-APD`. #1143 has the details, and PR #1365 is an implementation of creating that name on the backend.

**Comment by jeromeleecms** [comment]
*Headers:* Totally on board, no need to delay the dashboard. Thanks for spinning up the issue!

*Footers:* General hierarchy for decision making makes sense -- :thinking-face: we should include the caveat that we review the MacPRO styling/structure with a little heavier weight for (ii). We are grouped in that family of products, so our branding and styling should have similarities (#1126 is in the icebox currently) unless it deviates significantly from the CMS Design System. Then we'd have to make some judgement calls...

That being said, I don't have access to MacPRO (I'll have to request access) but in the meantime, we might have to wait until @NAretakis can weigh in/grab a screenshot for us. I looked at some of the other tools we use and footers are all over the place.

**Comment by mgwalker** [comment]
One question: the background here is all white.  Is that going to be the direction for the rest of the app, or will we still have the gray background?

**Comment by jenniferthibault** [comment]
Yes! Except for... login/account maintenance flows, so that there's a visual cue that something is different about that part of the experience. 

But for the form builder & dashboard/landing page: yep! Removing these background/foreground containers is one tactic to creating more visual simplicity.

**Comment by lauraponce** [comment]
@jenniferthibault to your questions from last Friday —
1. & 2. Agreed! ✅
3. @mgwalker if the docs are named automatically with `(state abbreviation)-(creation date)-HITECH-APD` is it easy enough to parse that and pull out the state name, date, and doc type so that it looks like `State date APD` in the list (which is easier to read at a glance as regular text than the hyphenated file name/ID)? And then the automated ID would go right below like this as @jenniferthibault mocked up in #1346:

![image](https://user-images.githubusercontent.com/21222704/54246799-9b9cd880-44f3-11e9-9774-67f66fe1bf52.png)

**Comment by mgwalker** [comment]
@lauraponce Good news!  😄  We already have the state ID and years covered as data separate from the name.  For the pilot, since everything is an APD, we can just hard code that one in.  Done!

@jeromeleecms For the APD year, we have a list of the federal fiscal years that the APD covers.  In the mockup @lauraponce posted above, should we display the year the APD was created (calendar or fiscal?) only the first covered year, all of the covered years (`2018, 2019, 2020` - this is how we have it now and it feels kinda clunky), or a start/end combo (`2018-2020`)?

**Comment by jenniferthibault** [comment]
I'm going to carry the comments about naming and IDs from here over to #1346 so that we can keep the implementation issues small. I'm starting to create an implementation issue for this work, and will crosslink to it & close this when done!

**Comment by jenniferthibault** [comment]
Moved to implementation in #1378 !
