### ISSUE TITLE
Create a UX for users to change their passwords

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1274]
Users need to be able to change their passwords.  F'real.

There is no API support for this, either.

### This task is done when...
 - [ ] users can change their own passwords

**Comment by jenniferthibault** [comment]
@mgwalker got this started in #1357. I had a lot of design notes, so pulling that discussion into here in case any of it needs more discussion:

> - Adds a top button to view your own account - in the preview link, clicking that button will be the only way to get to the page for editing your account

>  <img width="955" alt="screen shot 2019-03-06 at 6 38 46 pm" src="https://user-images.githubusercontent.com/1775733/53923846-55e99700-403f-11e9-8f8c-0463dd36f949.png">

This makes sense for now since our available functionality is limited. Could we call it `Manage account` to mirror [Login.gov's IA](https://login.gov/)? I'd wager that theirs is informed by some data, which is more than we can say for ours right now.

____

> - which takes you to this fancy-pants account editor (the pants aren't really that fancy) - using the *actually* fancy-pants CMS design system buttons and alert box

>  <img width="529" alt="screen shot 2019-03-06 at 6 41 54 pm" src="https://user-images.githubusercontent.com/1775733/53923923-921cf780-403f-11e9-84bc-ea8d4985d76f.png">

The [Form label with hint text](https://design.cms.gov/components/form-label/) feels like a better fit here instead of the alert because it's specific to that field, and lots smaller.

This components in the mockup I've proposed below also include the:
- [Text field component](https://design.cms.gov/components/text-field/) ,
- [Masked field component](https://design.cms.gov/components/masked-field/) for the Phone number field, 
- [Checkbox component](https://design.cms.gov/components/choice/) at the small size variant. 
-   `ds-c-button--transparent` [modifier](https://design.cms.gov/components/button/) for the "Cancel" button (which replaces  "Back")

![account-manage](https://user-images.githubusercontent.com/11636908/53928249-673e9d80-4057-11e9-834e-78bb9819012d.png)

______
> - and adds a new password meter

>  ![passwords](https://user-images.githubusercontent.com/1775733/53924072-2edf9500-4040-11e9-84e1-d74da8947dde.gif) 

In order to avoid the jump in the experience when the password meter hides/displays, we could instead have it always displayed (but in "empty" state) until the user starts typing in the field.

![screen shot 2019-03-06 at 9 34 04 pm](https://user-images.githubusercontent.com/11636908/53928304-9d7c1d00-4057-11e9-8529-e9f9a059ae4a.png)

________

Is it also possible to include some validation for when the changes are saved? Again following [Login's model](https://login.gov/help/creating-an-account/how-do-i-create-an-account-with-logingov/), placing the `success` state alert at the top of the page: 

![account-manage-success](https://user-images.githubusercontent.com/11636908/53928467-390d8d80-4058-11e9-8e45-a7e7246ab823.png)

I'm not sure if we have in-line field validation at this point, but if we do I'm glad to mock up some error states for this flow

(👀 at overall concept, @jameshupp @lauraponce )

**Comment by mgwalker** [comment]
Checks to all of that.  I'll make those changes first thing.  I'll hold off on validation for now, but FWIW if it'd be useful, we could pair and look at different things live.

I had looked at the form fields in the design system and backed away because I didn't want to introduce validation in one place but not anywhere else.  I feel much more comfortable with you making that decision. 😄 But this form (and the other two account management type forms) seem like ideal candidates for adding validation because they're pretty simple.

On this form, there are only 3 error states:
1. if you change the email address, but the new one is already associated with a different account
2. if you change the phone number to more than 10 digits (other characters are stripped out)
3. if you change the password to something that is too weak (because we're using [zxcvbn](https://github.com/dropbox/zxcvbn), we can't say exactly _why_ it's too weak; it's purely algorithmic)

We don't currently check any of these conditions in the app, though there is at least a visual indicator for the password (small wins, yay!).  It'd be pretty easy to add those checks for these conditions, though.

Right now the validation happens on the API, which returns an error code.  The error code is some text of the form `[action]-[error]`, ostensibly so we could have useful error messages.  E.g., a weak password on this form would result in the error `update-self-weak-password`.  The implementation in #1357 maps that API error into text that's shown in the little toast notification in the bottom right.

**Comment by mgwalker** [comment]
Updated the screenshots in #1357 with the changes.  Some notes on deviations from your design:

1. The white padding inside the form is wrong. My guess is that the grid is involved in fixing that. Right now it's using the old grid system. Anyway, getting that right is outside my expertise, so I'll probably pair with @hbillings to figure it out

2. When the alert shows up, the heading gets a ton of margin on top. That's using the `h1.ds-h1` class with the `ds-c-alert ds-c-alert--success` above it.  It looks like when `ds-h1` is the first child, the top margin is zeroed out, but as soon as the alert appears, that margin poofs up.

3. The 'show password' checkbox seems to float too high relative to the label and I'm not sure how to get it down.  Might need to pair with @hbillings on that one too!

**Comment by hbillings** [comment]
@jenniferthibault Do you have a sketchfile with columns on it? This looks like it's maybe 6 columns wide with a column of whitespace as padding within the box, but if you have info that'll let us not guess, that would be swell! ^_^

**Comment by jameshupp** [comment]
At the risk of throwing over an apple cart that is making great progress down its intended road, is there a way to show/hide the password field and using the `Change password` text as a trigger? (Whether a button, an arrow, or whatever.) I find it really incongruous to see a blank password field between the personal info and the `Save changes` button. In a lot of apps, to edit your information you have to re-enter your password, and this might trigger that impulse in someone. (And if they enter it but mistype _slightly_ now they have a new mystery password!)

**Comment by hbillings** [comment]
@jameshupp That is a _super_ good point! We might also consider making the password field have a secondary "confirm" field so they can't accidentally change their password and mistype.

**Comment by lauraponce** [comment]
Jumping in on this since Jen is slammed with offboarding and I have some time! Great points, @jameshupp @hbillings! Would something like this work better? 

![Screen Shot 2019-03-19 at 5 38 18 PM](https://user-images.githubusercontent.com/21222704/54650988-09a24c00-4a6e-11e9-9332-3c1127c58c8b.png)

### Clicked Change password

![Screen Shot 2019-03-19 at 5 38 31 PM](https://user-images.githubusercontent.com/21222704/54650995-0c9d3c80-4a6e-11e9-83df-9a8ac57da646.png)

The way Login.gov does this is by having edit links by each of the fields and then taking you to another page where you can make changes. For what we need, it seems like keeping it all in line on this page would work fine for us. 

I'm picturing the errors to show up similarly to #1306 where the field would turn red if it's too short of a password or if they don't match.

To your point, @jameshupp, about users thinking they need to enter their passwords before saving, maybe that could be made clearer by making the password field view only and they wouldn't be able to click into it or make changes without going through the Change password link. (There is a bigger piece of work around refining ALL the input fields in #1383 so maybe we can revisit this page after that.)

**Comment by jameshupp** [comment]
Had a short chat with @hbillings on this; sounds like we may want to gray out the view-only password field, but otherwise I think this covers it.

**Comment by lauraponce** [comment]
Sounds good — here's a version of what it looks like with the grayed out password field: 

![Screen Shot 2019-03-20 at 7 51 51 AM](https://user-images.githubusercontent.com/21222704/54694209-18781580-4ae5-11e9-94ca-8ba5be192556.png)

**Comment by jenniferthibault** [comment]
Thank you so much for catching this issue @lauraponce ! These are smart interaction changes!

I'd recommend a few small tweaks to these visual styles:

1. With regular link styling, people may expect to be taken elsewhere when they click "Change password". To help with this, add an icon that implies a change in the current state ([lock](https://fontawesome.com/icons/lock?style=solid) / [unlock](https://fontawesome.com/icons/unlock-alt?style=solid))
2. When you're in password "edit" mode, keep the old field disabled (since you really can't do anything with it), disable the "Change password" link, and switch the icon to unlocked.
3. When we have "Show password" we don't need to ask users to re-enter their password (following Login's model)

### Default
<img width="712" alt="Screen Shot 2019-03-21 at 9 08 26 AM" src="https://user-images.githubusercontent.com/11636908/54754303-8ee64780-4bb9-11e9-8c80-024e8d3afbcf.png">


### Edit mode
<img width="716" alt="Screen Shot 2019-03-21 at 9 08 38 AM" src="https://user-images.githubusercontent.com/11636908/54754309-93126500-4bb9-11e9-9021-ed5ff79acd5b.png">


Thoughts?

**Comment by lauraponce** [comment]
I'm _so_ going to miss having your brain on this project and being able to see how you think through problems and the best way to solve them, @jenniferthibault! Completely agree with all of your tweaks!

**Comment by mgwalker** [comment]
Closed by #1357. Created #1396 to capture the modified "change password" behavior outlined above.
