### ISSUE TITLE
Using a screen reader, there is no option to "Skip to main content" when tabbing through pages

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1304]
When tabbing through the content, there is no option to "Skip to main content." Instead user must navigate through the sidebar before getting to main content.

### This task is done when...
 - [ ] "Skip to main" content is available in each portion of the app (login, dashboard, app builder)

**Comment by jeromeleecms** [comment]
@nkkl could you please take a look to see if this in the ballpark for what is expected for testing? We can close this out and/or move the content into a general Google doc for review once the design system + table changes have been made (or we can keep this pending and remove the assignment).

**Comment by nkkl** [comment]
This is an interesting one – I wouldn't say that we necessarily have enough navigation that we _need_ it but at the same time it would be really helpful for users, especially inside the APD itself. Might be a good thing to run by design and see how @lauraponce thinks we ought to handle this.

This is also going to be more or less helpful depending on how many of our end users depend on screen readers and/or keyboard-only navigation.

**Comment by nkkl** [comment]
At any rate, I can confirm that the bug repros. 😉

**Comment by lauraponce** [comment]
If this is an easy fix, it would be nice to have it in, but I can't speak to that level of effort. This seems important to add in as part of layer 2+, but agreed with @nkkl that maybe we'd be okay to not rush to get it in for the pilot if we don't have participants who would rely on this to navigate.

**Comment by jeromeleecms** [comment]
Thanks all! It was more of an issue when we had the sidebar on the dashboard (lots of tabbing to get to the actual dashboard), but since we are proposing to take this out, I'll put this bug in the icebox pending for layer 2.

**Comment by nkkl** [comment]
Sounds good! And when we do take it into consideration, it feels most relevant for the APD itself.
