### ISSUE TITLE
Apply CMS design system styles to user management flow

### ISSUE THREAD

**Issue by jenniferthibault** [18F/cms-hitech-apd#1306]
So that users of the eAPD system have a consistent visual and interaction experience from start to finish in the app (and maintain a high level of confidence in its authenticity), we need to use the CMS design system styles in the user management flow created in #1253, #1254, and #1276.

### This task is done when...
 - [x] The experience for Logging in is designed using the CMS design system
 - [x] The experience for Logging out is designed using the CMS design system
 - [ ] A new issue has been created passing designs to implementation

**Comment by lauraponce** [comment]
Here is a first pass at the main **Log in** page for how it could look with the CMS design system:

![log in page new](https://user-images.githubusercontent.com/21222704/54007797-7c2f3580-4118-11e9-9202-30f938985e68.png)

### Incorrect email or password:
![log in page new copy](https://user-images.githubusercontent.com/21222704/54007801-82251680-4118-11e9-9a81-12461e8d2c2e.png)

### Tried to log in with an empty field:
![log in page new copy 2](https://user-images.githubusercontent.com/21222704/54007817-8f420580-4118-11e9-86b4-641a402985ed.png)

@jenniferthibault 👀& feedback for this layout?
@jameshupp do you have thoughts on `log in` vs `sign in` (or feedback on any of this)?

**Comment by jeromeleecms** [comment]
@jameshupp Feel free to updated #1308 if you provide @lauraponce feedback on the error messages here!

**Comment by lauraponce** [comment]
@jenniferthibault and I talked through the login experience and here are the desigs that we landed on:

### Log in page:
![Log in page new](https://user-images.githubusercontent.com/21222704/54058997-623f3280-41ac-11e9-8fc8-ad43e5253939.png)

### Log in page with incorrect email/password error state:
![Log in page new - error](https://user-images.githubusercontent.com/21222704/54058995-61a69c00-41ac-11e9-92a4-187f019ed8fb.png)

### Log in page with empty field error state:
![Log in page new error 2](https://user-images.githubusercontent.com/21222704/54058996-61a69c00-41ac-11e9-8ea7-346f8fc5e64e.png)

Questions for @jeromeleecms & @NAretakis -
- To limit the scope for the pilot, @jenniferthibault and I talked about the experience for logging out and felt like it would make sense to just take them back to the main Log in page when they log out so they can get back in if they need to. Does that feel like the right call for now?
- For the pilot, are the accounts going to be created for the state participants on our end and we will send them their credentials, or will they be creating accounts for themselves? (When we talked about this recently, I think we landed on creating the accounts for them but wanted to make sure since it has implications for the Create an account link on this page.)
- Also for the pilot, does it seem reasonable to _not_ create a forgot password flow, and if any of the pilot participants forget their password, we (we probably = @mgwalker) will help them recover/reset it manually? It seems like there is a lot involved here so trying to think through the priority of this and it feels like it could fall below the line for layer 1.

@jameshupp 👀do you prefer to call out any content changes in this issue or would it help if I made a new one specifically for that?

**Comment by lauraponce** [comment]
Once I hear back about these these questions and feedback, I'll update the mock ups (if needed), then will create the dev issue(s), and then this will be good to be closed out.

**Comment by jeromeleecms** [comment]
1. Yes. I agree -- after a user logs out, we should return them to the login screen.
2. I believe that's where we landed. We can create the accounts for the pilot testers. @mgwalker Sounds like #1302 provided a UI for admins to  create/edit user account, right? 
3. #1044 is in the icebox currently, so that makes sense (unless an automated user driven forgot password flow is necessary for ATO). I'm OK with manually handling password resets -- #1307 should address the flow question for manual changes and with getting the password to the user.
4. For accessibility reason, "This field is required." would need to be changed as it does not provide sufficient information about which field is required. I will defer to @jameshupp on any final language, but "An email is required." or the "A password is required." would indicate which field is empty.

**Comment by lauraponce** [comment]
Thanks for the speedy reply, @jeromeleecms! Sounds like we're on the same page with everything — logging out goes back to log in, accounts will be created for them, and manual password reset by us if needed. 

I think that means for this login page, we can just get rid of the forgot password and create account links at the bottom for the pilot then add those back in for layer 2 once the experiences are built out. Does that sound right, @jenniferthibault @jeromeleecms?

**Comment by jenniferthibault** [comment]
Sounds right to me!

**Comment by jeromeleecms** [comment]
1. Forgot password: Instead of just removing the forgot password link, can we have some simple instructions that says something along the lines of: "For lost/forgotten passwords, please contact <email>."

That way it gives the user some direction in case they need assistance.

2. Create Account link: makes sense to move to layer 2!

**Comment by jenniferthibault** [comment]
@jeromeleecms Yes! 🎉 Simple instructions for who to contact when someone forgets a password would be even better! Do we know the answer?
Who _would_ be the point of contact for this info?

**Comment by mgwalker** [comment]
🎉 for this conversation.  Users won't be able to reset passwords on their own until we have a way of automatically contacting them outside of the app (probably email).  Same with creating their own accounts (which maybe they should _never_ be able to do as a policy matter?).

**Comment by jeromeleecms** [comment]
@jenniferthibault I knew that was going to be the next question! Still noodling through this, but some options I've come up with..

1) Shared general mailbox (we'd have to request this on the CMS servers) or...

2) Addressed to Nick and I for the pilot with the option of moving to (1) or directly to automation once that is squared away. (Leaning toward this option because its lightweight). Also open to adding more folks, if we identify other potential admins to create some customer focused redundancy.

The shared general mailbox might be nice if we were looking for a central way to collect feedback during the pilot (though the 18F and MeT team wouldn't have access to this if it was housed as a CMS address)...

But (2) has the most mental traction with me at the moment...

**Comment by lauraponce** [comment]
@jeromeleecms are you thinking along the lines of this? With a placeholder email address for now until we have the actual.

![Screen Shot 2019-03-12 at 6 02 25 PM](https://user-images.githubusercontent.com/21222704/54246178-0d275780-44f1-11e9-86ff-c357c6d9ff8e.png)

@jenniferthibault 👀 (this is using the `Regular hint` text style — I _think_ this counts as a hint?)

**Comment by jenniferthibault** [comment]
Agreed that styling also makes sense to me here @lauraponce ! Nice!

**Comment by lauraponce** [comment]
Created #1376 for the dev issue to build this!
