### ISSUE TITLE
Create Policy about how to get user account information to user

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1307]
This issue will define our password policy for creation, maintenance, and initial account information.

### This task is done when...
 - [x] password policy created and documented in this issue
 - [x] policy for account information created and documented in this issue

**Comment by NAretakis** [comment]
Password Policy, @mgwalker are can we use these requirements with our authentication? And/or what is does our password requirement thing currently require?

> Case Sensitive 
> Be changed at least every 60 days 
> Not be changed more than once per day 
> Password can’t contain 50% characters from previous password 
> Be different from the previous 24 passwords 
> Must include:
 - At least one number (0-9)
 - At least one Lowercase alphabetic character (a-z)
 - At least one Upper Case alphabetic character (A-Z)
 - Confirm Password Match

**Comment by NAretakis** [comment]
Initial User Account Information Policy includes the following:

1. Username
2. State
3. Account Setup (Y/N)
4. Default Password Setup
5. Account Information Emailed (Y/N)
6. Default Password Changed (Y/N)

https://docs.google.com/spreadsheets/d/1RsCJzGeBjbqKez5Wvhl3X6A6pvyImLuNdOhwCrtOp9Q/edit#gid=0

**Comment by mgwalker** [comment]
@NAretakis We  are currently using a [zxcvbn library](https://github.com/dropbox/zxcvbn), which I believe satisfies the revised [password guidance from NIST 800-63b](https://pages.nist.gov/800-63-3/sp800-63b.html#memsecret).  It uses pattern matching to identify things like repeated characters, repeated character sequences, keyboard sequences (like `asdf`), and common passwords to estimate password strength.  It also maintains a list of compromised passwords that it checks against.  As best I can tell, it ticks all of NIST's new checkboxes.

Point-by-point:

1. **Case Sensitive** - Yes, done!

2. **Be changed at least every 60 days** - Is this something we can push back on? NIST's updated recommendation is to ***not*** do this:
   > Verifiers SHOULD NOT require memorized secrets to be changed arbitrarily (e.g., periodically). However, verifiers SHALL force a change if there is evidence of compromise of the authenticator.

   (NIST built a FAQ and [one of the answers in it](https://pages.nist.gov/800-63-FAQ/#q-b5) is about this precisely.)

3. **Not be changed more than once per day** - We *can* but if we can push back on this one, I'd recommend it.  It's historically used as a way to enforce desired outcomes on points 2, 4, and 5, all of which run contrary to NIST guidance (and 4 and 5 run contrary to common sense, but they are oh so common in government).

4. **Password can’t contain 50% characters from previous password** - No. We absolutely cannot do this and I will dig in and fight on this one.  The only possible way to enforce this is if we store users' passwords in clear text somewhere and I will move to Siberia before I do that because it is a horrifyingly bad practice.  Doing that is how you end up having all the tech journals shaking their heads because everyone knows better.  (Happy to explain more about how we store passwords to keep them secure, but in summary, we can't store them securely if we have to enforce this policy.)

5. **Be different from the previous 24 passwords** - No.  Same reason as 4.

6. **Must include [character requirements]** - We *can*, but this one is also contrary to NIST guidance:
   > Verifiers SHOULD NOT impose other composition rules (e.g., requiring mixtures of different character types or prohibiting consecutively repeated characters) for memorized secrets.

   (NIST has a [FAQ answer](https://pages.nist.gov/800-63-FAQ/#q-b6) for this one, too!)

   - **Confirm Password Match** - We can do that.  We'd discussed it elsewhere and I think @lauraponce or @jenniferthibault concluded that since users can make their password visible (also recommended by NIST!), that should suffice.  But if this is a CMS requirement, it's easy enough to implement and doesn't do any harm, so this is one I'd just shrug and do rather than argue about. 😆

**Comment by NAretakis** [comment]
Ok, revised policy that is good to go if @mgwalker gives it a thumbs up:

Point-by-point:

1. **Case Sensitive** - Yes, done!

2. **Verifiers SHALL force a change if there is evidence of compromise of the authenticator.**
   (NIST built a FAQ and [one of the answers in it](https://pages.nist.gov/800-63-FAQ/#q-b5) is about this precisely.)

3. **Verifiers SHOULD NOT impose other composition rules (e.g., requiring mixtures of different character types or prohibiting consecutively repeated characters) for memorized secrets.**
   (NIST has a [FAQ answer](https://pages.nist.gov/800-63-FAQ/#q-b6) for this one, too!)

 4. **Confirm Password Visibility** -  since users can make their password visible (also recommended by NIST).

**Comment by NAretakis** [comment]
@mgwalker gave a thumbs up to this on standup. Hooray!

**Comment by mgwalker** [comment]
To be clear, there is also a policy for how accounts will be created and how the initial passwords will be delivered to users?
