### ISSUE TITLE
Review error messages -> update Save interaction

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1308]
This was the original to-do on this item:

Take a look at the error messages that appear in the app. 

Currently:
1) Password Error
2) No user name Error
3) APD Save Errors
4) APD Delete Errors

At present, however, we've rolled a bunch of issues around and what this issue is _now_ is to design a new in-progress Save interaction.

#### Current version of task list

- [x] @jameshupp Reviewed language on known error messages
- [x] Get input from @lauraponce or @austinhernandez about the rendering of the save success/failure toast message
- [x] Confirmed that we aren't doing form validation on Save anymore.
- [ ] The to-do list @austinhernandez defined in [his comment with up-to-date mockups](#issuecomment-479564669) is complete. (Yes, this is a to-do list in a to-do list. This issue got away from us a bit.)

#### Saving for later to write into a different issue

- [ ] The API's use of 401 and 403 errors is corrected (currently they're reversed)
- [ ] Update the 404 and 500 error messages (available [in the doc](https://docs.google.com/document/d/1D5kOCREcV0ib-VCSYRsqdUUB_HlphAc9GsHwKOOxI8c/edit) 🔒)
- [ ] Update the login error message (also in the doc)
- [ ] Check to see whether date validation has a bug (currently, text that shouldn't parse as dates isn't triggering an error)
- [ ] Update the date-based save error messages we have clarity on (also in the doc)

**Comment by mgwalker** [comment]
@jameshupp When you get to this one, if you want to sync up for 5-10 minutes, I can show you where those errors originate.  In a nutshell, we have "error tokens" coming from the API, and we convert those into strings.  I'd be very happy if the error message content structure and error token structure were the same/similar and would be eager to make whatever changes to support that.

**Comment by jameshupp** [comment]
To clarify: the two lists are separate things, right? They are not intended to be overlapping or have any kind of parent/child relationship? That's certainly my understanding, just want to be sure.

**Comment by mgwalker** [comment]
Correct.  It's really just one long list, but definitely no overlapping or hierarchy.  It will only be one error, not any combination.

**Comment by jameshupp** [comment]
I have made a worksheet where I've started working on this. @mgwalker it will surprise you not at all it has led me to some technical questions! I have left them in comments in the doc. Can you give them a look? (There's a shorter, easier design-related one in there, too, but the technical ones are far more important for this stage.)

🔒 https://docs.google.com/document/d/1D5kOCREcV0ib-VCSYRsqdUUB_HlphAc9GsHwKOOxI8c/edit 🔒

**Comment by jameshupp** [comment]
Okay so after discussing some specifics with Greg, we actually have additional tasks here. I've updated this issue to account for them, but as you'll see it has _all the labels_. The task are individually fairly small so I don't think it's wrong to keep this as one issue, but if people are more comfortable separating I'm fine with that, too.

**Comment by jameshupp** [comment]
One of the checklist items is about whether it's okay to have longer content in the toast message. @lauraponce and @austinhernandez, here's how those look now. Can these get longer? Should they? Do they need a different design direction entirely, with or without text changes?

<img width="309" alt="Save success toast message" src="https://user-images.githubusercontent.com/6314097/54835762-30909600-4c99-11e9-8900-b6f3ee9af1ad.png">
<img width="308" alt="Save failed toast message" src="https://user-images.githubusercontent.com/6314097/54835763-30909600-4c99-11e9-8ed1-f15e3bbfaf2b.png">
<img width="819" alt="Save failed message in browser context" src="https://user-images.githubusercontent.com/6314097/54835824-4f8f2800-4c99-11e9-9534-6819977314a2.png">

**Comment by jameshupp** [comment]
I **love** the button state changes.

Failed saves can happen for unspecified reasons, and in that case, maybe keeping it simple like this is best. I wonder about a short "try again" message near the button?

But there are also specific issues that cause fails and we should alert people to those. So like one example is someone didn't name one of their activities, or they tried to give the same name to two activities. The API catches those and we should tell people the specific thing we want to change.

**Comment by austinhernandez** [comment]
Ok this version. Combines #1403 and #1337 and this ticket. It's got it all. It's got button save states, it's got toast messages, it's got new button placements. 

Rationale: 

- Since users are working with several pages of content without an autosave, saving process will be crucial. Save button is fixed to the bottom right corner where a form submit or save button would typically be. The position is to remind users to save early and save often.
  - (I wonder if they could download a worksheet / template) so this could be completed offline and copied in or sent in?) 
- The export button was removed from the left column and the language of step 9 was changed to "Export"
- Button change and loading states better indicate system status, aka let the user know what the results of their actions are and if they did it right.
   - Interaction for the loading spinner is already a button component in the design system -  https://design.cms.gov/components/spinner/
- Toast messaging occurs near click actions, toast messaging allows for more descriptive system status or alternative options to failed saves.
- Text was changed to "Save changes" so users aren't confused as to the function of this button. With the space around the button - we could also had some helper text if needed.
- Next steps: lets see what this looks like IRL so we can make interaction changes as needed

Save default state:
![Save interactions - new placement - save](https://user-images.githubusercontent.com/23194720/55494405-b4873e00-5608-11e9-8862-ca757227ef3c.png)

Save loading state ([loading spinner](https://design.cms.gov/components/spinner/)):
![Save interactions - new placement - save loading](https://user-images.githubusercontent.com/23194720/55494404-b4873e00-5608-11e9-88db-a8a65326e7b4.png)

Save failed + toast messaging:
![Save interactions - new placement - failed](https://user-images.githubusercontent.com/23194720/55494403-b4873e00-5608-11e9-8d54-45eb67fab79e.png)

Save successful + toast messaging:
![Save interactions - new placement - saved](https://user-images.githubusercontent.com/23194720/55494406-b4873e00-5608-11e9-9837-a81547b8ba11.png)


## It is ready for review:
- [ ] Content review and states provided by @jameshupp here: [Error states and messaging](https://docs.google.com/document/d/1D5kOCREcV0ib-VCSYRsqdUUB_HlphAc9GsHwKOOxI8c/edit)
- [ ] Ready for product sign off by @jeromeleecms and @NAretakis (maybe guidance from @nkkl ?)
- [ ] Development estimates and gotchas from @mgwalker and @hbillings 
- [ ] User flow considerations from @lauraponce

**Comment by lauraponce** [comment]
@austinhernandez I love the direction you're going with these button states! Two thoughts:

1. On the failed save state, I feel like it might make more sense to leave the button state as `Save changes` and use the toast message text to indicate there was an error letting them know they need to try again. That way when they click the button they are selecting the save changes button rather than the one with the error.

2. Similarly, I wonder if we need the `Save successful` toast message at all with the success state since the button has that information there as well?

**Comment by austinhernandez** [comment]
We agreed 4/3 to implement and move the buttons to the lower right hand corner.

Still TBD:
- Link to "export PDF"
- Should we use a toast popup or text based error message (using form validation styles) to show users what went wrong with save?
- What is the messaging we should use on save failed / what's the  "escape hatch" ?

**Comment by jameshupp** [comment]
Content review for the save button style is done. Reminder we're working from @austinhernandez's [comment defining completion criteria](#issuecomment-479564669), not from the top checklist anymore, which I'm going to amend/get rid of momentarily.

**Comment by NAretakis** [comment]
Good to go from me!

**Comment by lauraponce** [comment]
I know we talked about this after one of our standups, but I think I had to drop early for another meeting before everything was decided. Can someone remind me where we landed on using the button states for messaging? Did we decide to use the toast popup or some other form of notification above the button to indicate what's happening while the button always remains as `Save changes`?

**Comment by jameshupp** [comment]
I don't recall either. I guess if you can click the button immediately regardless of outcome, might as well leave the button the same?

**Comment by jeromeleecms** [comment]
Started reviewing this and then realized that Nick already gave the thumbs up, so not going to re-review this! 

@mgwalker @hbillings do you have any lingering issues regarding implementation of this? If not we can spin up a separate dev issue and get the implementation on the board.

**Comment by mgwalker** [comment]
Can we summarize in a single comment what the final result is to be?  Does Austin's comment here https://github.com/18F/cms-hitech-apd/issues/1308#issuecomment-479564669 capture it completely?

**Comment by jameshupp** [comment]
@mgwalker I think there are two things not reflected in that comment now. I can make change 1, but what do we think about 2:

1. Seems like we don't want a `save failed` button state. The toasts cover that, and it makes it easier to know to click that button again to try again.
2. We don't have it documented how long the toasts should last. Should it be the same length always? Should success and failure have different lengths? Maybe success for five seconds and failure until another attempt is made? @lauraponce any thoughts?

**Comment by lauraponce** [comment]
This is my understanding of the button states (which, I think, matches what @jameshupp said):

Unsaved changes 

![Screen Shot 2019-04-11 at 1 41 47 PM](https://user-images.githubusercontent.com/21222704/55991710-bb90fa80-5c5f-11e9-8eec-07100ce821f9.png)

Save failed - the error message persists and doesn't disappear until they try saving again

![Screen Shot 2019-04-11 at 1 39 02 PM](https://user-images.githubusercontent.com/21222704/55991736-cba8da00-5c5f-11e9-85ad-db38f98ad321.png)

Save success (what they see immediately)

![Screen Shot 2019-04-11 at 1 41 22 PM](https://user-images.githubusercontent.com/21222704/55991765-debbaa00-5c5f-11e9-9ba8-94a905983ae9.png)

All changes saved (no new changes made) 5 seconds later after the toast popup disappears. I agree that 5 seconds seems like a reasonable length — since the button itself is a secondary indicator that everything is saved, the toast popup is kind of just an extra assurance.

![Screen Shot 2019-04-11 at 1 42 57 PM](https://user-images.githubusercontent.com/21222704/55991907-25a99f80-5c60-11e9-98bc-6ef52ae5c40c.png)

Once a change is made, the button turns into the Save changes button again

![Screen Shot 2019-04-11 at 1 41 47 PM](https://user-images.githubusercontent.com/21222704/55991929-35c17f00-5c60-11e9-9a21-c28b200285d5.png)

**Comment by jeromeleecms** [comment]
This is done.
