### ISSUE TITLE
Define the PDF APD submission handoff process 

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1317]
When states are ready to submit their APD, they'll need to turn in the exported PDF to their analyst. 

Some of the questions to answer as part of defining this process are:
- How should this process work?
- What are the steps involved? 
- Will there be a meeting; if so, who will be included?
- How will Nick and Jerome work with the primary state's reviewer?

### This task is done when...
 - [x] The APD submission/handoff process has been defined
 - [ ] The handoff process has been shared with the people who are part of it

**Comment by jeromeleecms** [comment]
@lauraponce @NAretakis @MCorradoHMA @CSwartzHMA Just some thoughts around this, but open to suggestions + additional comments!

I don't think this needs to modify the exist process that dramatically. I made a swim lane in our existing Document Status Flow map (instead of creating a new map). 

https://app.mural.co/t/gsa6/m/gsa6/1540576639730/98e9cb36a85619864c28a397648ed67e18defdee

Fundamentally, the handoff should be very similar to our existing flow (with changes starred [*] below)
1) Exported PDF is submitted to the mailbox 
2) State officer begins review. We can have a separate orientation with the State Officer to provide expectations, but I don't think we should try to hand hold the State Officer through the review so they can have an "untainted" view of the submission.
3) Nick and/or Jerome should also review submission independently [*]
4) Team should collectively meet with the state officer to review questions/comments that came out of the review. We should also track any themes around the questions to see if the help text was sufficient/needs to be modified. We could use this same meeting to capture feedback on the review of the PDF, but maybe this could be a separate meeting(?) [*]

**Comment by lauraponce** [comment]
This seems clear to me, @jeromeleecms but will definitely want Nick and MeT to weigh in too with their thoughts/questions! 

The only question that comes to mind right now is will you still be subject to the 60-day clock for the pilot, and if so, is there anything different about how you'll keep track of that?

**Comment by jeromeleecms** [comment]
While HITECH does not not have a formal 60 day clock, our plan should be to hold to that time frame to ensure timely approvals. 

Step (1) will trigger some additional steps which are part of our current process so we can track receipt date and "due date" - besides the fact the the APD submission came out of the builder - things should run like normal.

**Comment by jeromeleecms** [comment]
@CSwartzHMA @MCorradoHMA  @NAretakis 

Just bumping this in case you haven't had a chance to review (or need to tie it to any of your other pilot related activities).

Do we need to document this as part of the pilot planning docs?

**Comment by jeromeleecms** [comment]
This content will be reviewed and incorporated into #1316 +the other pilot planning work that is ongoing.
