### ISSUE TITLE
Book travel for in-person state research

### ISSUE THREAD

**Issue by nicoleslaw** [18F/cms-hitech-apd#133]
I will set up some time for us, just making an issue to remind myself. Budget sheet is here: https://docs.google.com/spreadsheets/d/1YlEIYvj7F27gC0OYWZxuDwjAgYa4TE4r9rQD9opVfMg/edit?pli=1#gid=750734413

**Comment by nkkl** [comment]
Let's include @brendansudol in this trip as well, so that dev can get a firsthand look at the way budgets are done.

**Comment by lauraponce** [comment]
@brendansudol @quarterback let's start thinking about dates for this! What Nicole and I were thinking was to start with Massachusetts and meet with them at their office in Boston. We can talk to them about their APD process and really go into depth about their budget stuff in order to find out what they need to start building out that flow.

We can also show them the prototype for what we have at the point in time when we meet with them. Since we'll be there in person, we could even do some sketching with them and update it based on their feedback.

Thoughts on when we should plan for this? I'm thinking maybe the last week of Feb or the first week of March, but since you both are the ones working out your schedule to travel, let me know what works for you!

**Comment by quarterback** [comment]
@lauraponce @brendansudol The end of Feb. (26-3/2) would probably be better than the first week of March (5th-9th) for me.

**Comment by brendansudol** [comment]
I have a commitment in the evening on Feb 28th (a Wednesday) locally that I can't miss, but I could do Feb 26-27 (Mon/Tues), or March 1-2 (Thurs/Fri); I can also do any period of time between March 5-9th.

**Comment by lauraponce** [comment]
I'm going to be out on 2/26 and will be out in the afternoon of 3/2, and since @brendansudol has something on 2/28, that leaves 3/5-3/9. Would 3/7-3/8 work for either of you @quarterback @brendansudol?

**Comment by quarterback** [comment]
The only day I have a conflict is 3/7, an evening event I'm committed to volunteering at locally. Otherwise, I can do anything else that works for both of you.

**Comment by lauraponce** [comment]
Okay, no worries, we can try moving it up a couple days—how about 3/5-3/6? (Also, this is assuming this date would also work for the MA team.)

**Comment by quarterback** [comment]
I can do that.

**Comment by brendansudol** [comment]
3/5-3/6 works great for me!

**Comment by lauraponce** [comment]
@jeromeleecms @NAretakis Can you help us coordinate with the MA team to see if **Monday, 3/5** works for them to meet with us? We'd like to meet with them at their office for a few hours to learn about their process and go into depth about budget tables. We can also show them the prototype and do a usability test with them as well.

**Comment by lauraponce** [comment]
Update: Jerome reached out to the MA team, and we expect to hear back early next week since they are OOO today.

**Comment by lauraponce** [comment]
@brendansudol @quarterback since we're moving the date up a week for this, how does Tuesday 3/13 sound for meeting with MA?

**Comment by lauraponce** [comment]
Updating this thread with the latest, we are scheduled for 3/15 from 12-3!
