### ISSUE TITLE
Design admin landing page

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1351]
There are currently admin pages for creating and editing user accounts, but the only way to get to them is to navigate to them by URL.  My thinking was this landing page might just be links to those two pages, but maybe those two items become widgets on a combined admin page?

### This task is done when...
 - [x] we know what a single admin point-of-entry (?) looks like and how it behaves
 - [x] handed off to dev (see #1273)

**Comment by jenniferthibault** [comment]
One place we could start that tried to keep things simple:

![Layer 1: Admin Landing_2](https://user-images.githubusercontent.com/11636908/54328368-0594ab00-45e4-11e9-9384-d45d47ca95be.png)




Implementation considerations:
- This uses the same grid foundation as the state dashboard page from #1268 
- Each card is four grid columns wide with one gutter in-between
- The icons are [user-cog](https://fontawesome.com/icons/user-cog?style=solid) and [user-plus](https://fontawesome.com/icons/user-plus?style=solid) from Font Awesome under a Creative Commons Attribution 4.0 International license. That means we need to abide by the following:
> You must give appropriate credit, provide a link to the [license](https://fontawesome.com/license), and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

In the past, I've handled this by listing the icons we use and providing the attribution and license link in the repo's LICENSE file. If we go for it here, I'd make the PR for that from this issue separate from the dev issue. (And I could do it!)

I did consider adding both widgets to this landing page directly, as Greg suggested above, but that quickly lost the clarity in exactly what tasks were possible at this stage, which the above mockup provides. I also considered making larger solid background card-type components for this (see below), but those would be totally custom elements not from the design system. Since the mockup above uses just typography styles, it allows us to avoid customization and code used in a one-off way.
![Screen Shot 2019-03-13 at 11 01 06 PM](https://user-images.githubusercontent.com/11636908/54328339-e9910980-45e3-11e9-820e-18815810ec0a.png)

**Comment by NAretakis** [comment]
From my perspective, this look great. I like the typography styles version as it keeps things simple but still accomplishes what this page needs to do.

**Comment by jenniferthibault** [comment]
Moved to implementation in #1273
