### ISSUE TITLE
Apply design system styles to log in page

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1376]
As detailed out in #1306, the log in page should be updated to match the CMS design system styles.

![Log in page new](https://user-images.githubusercontent.com/21222704/54322465-8044d280-45b2-11e9-83d6-eb636838f493.png)

with incorrect email/password error state:

![Log in page new - error](https://user-images.githubusercontent.com/21222704/54322471-83d85980-45b2-11e9-879f-287f46f3a987.png)

with empty field error state:

![Log in page new error 2](https://user-images.githubusercontent.com/21222704/54322473-863ab380-45b2-11e9-958b-b4e75cded387.png)

### This task is done when...
 - [ ] Log in page has been updated with error states
 - [ ] Design/content have reviewed it and approve

**Comment by jameshupp** [comment]
Sorry it took me a long time to weigh in on this. `Log in` vs `Sign in` is sort of immaterial. N/N recommended `Sign in` based on research but that was in 2002, and their own website now uses `Log in`. I think this is mostly preference.

My two questions:

* Have we considered whether we want to say `Log out` or `Sign out` in the header for current users? In and out should be consistent.
* What do we want the page to be called? The URL is `login` and I'd rather be consistent with that.

So the easiest thing is `Log in` I think. Which is good, because the page header and the button should either use the same term, or they should be totally different. But `Log in` for the header and `Sign in` for the button feels weird.

**Comment by lauraponce** [comment]
One of the arguments I've seen is that `Log in` is easier to distinguish from `Sign up` than `Sign in` is. But since we'd probably use `Create account` vs `Sign up` anyway maybe that point is irrelevant. 🤷‍♀️ Either way, it sounds like you're advocating for `Log in/out` for all the links, and that sounds good to me, @jameshupp! 👍 

It looks like @jenniferthibault is already one step ahead and updated the button to `Log in` in the design files so just I'll paste those here so Greg and Heather have the latest in this issue:

![Screen Shot 2019-03-19 at 6 04 49 PM](https://user-images.githubusercontent.com/21222704/54651809-a9150e00-4a71-11e9-82bf-8fef04755ad5.png)

![Screen Shot 2019-03-19 at 6 05 10 PM](https://user-images.githubusercontent.com/21222704/54651807-a87c7780-4a71-11e9-8fb6-061bf8548bee.png)

**Comment by NAretakis** [comment]
This also has accessibility issues built into the comments above.

**Comment by jameshupp** [comment]
Sorry @NAretakis do you mean the new direction represents a fix? Looks like from #1306 that specifying "email" or "password" in the error solves the problem described there, but are there other issues we should know about, too?

**Comment by jeromeleecms** [comment]
@jameshupp I made this comment during sprint planning that applying this design would solve one of the the accessibility issues I identified in #1308 (the existing language for error messages is not that descriptive). 

Thinking aloud here, it may be beyond the scope of this particular issue, so I'm happy to keep it here or we can spin it up separately after you've had a chance to complete #1308.

**Comment by jameshupp** [comment]
That's right, thanks! I just added it into the doc for #1308.

**Comment by hbillings** [comment]
@jeromeleecms @NAretakis What is the email address noted in the footer? I can't tell if it's `contact CMS_shared_inbox@cms.gov` or contact CMS: shared_inbox@cms.gov`.

**Comment by jeromeleecms** [comment]
@hbillings That was just a placeholder email address for the mockup. Can you leave that as an empty link that does nothing: maybe CMS-eapd@cms.gov? Alternatively, if we do need to have it do something, have it email Nick and I.

I'll spin up an issue to explore getting a shared CMS email box for our project to handle requests like this.

**Comment by hbillings** [comment]
@jeromeleecms I'm going to spin up another issue to add the email/password info to the login page once we have it so that we can go ahead and close this one out!

**Comment by hbillings** [comment]
Since we're not currently doing client-side form validation anywhere, rather than introduce it here with the empty email/password state, I disabled the button unless there's something in both fields. @lauraponce, how does this seem?
<img width="717" alt="Screen Shot 2019-03-28 at 12 38 47 PM" src="https://user-images.githubusercontent.com/509309/55183924-89a77080-5156-11e9-8e02-9b2e34096263.png">

**Comment by lauraponce** [comment]
@hbillings 👍 that works!
