### ISSUE TITLE
Decide on long-term replacement for our rich text editor

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1408]
Per #1127, this issue is for us to investigate and determine a long-term solution for our rich text editor. 
and make an informed switch to a different rich text editor library:
   - **pros:** can pick something that is actively maintained
   - **cons:** might not find something with all the same features
   - might be complicated to retrofit

This issue is for a research spike of the above to see what's out there, what features we'd lose/gain, and the effort to replace it.  The result of that spike could inform a decision.

### This task is done when...
 - [ ] Various rich text editor options are researched
 - [ ] A rich text editor is selected to implement based on our research

**Comment by jeromeleecms** [comment]
As part of our research, have we considered COTS and open-source options?

**Comment by mgwalker** [comment]
Most of the libraries I can find rely on using a `contenteditable` node rather than an `<input>` or `<textarea>`, so they will all have the same IE spellcheck problem.

- #### [Draft.js](https://draftjs.org/)

  This is the library underlying the editor we use. It seems to be the most maintained (it's a Facebook product, and it's been updated in the past week) and also the most used. One advantage of using a Draft-based editor is that the rich text fields we've already stored in the database would still be valid. If we switch to another library, we might have to figure out how to transform the text we've stored into the new library's format. The downside is that Draft.js is not itself a complete rich text editor - it's a framework for building one. So we'd still have to pick an actual editor:

  - [react-draft-wysiwyg](https://github.com/jpuri/react-draft-wysiwyg) - This is the one we use now. We know there is a performance problem with multiple editors on the screen at once (that's why we have our own fork), and we also know it isn't being actively maintained anymore.

  - [Megadraft](https://www.npmjs.com/package/megadraft) - Not widely used, but updated within the past month or so, but there are a bunch of very old issues still sitting out there open.

  - Custom implementation - Given the number of articles on the web about building a rich text editor using Draft.js, I have to wonder if maybe it's easy enough that we _should_ just do our own. The trouble is that it's not a small amount of code that would have to be maintained.

- #### [Quill](https://quilljs.com/)

  Quill also seems to be well-maintained and widely used, but it doesn't claim to support IE at all. It might work, but if anything goes wrong, we won't get any help. Similar to Draft.js, it isn't an editor in a box, but it has a bunch of plugins that you can compose together to create a full editor. That is, we wouldn't need a 3rd-party built on top of Quill, we'd just use different Quill pieces.

- #### [ProseMirror](https://prosemirror.net)

  This one seems to have been popular for a while but hasn't been updated in about a year. Unlike Draft.js, ProseMirror comes as a more complete package rather than just being a library, but it's extensible so we could swap in other parts and pieces if we wanted. Ideally, we wouldn't want to, but it's an option. ProseMirror claims support for IE11.

- #### [TinyMCE](https://www.tiny.cloud)

  Seems like a pretty standard go-to. Looks fairly easy, and they provide a React wrapper. We'd have to figure out how to get self-hosting setup, though there is an option to use cloud hosting. However, using their cloud hosting would mean creating an account that someone at CMS would have to manage. Much easier to self-host. ("Hosting" just refers to the client-side script. There's not a server-side component.) However, [TinyMCE is known to have the same spellcheck issue with IE](https://community.tiny.cloud/communityQuestion?id=90661000000MrpVAAS) as the others.

- #### [CKEditor](https://ckeditor.com/)

  Also looks pretty straightforward. It's available for free under GPL 2.0, so we'd need to check to make sure that's compatible with public domain projects (I don't have any idea...). The latest version is 5.x, but we'd have to use 4.x if we wanted any IE support at all. Version 4.x claims full compatibility with IE 11 and has a support lifetime until at least 2023, so that would buy some time to hopefully get people off IE altogether.

**Comment by hbillings** [comment]
Ugh, I don't want to write our own editor, but it seems like if we stick with Draft, that's what we're going to need to do. That said, it seems like there's a good argument for sticking with Draft, both from an "it works with what we have" and an "it's maintained" perspective.

Quill seems like it would be easier to use than writing our own thing, but we'd want to test it with IE.

From a future-proofing standpoint, it's gonna be hard to beat TinyMCE. That thing has been around forever (and it used to be what WordPress' editor was built on, IIRC, although I don't know if it still is). It was a bit of a nightmare the last time I used it, but that was like seven years ago and I'm sure it's gotten easier, especially with the React wrapper.

CKEditor looks freakin' amazing! I did notice that their spellcheck is outsourced to a third party service that has its own pricing tier, starting at $150/year. But it also claims to support copy/paste from Word and Excel, which would speak to some of the user feedback we've heard. (Whether or not we want to support that use case is another story.)

**Comment by jeromeleecms** [comment]
Note, @NAretakis has indicated that he is open to supporting/exploring paid COTS products. So don't let the pricing tier be a deterrent if it solves a lot of our problems! We just have to run it by him to see what we'll need to do to get it onboard if this is the best solution.

**Comment by jeromeleecms** [comment]
Schedule a meeting with @mgwalker @hbillings and @jeromeleecms to finalize path forward.

**Comment by mgwalker** [comment]
Nextsteps:

1. build a prototype with TinyMCE to try it out
2. look into the effort for building a custom Draft.js editor
3. research whether Draft.js has plugins, especially around copy/paste

**Comment by jeromeleecms** [comment]
Close this out since #1871 and #1872 define next steps.
