### ISSUE TITLE
Government Consent Screen before User Login

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1424]
Government Consent Screen should appear prior to user logging into the app (ATO Requirement).

Current recommendation is to take the one from cloud.gov, but need to be have CMS lawyers approval. Also available, is the language from NIST. 

Reference: https://login.fr.cloud.gov/login

### This task is done when...
 - [ ] User is presented with the Government Consent Screen
 - [ ] User can access the login screen after the Consent Screen

**Comment by mgwalker** [comment]
I was wrong, there's not NIST-recommended language.  They just list a series of bullets that must be covered in the language:  https://nvd.nist.gov/800-53/Rev4/control/AC-8

Should there be a separate issue for figuring out whether the cloud.gov language/behavior is okay with legal, and if not, for tracking down the CMS-approved language?  We probably don't want to start doing any implementation work on this one until then.  😬

**Comment by jeromeleecms** [comment]
@mgwalker can we just lift the language from here: https://sea.cms.gov/SEAPROD or https://eidm.cms.gov/EIDMLogin/login?

Both are CMS production sites -- unless the language from NIST is newer (I can't seem to tell when the last revision to these bullets were), these should be OK.

**Comment by mgwalker** [comment]
I can't see either of those, but if you want to paste the text here, that's fine with me!

My bigger concern is with the behavior.  The cloud.gov behavior is to show a smaller bit of text with gentler language in it, and offer the option to expand out to the full scary consent language.  The typical behavior is to show you that giant blob of scary text right away (scary to me, anyway).  It may be less of an issue for eAPD users though since they're probably mostly accustomed to blindly clicking through government consent notifications anyway.

I'd be interested in what @lauraponce and/or @austinhernandez have to say about the consent banner/notification screens, though.

**Comment by jeromeleecms** [comment]
From SEA: 

Terms and Conditions
--
 
You are accessing a U.S. Government information system, which includes (1) this computer, (2) this computer network, (3) all computers connected to this network, and (4) all devices and storage media attached to this network or to a computer on this network. This information system is provided for U.S. Government-authorized use only.Unauthorized or improper use of this system may result in disciplinary action, as well as civil and criminal penalties.By using this information system, you understand and consent to the following: You have no reasonable expectation of privacy regarding any communications or data transiting or stored on this information system.At any time, and for any lawful Government purpose, the government may monitor, intercept, and search and seize any communication or data transiting or stored on this information system.Any communication or data transiting or stored on this information system may be disclosed or used for any lawful Government purpose.
 
To continue, you must accept the terms and conditions. If you decline, your login will automatically be cancelled.

**Accept** / **Decline** <-- As buttons

**Comment by jeromeleecms** [comment]
From EIDM:

OMB No.0938-1236 \| | Expiration Date: 04/30/2017 (OMB Re-Certification Pending) \| | Paperwork Reduction Act

This warning banner provides privacy and security notices consistent with applicable federal laws, directives, and other federal guidance for accessing this Government system, which includes (1) this computer network, (2) all computers connected to this network, and (3) all devices and storage media attached to this network or to a computer on this network.

This system is provided for Government authorized use only.

Unauthorized or improper use of this system is prohibited and may result in disciplinary action and/or civil and criminal penalties.

Personal use of social media and networking sites on this system is limited as to not interfere with official work duties and is subject to monitoring.

By using this system, you understand and consent to the following:

- The Government may monitor, record, and audit your system usage, including usage of personal devices and email systems for official duties or to conduct HHS business. Therefore, you have no reasonable expectation of privacy regarding any communication or data transiting or stored on this system. At any time, and for any lawful Government purpose, the government may monitor, intercept, and search and seize any communication or data transiting or stored on this system.
- Any communication or data transiting or stored on this system may be disclosed or used for any lawful Government purpose.

To continue, you must accept the terms and conditions. If you decline, your login will automatically be cancelled.

**I Accept** / **I Decline** <-- As buttons

**Comment by jeromeleecms** [comment]
@mgwalker Instead of pictures, I copied the text as text, so you could copy the text instead of transcribe it.

**Comment by lauraponce** [comment]
There has been a lot of research on users reading terms and conditions, and the verdict is that people generally only spend a few seconds on the page before clicking agree (which means they aren't reading it). So, if we can follow a similar pattern to cloud.gov where they pull out the most important information with the option to read more, that would be ideal. 

If that's not possible because of legal reasons, then it wouldn't be the end of the world to have it all on the page. And agreed with @mgwalker on it that it probably wouldn't come as a big surprise to folks who are familiar with these types of government systems. e-QIP had a similarly scary/jarring popup that people had to agree to and it worked okay, it just wasn't the _perfect_ solution 🤷‍♀️

**Comment by mgwalker** [comment]
> OK so after all of this...
1) Sequence above
2) Short Text with longer pop up window (because it's easy to fix if they say no). Short text - I'm OK with lifting the <http://cloud.gov|cloud.gov> language :slightly_smiling_face:
3) Single Button for Agree to move to login page. (no disagree button based on our last comment)
<sub>[View in Slack](https://gsa-tts.slack.com/archives/C8E5EJK9V/p1555092608023800)</sub>

**Comment by jeromeleecms** [comment]
So sequence above refers to:

Notification Screen -> Accept Consent Screen -> Login Screen
