### ISSUE TITLE
Determine how best to keep selected nav item in view in sidebar

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1432]
In #1337, we made the observation that when multiple sections are expanded, it is possible to lose the highlighted nav item offscreen. There were a couple of suggested solutions:
- make the nav collapse an open item once it loses focus
- auto-scroll the nav so that the highlighted item sticks to the top of the window

We should investigate design options around this.

### This task is done when...
 - [ ] We have identified an effective way to keep the highlighted nav in view

**Comment by lauraponce** [comment]
Adding some more thoughts here! When an activity's accordion is expanded and within the accordion, you scroll down to the end then collapse the activity accordion element, the page drops you down the page instead of leaving you where the top of the accordion is. For example: 

![NI7r4ENhTi](https://user-images.githubusercontent.com/21222704/55917634-e66a4880-5ba4-11e9-8a83-3f24679adc1a.gif)

**Comment by jeromeleecms** [comment]
We no longer use this design to show content to the user. Closed because it's obsolete :)
