### ISSUE TITLE
Design the Executive Summary section that uses the CMS design system

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1457]
The Executive Summary includes the activity summary with the FFY costs and total cost as well as the program budget tables. This section acts similar to a review screen where state users can see what they've entered as view-only (to edit, they can do so in the previous sections).

This section needs to be updated to match the rest of the app and should use the CMS design system. 

Current version of Executive Summary:

<img width="760" alt="Screen Shot 2019-04-14 at 7 47 52 PM" src="https://user-images.githubusercontent.com/21222704/56104820-3ec78000-5eee-11e9-850f-934870dec73e.png">

<img width="680" alt="Screen Shot 2019-04-14 at 7 48 00 PM" src="https://user-images.githubusercontent.com/21222704/56104859-628ac600-5eee-11e9-9e8a-2f05054a2fe2.png">

### This task is done when...
 - [ ] The Executive Summary section has been designed in the CMS design system
 - [ ] Designs are reviewed and approved
 - [ ] Implementation issue has been created

**Comment by austinhernandez** [comment]
Rationale:
- The main point of this section is for the user to review and possibly edit data. 
- I went with a design that indicated that the dynamic nature of the text here by adding content in a disabled text field.
- I made the call to action more apparent by having a link that said "edit activity" as opposed to an underlined activity name.
  - The goal is for the interface to say "You edited this text above, but you caint edit it here. If you wanna edit it, u gotta edit it above."
  - This way, when you are directed to the top of the page it won't be as jarring and more apparent that you are moving to a different part of the page. A smooth scroll might be useful here?  

Questions for dev+design pairing:
- Should we consider adding "Please verify that the information you entered is correct?"
- Should data should stay consistent so if we are showing FY and $$$ in columns?
- How much variation will be in this data?
- If we are restricting the $s to 3 digits and decimals, should numbers like `$1.9M` be translated to `1.90M` so they align with numbers like `453K` they should stay that way, _unless_ there is way more data that can be added here?
  - What are the variants of numbers here? Will that make sense with the data?
- What's up with the Title Case On Labels? Are We Doing That On The Interface?

![image](https://user-images.githubusercontent.com/23194720/56433266-53b16400-629e-11e9-8542-d870f3fe43f0.png)

**Comment by austinhernandez** [comment]
Consensus on this on design + dev ticket:  
- This layout looks better and solves a lot of problems, but we came up with a list of considerations and product questions.

Considerations / product questions
- What if there are long activity names with the first part of the name?
- Are the `totals` auto-generated or can we take them out of form fields to save space?
- @jameshupp with content on "please verify these numbers are correct" #1407 
- Since this is a review of numbers. Do we need REAL $ values here or should we still round up?
- If we are restricting the $s to 3 digits and decimals, should numbers like $1.9M be translated to $1.90M so they align?
- What are the variants of numbers here? Will that make sense with the data?
- Greg says "we can add up to 3 Fiscal Yearz (FY)" so accommodate on layout
- On layer cake 2 idea: 🗡 Add a drawer underneath the activity to show more details and answer "where the heck did these numbers come from?!"

**Comment by austinhernandez** [comment]
New design from the dev design meeting 4/22

![image](https://user-images.githubusercontent.com/23194720/56519449-b9545900-6507-11e9-9a29-a9a31ce24e9f.png)

**Comment by austinhernandez** [comment]
4/22 Discussed at our weekly meeting:

Final mockup needs content review before moving to development implementation ticket.
![image](https://user-images.githubusercontent.com/23194720/56535731-07765600-6522-11e9-9048-5fe0c0fd9705.png)

This mockup reflects
- Showing the actual dollar amount.
- What we really need to show here is a summary of the activity, the total cost of the activity, the dates, the Medicaid share and the Federal Share.
- The save button will live outside of the content area. and @hbillings will try to put the save button in its own grid column in #1467 
- We will remove export as PDF (that will go under the export section.)
- @jameshupp a content review the content in this ticket before I make a ticket for implementation.
  - Casing on text
  - Save button
  - Fiscal years (FFY? FY? Fiscal Year? Fiscal year?)
  - Labels and their content. Review the following and comment
    - Total cost helper text (do we need it or not?)
    - Federal fiscal years requested: FY19, FY20, FY21
    - Medicaid Share: $1,500,000 ($1,450,000 Federal Share)
    - Total cost from APD: $13,939,200

**Comment by jameshupp** [comment]
Reactions to those same bullets:
* We decided to go with title case for anything that is reflected in navigation because it would be easier to scan in the left nav that way. So that's `Executive Summary` not `Executive summary` and `Activities Summary` not `Activities summary`.
* `Save` is fine as is for now. Initially I thought something like `Save progress` would make more sense, but as I think about it, the interaction itself and the left nav should work together to clarify that this isn't ending their work or anything, so let's leave it simple unless we hear during the pilot that it's confusing.
* FFY cost I'm addressing in its own comment because it's a bit more complicated.
* Labels!
  * **Helper text**, what do we think of this? 
    Verify that this information is correct. [Edit your activities](#) to make changes.
  * **FFYs list**
    Federal Fiscal Years requested: FFY 2019, 2020, 2021
    @hbillings Is this easy enough to be worth doing? Where we append `FFY` ahead of the first year and then give full years? Just seems clearer to me than FY19, FY20, FY21 when we've used FFY earlier, but repeating all three letters seems excessive.
  * **Medicaid share** is perfect as it is.
  * **Total cost**
    Total cost from this APD: $$$$
    I'm not sure about the word "from" here. @NAretakis and @jeromeleecms would you ever say it's the cost "of" the APD? It's the program, not the APD, that costs money. Do these costs come into play because someone submits the APD? Is "from" right in that way? Or is there another sense to understand it?

**Comment by jameshupp** [comment]
Okay, on how to say "cost per FFY" the best:

I can change `Each activity is listed with its total cost and cost per FFY.` to `Each activity is listed with its total cost and cost per federal fiscal year (FFY).` We've done that in a couple other places in the app but it's probably good repeat for this section. 

In general, when the choice is `FY` vs `FFY` let's use `FFY`. State fiscal years (SFY) are not always the same as federal fiscal years, and sometimes the states will default to using the state years if we aren't specific.

All that said ... the mockup here doesn't really show the cost being broken down per FFY. It just shows the total cost. So are we not showing per FFY anymore? If we're not this problem goes away. And the point I asked Heather about in the last comment becomes the only relevant one.

**Comment by hbillings** [comment]
@jameshupp Sure! I believe the data only contains the years and we're adding `FFY` to each of them anyway. We could just as easily only add `FFY` to the beginning of the list.

**Comment by jameshupp** [comment]
Since we're not recording FFY breakdowns for each individual activity in the Activity Summary, seems like the intro copy is entirely unnecessary. The labels and data that go with them are so clear in this new format that I don't think we need to describe what people are looking at. So how about just getting rid of the subhead? So: ~Each activity is listed with its total cost and cost per FFY.~

**Comment by jameshupp** [comment]
Sorry just to clarify: now that I've added my bit is the next task the creation of an implementation issue? Just want to make sure I move assignments and the like around correctly.

**Comment by jeromeleecms** [comment]
@jameshupp  Yes. Reading through this, it looks like all the design related topics are complete and this is ready for us to put into the dev queue.  Thanks for making sure we are following our process :)

@austinhernandez Since James' availability is a bit unpredictable at the moment, would you mind spinning up this issue with sufficient detail for the devs?

**Comment by austinhernandez** [comment]
All done with design and into development ticket #1491
