### ISSUE TITLE
Initial APD prototype - personnel

### ISSUE THREAD

**Issue by brendansudol** [18F/cms-hitech-apd#150]

**Comment by mgwalker** [comment]
Well, I reopened this because the current implementation doesn't match the content prototype.  However, I'm going to close it again because:

1. this page isn't part of the test protocol for the upcoming session
2. it's actually pretty complex, and I think we need to spend some time thinking about how we'll do form state management in the app longterm - our current solution would create kind of a rat's nest of code that we'd then just toss out anyway, so why spend the time on it?
