### ISSUE TITLE
Initial APD prototype - expenses

### ISSUE THREAD

**Issue by brendansudol** [18F/cms-hitech-apd#151]

**Comment by nkkl** [comment]
@mgwalker is task ready to close?

**Comment by mgwalker** [comment]
I don't think so.  We have code to support it, but I took the opportunity to fiddle with some different routing logic, file structure, etc.  There will be an ongoing conversation in #173 about some of that.

So, we can think of it two ways: yes, the prototype implementation is done and now we're discussing it from a code perspective; or no, the prototype implementation is not done because users can't test it yet.  I lean towards the latter, personally.

**Comment by nkkl** [comment]
Ok, let's keep it open, then.
