### ISSUE TITLE
Show a logout message or page

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1511]
[NIST 800-53 AC-12(1)](https://nvd.nist.gov/800-53/Rev4/control/AC-12) requires that we display an explicit logout message.  Currently when users log out, they are sent straight back to the normal login page.  We can satisfy this requirement either with a logout page or by adding a message to the login page letting know users they were successfully logged out.

### This task is done when...
- [ ] we know how we want to satisfy this requirement
- [ ] a design task is created to design the logout page/logout message on the login page
- [ ] a dev task is created to implement it

**Comment by austinhernandez** [comment]
Discussed 5/21 with dev! 

Rationale:
- Let the folks know they saved cuz that's real important! 
- I like the flow the way it is now! A log off redirects you back to the login screen, now it has an alert success message above
- Add a header title about "securely" being logged off cuz government

Flow and content questions:
@jameshupp on logout if a user needs to save, they see a system dialog that says "You have unsaved changes to your APD. Do you want to leave this page without saving? OK / Cancel" is this cool?
- If they don't need to save and they were logged out successfully, they are redirected back to the login screen (which is actually a "you are being monitored by the government" pre-login screen) and let them know, "Your changes have been saved and you've been securely logged out." What do you think?

**Successful log out**
![image](https://user-images.githubusercontent.com/23194720/58129590-0f401d80-7be8-11e9-8788-91d236164d4e.png)

**System dialog on sign out or back button (already exists)**
![image](https://user-images.githubusercontent.com/23194720/58130329-c8532780-7be9-11e9-9f1e-7e4af3ff3861.png)

Future thoughts:
- Modal instead of system dialog?

**Comment by jameshupp** [comment]
**Success alert**

* Since this is only for user-generated log-outs, do we want to say "you have securely logged out" (instead of "you have been...")? Clarifies it was active on their part, not something that happened to them.
* I would reverse them: "You have securely logged out. All your changes have been saved." I _love_ telling them the save worked, but let's lead with the thing they did most immediately.
* There's something a bit disconcerting to me about seeing that message and then immediately reading the "consent to monitoring" message below it. Right now it looks almost like they've logged out and we want them to let us monitor them anyway. What do you all think of adding a header on the login page that says `Log In`? That should help create some mental separation between the alert when it's present and the consent message.

**System dialog**
Looks basically right to me. Only question is whether there's value in specifying that they're about to log out, vs using a standard navigating-away dialog. I can't think of any reason to, but just trying to think about use cases.

**Comment by mgwalker** [comment]
#### Success alert

On point 3, we could enforce that logging out always goes to the login form and bypasses the consent screen.  It seems reasonable since a person who just logged out has, necessarily, already clicked through the consent screen before.

#### System dialog
Just a heads-up that we can only _suggest_ text there - there is no guarantee about what will actually be displayed. Chrome currently uses our text, even though it claims it doesn't, so who knows how long that'll last. All that to say, I'm not sure it's worth spending a lot of time making that message context-aware since users may not get to see it anyway.

**Comment by austinhernandez** [comment]
Thanks @jameshupp! I agree point 3 on the consent/monitor screen. Since it has the same URL as the login screen `https://hitech-apd.app.cloud.gov/login` I thought it could not be avoided! I 100% agree with @mgwalker if we can bypass that screen that would be ideal.

Thanks for the background on system dialog, Greg. 

@jameshupp - From our dev/design chat yesterday seems like a modal with custom text is too much work for Layer 1. This system dialog popup that we don't have much control over is a temporary solution. Here was the initial mockup and it would be great to have your thoughts on this so it's ready for a future release, though!

Proposal for Layer 2:
![image](https://user-images.githubusercontent.com/23194720/58185101-62fe4580-7c80-11e9-936c-fff9dd090410.png)

---- 

But for now, I will use this design and text for the implementation ticket. 
![image](https://user-images.githubusercontent.com/23194720/58185057-4d891b80-7c80-11e9-8afa-fb75fdb15808.png)

**Comment by jameshupp** [comment]
Looks awesome to me!
