### ISSUE TITLE
Implement the Private Contractor Costs subsection using CMS design system

### ISSUE THREAD

**Issue by austinhernandez** [18F/cms-hitech-apd#1522]
From the design ticket #1463 we are ready to implement!

Final mockup:
![image.png](https://images.zenhubusercontent.com/58938fe151aa2c3057735ca5/ce5628ba-62a5-4626-874d-d352a81a6a75)

### This task is done when...
 - [ ] The Private Contractor Costs section looks like the mockup
 - [ ] Use the [review pattern](https://design.cms.gov/patterns/review/) from the CMS design system  / the [Key Personnel pattern](https://hitech-apd.app.cloud.gov/apd#apd-state-profile-key-personnel) from the current app
 - [ ] Designers approve! 
 
Details:
- This design was decided upon on 5/7 as part of our post-standup parking lot session.
- Don't worry about the exact pixels heights from this mockup, I am using the [review pattern](https://design.cms.gov/patterns/review/) from the CMS design system.
- The action to edit opens the section up again, like [the Key Personnel section](https://hitech-apd.app.cloud.gov/apd#apd-state-profile-key-personnel).
- The action to remove prompts you with an "Are you sure?" modal.
- Bold the labels, this pattern does not exist in other parts of the CMS (like [the Key Personnel section](https://hitech-apd.app.cloud.gov/apd#apd-state-profile-key-personnel)), but it is a pattern the team would like to follow for the review section.
- Don't truncate text, leave her as long as she wants to be!

**Comment by mgwalker** [comment]
Working on this one now.  Some questions for @austinhernandez:

- At the bottom of the form, there are separate "done" and "cancel" buttons, but we can't (currently) actually cancel - each change is saved to the browser copy of the APD as soon as they happen and we can't back them out.  On the key personnel form, which also uses the review pattern, we just have a "done" button. Should we adopt the same approach here?
- The default behavior of the design system date field is to put the field name above the input boxes rather than on the same row.  It also has a "hint" by default, but we can turn it off.  Here's a screenshot showing what I mean (default hint for start date, hint turned off for end date). Question is, should we use these defaults (label position and hint text), or move the label and turn off the hints?

    ![Screen Shot 2019-05-17 at 10 20 26 AM](https://user-images.githubusercontent.com/1775733/57938297-89da0780-788d-11e9-9de3-0d7770864f09.png)

**Comment by mgwalker** [comment]
Another question for Austin + @jeromeleecms or @NAretakis:
- Currenly, users can either enter total cost for the FFY or they can enter hourly costs, but not both. This design seems to enable both.  Should users to be able to enter both, or should they have to choose one or the other?  If they have to choose, maybe the "this is an hourly resource" checkbox can default to unchecked and then they see the appropriate forms based on what they select?
