### ISSUE TITLE
Review the layout and interactions of the app for the pilot

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1638]
Review the functional aspects of the app and check that it is working as expected.

### This task is done when...
 - [x] The design system has been applied to all the sections
 - [ ] The layout is appearing as expected
 - [ ] The design interactions are working as expected

**Comment by austinhernandez** [comment]
Here are all the bugs I found on my most recent audit (others have been documented elsewhere). Do these need individual tickets @hbillings @mgwalker?

- [ ] **HTML displaying plain text**
<img width="997" alt="Screen Shot 2019-06-28 at 2 54 05 PM" src="https://user-images.githubusercontent.com/23194720/60368943-28df3c80-99c0-11e9-8a05-a6acbc549dd0.png">

- [ ] **more bottom spacing on medicaid director, H3?**
<img width="671" alt="Screen Shot 2019-06-28 at 3 02 59 PM" src="https://user-images.githubusercontent.com/23194720/60368944-28df3c80-99c0-11e9-92b8-fe84df2847c1.png">

- [ ] **Remove button under Key Personnel... doesn't ask "are you sure" when you click it**
<img width="715" alt="Screen Shot 2019-06-28 at 3 04 15 PM" src="https://user-images.githubusercontent.com/23194720/60369048-72c82280-99c0-11e9-9ed3-a3433ec16bd8.png">


- [ ] **Too much spacing**
<img width="648" alt="Screen Shot 2019-06-28 at 3 20 11 PM" src="https://user-images.githubusercontent.com/23194720/60369051-7360b900-99c0-11e9-9992-cea225e53a38.png">

- [ ] **Emojis are cool, but could we remove them so the link icons fit on one line**
- [ ] **Can the labels extend the full width if the textarea and blue background helper section do?**
<img width="251" alt="Screen Shot 2019-06-28 at 3 05 56 PM" src="https://user-images.githubusercontent.com/23194720/60369050-72c82280-99c0-11e9-8717-74275ba42173.png">
<img width="632" alt="Screen Shot 2019-06-28 at 3 21 30 PM" src="https://user-images.githubusercontent.com/23194720/60369052-7360b900-99c0-11e9-91cc-6e72c7a915c1.png">

- [ ] **Remove button doesn't ask are you sure on click in private contractor costs**
<img width="633" alt="Screen Shot 2019-06-28 at 3 25 58 PM" src="https://user-images.githubusercontent.com/23194720/60369053-7360b900-99c0-11e9-8b9b-027afc811b4d.png">

**Comment by mgwalker** [comment]
The HTML-as-plaintext was fixed in #1565, when the benchmark text was switched from a rich text field to a plain text area. We probably have old data in the database that still has HTML in it, and that's why you're seeing that. This is what it looks like now:

![image](https://user-images.githubusercontent.com/1775733/60443995-edbc5380-9be1-11e9-9234-e4f9ef112c91.png)

Those dashes are each in their own line on the form, though - should line breaks in the user-supplied text also be rendered in the review view?

---

- created #1646 for vertical spacing on the Medicaid director form headings
- created #1647 for the key personnel delete prompt
- created #1648 for vertical spacing on the activity overview
- created #1649 for the emoji button
- created #1650 for making the form label width match the rich text field width
- created #1651 for the contractor resource delete prompt

**Comment by NAretakis** [comment]
@austinhernandez reviewed and several issues were created. This is good to close.
