### ISSUE TITLE
Fix issues in Exported PDF

### ISSUE THREAD

**Issue by austinhernandez** [18F/cms-hitech-apd#1644]
I reviewed the PDF export of the APD on Chrome using Windows OS
[eAPD Chrome on windows export- annotated.pdf](https://github.com/18F/cms-hitech-apd/files/3340672/CMS.__.HITECH.__.APD-Chrome-windows.pdf) The PDF is annotated with fixes and the tasks are marked below! Some of these issues exist in the app and will fix the export. Some are export specific.

### This task is done when...
- [x] Page 1: Is this page intentionally left blank as a coversheet? 
- [x] Page 2: Bold labels
- [x] can we do `[name], [role]`? instead of `[name] <br> [role]` **[Edit from Heather: I think this is due to old data that has the HTML in it, rather than the layout itself?]**
- [x] should we remove edit and remove links for the PDF so that text can expand the full width?
- [x] Darken section number
- [x] Bold labels (time commitment:, total cost:, etc.)
- [x] Page 3: Bold labels
- [x] Remove white space
- [x] Page 4: The checkboxes don’t render as checked
- [x] Page 5: Can the `<textarea>`s collapse or can we remove extra spacing from textarea?
- [x] Page 6: Can the `<textarea>`s collapse? 
- [x] Can we move the sections up or does it need to start on a new page?
- [x] Page 7: Darken section number
- [x] Page 9: Bold labels
- [x] Remove action buttons like edit and remove
- [x] Darken the `Activity 1: Program Administration (HIT)` text
- [x] reduce the vertical spacing / white space between `Activity Overview` and `Please provide a short overview of this activity`
- [x] Page 10: Headings and helper text can expand the full width
- [x] Page 11: HTML is showing up in benchmarks
- [x] Remove Edit and Remove buttons
- [x] Remove double line
- [x] Remove empty date picker table
- [x] Add spacing around `Milestones header`
- [x] Page 12: remove double line
- [x] Remove Edit and Remove buttons
- [x] Page 13: remove  Edit and Remove buttons
- [x] Page 14: remove textarea padding
- [x] Pages 16-21: Content not displaying in Standards and Conditions sections! (Modularity, Medicaid IT architecture, industry standards, etc)
- [x] Pages 21-78: Same bugs as in activity 1, (see pages 9-20)
- [x] Pages 79: Darken section number
- [x] Pages 84: Remove white space
- [x] Pages 85: Darken section number
- [x] Radio buttons not selected, and you can select in PDF
- [x] one of the sections is cut off, do we have control of this?
- [x] Pages 86: Extend full width
- [x] Pages 87: Darken section number
- [x] Pages 89-90: LOL just remove the footer!

**Comment by hbillings** [comment]
This is a fantastic list!! Thanks, @austinhernandez!

Just entering this here because it's Friday afternoon and I don't want to forget: the "cover page" issue and subsequent blank page problems seems to be caused by something inherent in the `section` element. Changing our `section`s to `div`s removes it. Trying to track it down, but so far it's proving mysterious...

**Comment by hbillings** [comment]
Some more notes:

- The HTML showing up is an artifact of old data.
- The `Milestones` header seems like it might actually be the wrong heading level, so I'm ignoring until after we do the heading level audit.

Seems like we've got a couple buckets of work left:
- Collapsing `textareas`
- Getting radio and checkboxes to print correctly (I think this is due to them relying on a background color, although the fact that they're selectable in PDF form is... weird).

**Comment by hbillings** [comment]
It looks like the `Standards and Conditions` section blankness is caused by... wait for it... not having any content in those sections! 🤦‍♀ This does raise the issue, though, of whether we should have some indicative text when a field is blank?

**Comment by hbillings** [comment]
DONE
