### ISSUE TITLE
Get staging site domain

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#1690]
### This task is done when...
- [x] we have a pair of staging domains
   We can use CNAME records, just like we did for production. We can get them from AWS as soon as we need them
   - [x] for frontend (for example, staging-eapd.cms.gov)
   - [x] for backend (for example, staging-eapd-api.cms.gov)
- [x] we have a pair of SSL certificates
   - [x] for frontend
   - [x] for backend

**Comment by NAretakis** [comment]
Ok, last time we did we needed:

Domains - @jeromeleecms are you good with these?
 * staging-eapd.cms.gov & staging-eapd-api.cms.gov

CNAMES to point the domains to - @mgwalker can you provide us these:
 * [CNAME frontend]
 * [CNAME api]

With that info, I can get rolling on the domains.

**Comment by mgwalker** [comment]
[CNAME frontend]: dmi14i0aw7he4.cloudfront.net
[CNAME api]: eapd-staging-actual-190846704.us-east-1.elb.amazonaws.com

**Comment by jeromeleecms** [comment]
@NAretakis Anything I can do to help make this a reality?

**Comment by NAretakis** [comment]
Akamai ticket created for this: https://jira.cms.gov/browse/WAKA-6358

details are:
We are working on setting up our AWS infrastructure for the HI-C (eAPD) app, and are now at the point where we need a staging domain to continue. We currently have eAPD.cms.gov which is working great, however we are now requesting staging domains in order to support our application with a staging and prod environment.

We already have our VPC setup. This issue is to request the domains below, so that we can connect and enable the rest of our app. Please reach out if you have any questions or if additional information is needed to get this rolling.

Domain names we need:
**staging-eapd.cms.gov** for this one the CNAME should be: **dmi14i0aw7he4.cloudfront.net**

**staging-eapd-api.cms.gov** for this one the CNAME should be: **eapd-staging-actual-190846704.us-east-1.elb.amazonaws.com**

**Comment by jeromeleecms** [comment]
@NAretakis Following up to see if you need more information about the configuration errors that we are currently experiencing.

cc: @cthulhuplus in case you want to add more detail.

**Comment by mgwalker** [comment]
Are there new certificates? `staging-eapd-api.cms.gov` is using the certificates for `eapd-api.cms.gov`, which is causing a certificate error there. Not sure if CloudFront might just explode if it's given invalid certificates for the domain it's supposed to be serving.

**Comment by cthulhuplus** [comment]
@mgwalker there are not. When I was looking in CloudFront there were no CNAMEs for the staging environment. I explored adding it myself, but it required certificates so I stopped and reported back to @jeromeleecms since it seems like CMS is responsible for creating our certs and were supposed to set up the CNAMEs.

**Comment by jeromeleecms** [comment]
Certificates loaded and staging servers seem to be working. Any additional work need to be done here?

**Comment by jeromeleecms** [comment]
This is complete. @NAretakis Feel free to reopen if needed, but thank you for the getting the ball rolling on this.
