### ISSUE TITLE
Test updating the font size for the numbers in the tables to 16

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1737]
As a result of implementing more of the design system components in the tables in https://github.com/18F/cms-hitech-apd/pull/1722, the font sizes of the table values are 12 and 16 and should be consistent. 

For example:
![image](https://user-images.githubusercontent.com/21222704/62171248-33ecfb80-b2e3-11e9-9e6d-628d12c98b81.png)

Previously everything was 12, but according to the design system, it should be 16. Let's try seeing what it looks like to bump all of the numbers in the tables to 16 and if it blows up the layout, we can see which size works best.

### This task is done when...
 - [ ] We can see what it looks like and what it does to the page with all of the numbers in the tables at 16
- [ ] We figure out which font size all of the values in the tables will be
- [ ] The numbers in the tables are consistently sized

**Comment by hbillings** [comment]
I bumped up the font size and scanned through the tables. All of them are okay except the very last MMIS table, which is too wide for the container:
<img width="1186" alt="Screen Shot 2019-09-23 at 4 14 39 PM" src="https://user-images.githubusercontent.com/509309/65467109-df1abc80-de1d-11e9-85f4-be245b408bf7.png">

We could either rejigger this table so that the 90/10, 75/25, 50/50, and total columns are each in their own table, or we could keep the font at 12px.

**Comment by lauraponce** [comment]
Circling back to this after you brought it up in standup, 12px seems like the easier way to go with this (and it's what we've been using) so it seems fine to keep it. We also haven't heard feedback from users saying it's too small to read.
