### ISSUE TITLE
v1 list of user types and roles

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#179]
Need to determine a list of user types and the functionality that is associated with each role. 

### This task is done when...
 - [x] A list of user types is drafted
 - [x] User functionality is described within the document
 
 ** don't forget to fill out the LABEL, MILESTONE, and PROJECT sections before submitting (then delete this line) **

**Comment by mgwalker** [comment]
I'm not sure it's necessary to come up with a list of user types right now - that will emerge as we go along.  That list is also not in the code, so we can easily add it after the fact without making code changes.  I'm okay with leaving this as an ongoing issue, but also okay with closing it once we've got some documentation about activities/roles.

An idea for what that document might look like:

---

### Activities

Permission to perform different actions in the system is controlled by "activity" permissions.  These are fine-grained controls.  An "activity" refers to a specific action that the API can perform, and the API only performs those actions for users who are logged in and who have the activity permission.  Other requests are denied.

|Activity|Description|
|---|---|
|view-users|Allows the user to view the list of all users or a specific user in the system.|
|add-users|Allows the user to create a new user in the system.|
|view-roles|Allows the user to view the list of all roles in the system.|
|create-roles|Allows the user to create a new role in the system.|
|edit-roles|Allows the user to modify an existing role in the system.|

> The list of activities is defined in code and cannot be modified.  Adding activities to the database will have no effect, and renaming or deleting existing roles is effectively the same as denying all users that permission.

### Roles

Rather than assign a whole bunch of activities to each user in the system, a group of activities can be combined into a role.  A user who belongs to a role automatically gets all of the activity permissions associated with the role.  The system comes with some default roles, but those roles can be modified and new roles can be created as needed.

|Role|Activities|
|---|---|
|admin|view-users<br>add-users<br><br>view-roles<br>create-roles<br>edit-roles|
|cms-reviewer||
|state-submitter||

**Comment by NAretakis** [comment]
Ok, basic user roles and activities document has been created. We can revise and add as needed. I used your model @mgwalker. [Hopefully it makes sense.](https://docs.google.com/document/d/1Nvoy1NZ6G_-qvwKBe-28vB6gg0z6G3_JemMsAez8mqY/edit#)

**Comment by mgwalker** [comment]
Just skimmed it.  This is *fantastic*.
