### ISSUE TITLE
Add date range to top of APD in the app

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1820]
From our federal reviewer research in the pilot, it came up that having the full range of years that the APD is covering would be more helpful than just the first year. For example instead of Texas 2019 APD, it would be Texas 2019-2021 APD.

### This task is done when...
 - [ ] Update the year at the top of the APD to be the range of years for which they are requesting funding based on what they select in the app.

![Screen Shot 2019-09-16 at 3.50.19 PM.png](https://images.zenhubusercontent.com/57f4106595e42b6c5ba9e43c/20cec4fe-177a-4e6d-b40b-4695ab8d63d8)

**Comment by jeromeleecms** [comment]
This is not prescriptive redesign directive, but if remove the unique identifier and add the dates, we can also think about how this scales for other types of APDs (sample rework of how it might look). In lieu of `Implementation`, we could simply put `Planning `or `Operation`...

![image](https://user-images.githubusercontent.com/34279968/65057244-2b01c900-d927-11e9-8e41-20bd41a8eb8b.png)

The State name appears duplicative, but makes sense since we need it for exporting the document to PDF. 

Also, when we export, can we add the final name to the header where it currently resides? Sounds like a separate issue, but just documenting it here.

**Comment by jeromeleecms** [comment]
Is there some flavor of #1427 in here?

**Comment by mgwalker** [comment]
Did we decide what this should be? `Texas 2019-2021 APD` like the original issue says?

**Comment by lauraponce** [comment]
From my understanding, that's correct.
