### ISSUE TITLE
Show calculated total for FTE's within the app

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1824]
From reviewer feedback, it is not clear that a calculation occurred within the FTE field. Similar to #1792, we should look to provide transparency when math is being done. 

![image (1).png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/8977eccb-96f8-49f7-a0af-a75bc187de44)

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/e138cd8b-0a70-4dff-aae5-1a784aa3a9e1)

It may be as simple as adding the calculated total to the end, but would want a quick design look at this.

### This task is done when...
 - [ ] Design has provided guidance on how to show the total
- [ ] Product has approved
 - [ ] Appropriate issue has been spun up

**Comment by lauraponce** [comment]
For the preview of the already entered costs, here is a version that shows the total calculated amount:

<img width="608" alt="Screen Shot 2020-01-09 at 4 28 38 PM" src="https://user-images.githubusercontent.com/21222704/72115830-2bbad280-32fd-11ea-8f58-882a1053f235.png">

Another thought is that we could alternatively only show the total calculated amount in the preview and if they want to see more details, they'd have to click into it. This reduces the amount of information to pay attention to on the page:

<img width="602" alt="Screen Shot 2020-01-09 at 4 32 51 PM" src="https://user-images.githubusercontent.com/21222704/72116051-d7642280-32fd-11ea-98bb-5f6e5a12ccca.png">

Following the pattern we've been using where editable values are in the input fields and auto-calculations are not, I put the total below so that the math be visible in the same view as where they're editing:

<img width="623" alt="Screen Shot 2020-01-09 at 4 28 51 PM" src="https://user-images.githubusercontent.com/21222704/72115823-278eb500-32fd-11ea-9265-1003cb9af578.png">

@jeromeleecms what are your thoughts on this?

**Comment by lauraponce** [comment]
The final mocks are ready for development based on our sync earlier:

Editing view

<img width="357" alt="Screen Shot 2020-01-13 at 2 01 43 PM" src="https://user-images.githubusercontent.com/21222704/72296097-b35e5500-360d-11ea-9b61-ce4d3310f988.png">

Preview view

<img width="597" alt="Screen Shot 2020-01-13 at 2 01 32 PM" src="https://user-images.githubusercontent.com/21222704/72296134-c96c1580-360d-11ea-8ef0-ea5c439ed176.png">

cc @hbillings
