### ISSUE TITLE
Recruit participants for testing the updated activities section

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1858]
### This task is done when...
 - [x] Participants are recruited
 - [x] Sessions are scheduled

**Comment by CSwartzHMA** [comment]
@lauraponce @jeromeleecms Please take a look at this draft email language and let me know if you have any suggested edits:

Hello!
We want to provide an update on the progress CMS, MeT, and 18F (GSA) have been making together to modernize the HITECH IAPD creation and submission process. As part of the development of the eAPD (an online application that helps states submit IAPDs and associated contracts easily and is also intended to help CMS analysts review them more efficiently), we have conducted numerous usability sessions to get input from states on the design and features of the app, taking into consideration many of the common issues states identified with the current IAPD submission process.
You also hopefully heard that a few states had an opportunity to pilot the use of the new eAPD, Following the development of an IAPD in the app, feedback was collected from the pilot states. Building on the feedback received to date during the pilot and during earlier state user testing session, improvements have been made to the app. 
We are now seeking four states to volunteer to review these updates. Selected states will be scheduled a one hour meeting during which a walk through of the updated version will be presented. Observations and feedback will be captured during the call. States will have the opportunity to have a direct impact on the changes made to the app before nationwide release.
If you are interested, please email CMS.AllStates@briljent.com by November 6, 2019.



Also, please confirm that this should be sent as an All States email rather than targeting only pilot states or another subset of states. @lauraponce mentioned we are looking for 4 states and that we are hoping for at lease one to be a pilot state, so it sounds like we want to throw this out to all of the states.

**Comment by lauraponce** [comment]
@CSwartzHMA is this going to every state or just the ones that volunteered for testing and have been added to the distribution list? If it's the latter, we might be okay to cut out a lot of that context. 

Here is an example of what we used for a past round:

> We (18F and CMS) are continuing our work to improve the APD experience and are about to begin another round of user interviews related to APD updates. If you'd like to participate, please fill out this Google Form with your availability on 6/10 and 6/13. At the end of this week, we'll send out the confirmations for the sessions.

> We really appreciate your time and input on this project. Feel free to reach out if you have any additional questions!

Using the Google Form with the dates and times made it easier to wrangle all of the volunteers rather than working from their schedules. I'm not sure if you have access to create one, but I can help with that if you want to go that route!

**Comment by CSwartzHMA** [comment]
So, I was not aware we had a distribution list. I took much of this from the pilot email that went to the all states distro the MeT uses. Do we want to stick to just the smaller list of states? That should still get us a broad enough list that we should get at least 4 volunteers. 
I can create a google form for scheduling and hope states can access it. It looks like that was used previously, so I say we give it a shot! I will work on the google form and try to get this out today.

**Comment by lauraponce** [comment]
Sounds great! Here is the email distribution list: cms-testers@gsa.gov (this includes a subset of states that volunteered for testing and asked to be included, I think it's about 20-30).

**Comment by CSwartzHMA** [comment]
Here is the Google Form. Please let me know if it looks ok. If so, I will send along to the distribution list.
https://docs.google.com/forms/d/1Lern-vDiBnA8j7qBgSMUy3GAcCJmTnbgfOKSJs9sAbM/edit

**Comment by CSwartzHMA** [comment]
Recruitment email has been sent.

**Comment by CSwartzHMA** [comment]
Sessions have been scheduled with MA, DE (Pilot), KY and CA. Additional responses received from MI and Bill Pickert (I am not sure which state he is with), but the first 4 respondents were scheduled. I believe this issue can be closed, but will confirm with @lauraponce and @jeromeleecms that we need only 4 interviews. Once confirmed I will send wrap up email to MI to let them know we are full and will try to find an email address for Bill so I can close the loop with him also.
