### ISSUE TITLE
Explore help text in activity, goal, objective section

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#191]
Participants didn't interpret the structure and language of the activity, goal, and objective sections in a consistent way, and were sometimes confused about the relationship between different elements. Adding help text may make things easier for them.

### This task is done when...
 - [x] Problem areas/areas where helper text may be useful have been identified
 - [x] One or more approaches to helper text have been drafted
 - [ ] Help text implemented in the UI so that it can be tested

Related to #190

**Comment by quarterback** [comment]
Based on the demos & user testing, I think it'll be easier to make a better assessment of where helper text would be most useful and not just going to confuse people more.

**Comment by lauraponce** [comment]
Carrying over the notes from our synthesis discussion earlier – another opportunity for help text is the Select expenses section. One user was confused and said: 

> “Facilities? What is that? Is that rent? We've put it in training and outreach, if we had to find somewhere to hold a symposium, it might be a training & outreach.”

**Comment by quarterback** [comment]
Help text modeled in a fork of the original content prototype: https://docs.google.com/document/d/1C0KvJ5zMuTOIRSTqyHpSZU7T3aLbqm7U4EdJwIynpJw/edit?usp=sharing

**Comment by quarterback** [comment]
I created a new issue #368 which is the successor to this issue. We already know where the problems areas are, and given the conversations in testing and in our meetings over the past few weeks, it's clearer that we need help text for _all_ sections, not just a few problem areas. 

Because this will be a beast of an issue, it's better to start tackling this issue now, since we can use the existing document to develop messaging around the different tasks required for submission of the APD document, and it'll make it a lot easier to implement later.
