### ISSUE TITLE
Connect high level vision with SMHP

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#193]
Participants commented that many of the initial questions about the HITECH program felt redundant with the State Medicaid HIT Plan (SMHP), which they considered to be their core vision reference document. We should explore ways to connect the SMHP with the early parts of the APD submission to alleviate the feeling of redundancy.

### This task is done when...
 - [x] One or more models for connecting the SMHP to the APD have been explored
 - [x] A model has been chosen for implementation
 - [ ] The chosen model has been integrated into the UI so that it can be tested

**Comment by jeromeleecms** [comment]
Put a draft for 4 potential models with some textual descriptions for each. Didn't do a SWOT analysis on it, but happy to get feedback from @lauraponce and/or @quarterback if you want to put more detail under each model.

[Document in Drive](https://docs.google.com/document/d/1v0BDJWL8pl_RLlLrWWz8cw6gc39i-_NDIEfgA4qVwEg/edit#heading=h.ydf9tvjedq9h)

**Comment by nkkl** [comment]
Cool, I like it. What's our preference here?

**Comment by jeromeleecms** [comment]
@nkkl I prefer the separate state profile since it will allow us minimize redundant questions and abstract areas of the APD which are not specific to a particular activity. In HIE (completing #327 may make this more clear), if there are multiple HIE activities, the application won't have to ask multiple times regarding the state's HIE strategy, governance, value proposition, sustainability model, etc. which are helpful for us to make a decision, but may not be critical to the narrative of the activity itself.

Of course... Design may have come up with a way to avoid this redundancy so I can always be convinced/swayed another direction if their upcoming design solves this problem in a different way - happy to wait until they weigh in.

**Comment by nkkl** [comment]
That makes sense to me! If we don't have time to implement that, we can always walk it back to one of the other solutions.

**Comment by jeromeleecms** [comment]
Talked this over with @NAretakis. Model #1 from the drive document has been tied into #402 and can be tied into the UI once Dev has had a chance to incorporate this into the prototype. Closing this pending testing.
