### ISSUE TITLE
Design table for staffing across activities

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1937]
We heard from users in the latest round of usability testing (and it's also come up in previous rounds) that it'd be helpful for them to see staffing across all of their activities and not just _by_ activity.

### This task is done when...
 - [ ] There is a mock-up of a table that includes staffing across activities

**Comment by beparticular** [comment]
User Needs as discussed:
State users want to see a holistic view of staff (number of staff and budget items) across all activities and all years so that they can:
- Get a gut check to verify the information they entered is correct
- For anyone else who might look at the eAPD who didn't enter the information to get a summary
- This includes other folks preparing the eAPD or officers reivewing the information

**Comment by jjames521** [comment]
Here are some tables to check out added in kerning for the description which I think adds some readability to it.

Let me know your thoughts! @lauraponce @beparticular @jeromeleecms 

![StaffDrillDownVer1.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/36197c1d-0e3b-4f3b-8721-44a2efaa20b5)

Variant with no spacing and bold/highlighted/italic OTHER in description
![StaffDrillDownVer2Variant.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/fbf41ab2-3b68-4bd5-99b6-ad351d4e3a70)

**Comment by jeromeleecms** [comment]
@jjames521 @beparticular @lauraponce
Shaping up nicely -- I'm leaning towards the one with more spacing between tables (easier to read).

Some questions/thoughts (we can do a walkthrough of these tomorrow if it would help clarify):
 
1. Should the state staff have it's own subtitle/heading? We have one listed for "Other State Expenses"  
2. Thoughts about having a separate "Other state expenses" subtotal as well for consistency with the state staff section? 
3. Does indenting help readability? I edited activity 1 with some indents as an example.
4. Also, since we wrapped other costs in here, we should name this section "State Costs Summary." 
5. For the summary table, I think there may be a confusion about the math and some language, so mocked up how the math would fall out. Other costs come from the other grants/cost allocation (so would not be additive) and are different from the "Other State Expenses" (which are non personnel costs). I added a minus sign and circled it so the team knows where the number is deducted.
6. I'm a little torn about how we would want show the source of the calculations for "Other Costs" -- probably can talk through this as well.

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/e9e43b05-b3dd-472f-be46-1e6894afc688)

Appreciate all the thought and effort put into this!

**Comment by jeromeleecms** [comment]
This is good to go on my end. Spoke with @beparticular over Slack and she is OK with moving this forward as well. Future state, we'll have a way for her to also give her approval before design tasks are completed.

@pphillips-fearless @mgwalker Please create/convert this to a dev task. It can be placed at the top of the prioritized backlog once you've decided the best way you want to track this issue.

**Comment by mgwalker** [comment]
Since this won't go in until next sprint, I think it might be good if we put some time in next week's working session to talk about this one to make sure we capture the dev requirements properly. I suspect this one will be gnarly because it will require updating the budget reducer, which is where all the math happens.

What do you think, @pphillips-fearless?

**Comment by pphillips-fearless** [comment]
I'm fine with putting it into next week's discussion.  I would like a more technical discussion of the mechanics of the "budget reducer", so if that's not of interest to the rest of the team we might want to split it out as a side meeting for the dev team.
