### ISSUE TITLE
Determine what to do with the Save Button in light of the Autosave functionality

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1980]
Should we remove the button? Should we do something else?

Removing the button would fix the bug that prevents users from typing in text fields that share the same space as the error message.

### This task is done when...
 - [ ] We know where to put the Save Button information within the application
 - [ ] Mock-ups have been made
- [ ] Dev Approves
- [ ] Product Approves

**Comment by lauraponce** [comment]
Can be picked up by anyone!

**Comment by lauraponce** [comment]
Background context: the original reason for moving the save button out of the left nav to the bottom right was to make it easier to see since when the navigation is fully expanded, it pushes down whatever is at the bottom and you have to scroll to see it. 

What's different now is that users don't have to interact with the save button because we now have autosave so the button is less important to be in view at all times. We don't even need the physical button but we _do_ need a way to communicate the information that the button is currently displaying (i.e. saved, saving, save failed).

I think this could be a great use for the badge component in the design system because we only need to share a small bit of information about the current save state. The alerts would stay in the same place as they are currently.

Most common use cases:

<img width="885" alt="Screen Shot 2020-02-04 at 5 41 59 PM" src="https://user-images.githubusercontent.com/21222704/73803653-4e160380-4776-11ea-9a2f-116554240a9d.png">

<img width="834" alt="Screen Shot 2020-02-04 at 5 49 16 PM" src="https://user-images.githubusercontent.com/21222704/73803810-b9f86c00-4776-11ea-8828-f4ac60eff964.png">

Less common (error & warning states) use cases:

<img width="889" alt="Screen Shot 2020-02-04 at 5 42 42 PM" src="https://user-images.githubusercontent.com/21222704/73803677-5f5f1000-4776-11ea-9ca0-5d896bf34781.png">

<img width="885" alt="Screen Shot 2020-02-04 at 5 42 27 PM" src="https://user-images.githubusercontent.com/21222704/73803686-6554f100-4776-11ea-839d-a7efd1fdecb5.png">

@jeromeleecms @hbillings @mgwalker would love your thoughts on this approach 💭

**Comment by jeromeleecms** [comment]
Been thinking through this ... what if we also tried a hybrid-ish approach to this @lauraponce?

1) I like the sticky header - can we just remove the badge and report "Saving..." followed by the last "Save Time"... ?  That way people won't try to click on the badge. 
2) The error could be included right below the message as you had in your last mock-up...

![image](https://user-images.githubusercontent.com/34279968/74063980-7edc7f80-49a6-11ea-9841-04e6dc090ca0.png)

(And yes, if you were curious, this thought is heavily inspired by Google's autosave pattern)

![image](https://user-images.githubusercontent.com/34279968/74064148-ed214200-49a6-11ea-8500-230a06da60c6.png)

**Comment by lauraponce** [comment]
I think that would work well, and I'm all for trying the most subtle version first so it doesn't draw attention more than necessary, here's how that looks:

<img width="827" alt="Screen Shot 2020-02-07 at 1 36 33 PM" src="https://user-images.githubusercontent.com/21222704/74067904-2198fc00-49af-11ea-816a-0f1799154c84.png">

<img width="734" alt="Screen Shot 2020-02-07 at 1 44 23 PM" src="https://user-images.githubusercontent.com/21222704/74068240-ff53ae00-49af-11ea-8f42-ed4219a54903.png">

<img width="835" alt="Screen Shot 2020-02-07 at 1 36 47 PM" src="https://user-images.githubusercontent.com/21222704/74068251-05498f00-49b0-11ea-82f1-fec791861b25.png">

It'll be good to test if the error message is better placed at the top or bottom of the page where it's visible enough and doesn't get in the way of fixing what caused the errors.

What do you think about this, @jeromeleecms?

**Comment by jeromeleecms** [comment]
I like the subtle look and def. the thought around where to place the error message.

Let's talk through what to test as you scope out #2034.

**Comment by mgwalker** [comment]
😍

**Comment by lauraponce** [comment]
Closing this and will test in #2034
