### ISSUE TITLE
No description or help text for the quarterly FFP table

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#2057]
The quarterly FFP table is presented to the user with no context, no description, and no help text. It's no wonder users are confused by what it's for. 😅 

![screenshot of the quarterly ffp table showing there is no description or help text](https://user-images.githubusercontent.com/1775733/74345958-77d1ba80-4d74-11ea-9f0a-2a79b036f32d.png)

### This task is done when...
 - [x] we have description and/or help text to go before the quarterly FFP table

(We can turn this into a dev task when that's done.)

**Comment by jeromeleecms** [comment]
@lauraponce Would you mind doing a read through / edits? On a related note -  I miss our content team.

Quarterly Medicaid FFP Amount (<- h4?)

Provide a percentage estimate for the amount of Medicaid FFP needed for this activity by each Quarter of the FFY. 

(Help Text)
The total Medicaid FFP for each FFY was automatically calculated by applying the requested Federal/State Split against the total cost of the Activity minus the amount of Other Funding (i.e. the Medicaid Share). The auto calculated dollar values for each quarter should align with the state's quarterly CMS-37 request.

**Comment by lauraponce** [comment]
It could be helpful to include a "for example" in there to give states an idea about what you're expecting as a reviewer here. Are there a couple of scenarios you could add, maybe one where it's split evenly for each quarter and a scenario where it changes quarter to quarter?

**Comment by jeromeleecms** [comment]
Thanks, @lauraponce!! Adjusted per feedback. Merged some of the help text into the instructions and used the help text to provide an examples...

Quarterly Medicaid FFP Amount (<- h4?)

Provide a percentage estimate for the amount of Medicaid FFP, taken from the "Calculated Medicaid Federal and State Share" table, needed for this activity by each Quarter of the FFY. The auto calculated dollar values for each quarter should align with the state's quarterly CMS-37 request. As a reminder, In-house costs equals State Staff + Other State Expenses.

(Help Text)
Input a higher percentage in quarters where there may be non reoccurring costs and adjust the other quarters downward to ensure the totals do not exceed 100%. Examples of non reoccurring costs include one time state equipment purchases (in-house costs) or payments on a contract deliverable (private contractor costs).

**Comment by lauraponce** [comment]
This reads fairly technical to me, but maybe it's just because I'm not familiar with the `state's quarterly CMS-37 request`? Added some tweaks and questions below :) 

Quarterly Medicaid FFP Amount -> **Estimated Quarterly Expenditure** 

**For each quarter, enter the percentage of the total Medicaid FFP cost that will be spent in each category. The auto-calculated dollar values for each quarter should align with the state's quarterly CMS-37 request. As a reminder, In-house costs equals state staff + other state expenses.** 

I see what you were trying to do with the `taken from the "Calculated Medicaid Federal and State Share" table` part, but it isn't clear to me what's taken from that table. Is there another way to phrase it?

Help text:

**Input a higher percentage in quarters where there may be non-reoccurring costs and adjust the other quarters downward to ensure the totals do not exceed 100%. Examples of non-reoccurring costs include one-time state equipment purchases (in-house costs) or payments on a contract deliverable (private contractor costs). Examples of reoccurring costs include salaried positions where the cost will likely be spent equally in each quarter (i.e. 25%).**

**Comment by jeromeleecms** [comment]
Thanks @lauraponce -- just some additional tweaks.. thoughts? 

**Estimated Quarterly Expenditure**

For each quarter, enter the percentage of the total Medicaid FFP cost that will be spent in each category. The auto-calculated dollar values for each quarter should align with the state's quarterly FFP estimates for CMS. As a reminder, In-house costs equals state staff + other state expenses.

Help text:

Input a higher percentage in quarters where there may be non-reoccurring costs and adjust the other quarters downward to ensure the totals do not exceed 100%. Examples of non-reoccurring costs may include a one-time state equipment purchases (in-house costs) or payments on a contract deliverable (private contractor costs). An example of a reoccurring cost may include a salaried positions where the cost is equally divided into each quarter.

**Comment by lauraponce** [comment]
Sold! Looks great 👍

**Comment by jeromeleecms** [comment]
@mgwalker this is ready for Dev implementation. Also, cc: @pphillips-fearless just so you see how we've been spinning up new issues based on Design/Content..

Estimated Quarterly Expenditure

For each quarter, enter the percentage of the total Medicaid FFP cost that will be spent in each category. The auto-calculated dollar values for each quarter should align with the state's quarterly FFP estimates for CMS. As a reminder, In-house costs equals state staff + other state expenses.

Help text:

Input a higher percentage in quarters where there may be non-reoccurring costs and adjust the other quarters downward to ensure the totals do not exceed 100%. Examples of non-reoccurring costs may include a one-time state equipment purchases (in-house costs) or payments on a contract deliverable (private contractor costs). An example of a reoccurring cost may include a salaried positions where the cost is equally divided into each quarter.

**Comment by mgwalker** [comment]
dev issue is #2110
