### ISSUE TITLE
Refine the error message text so that it's clear what the problem is and how to fix it

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#2093]
The error message should be helpful and clear while letting people know what they need to do. 

Step 1. Figure out what use cases there are for errors.
Step 2. Write messaging for letting people know what the error is.

Some examples of current error messages:

![Screen Shot 2020-03-06 at 11 10 43 AM](https://user-images.githubusercontent.com/21222704/76114779-b6394e80-5f9b-11ea-9893-ffcacb1a2913.png)

![Screen Shot 2020-03-06 at 11 11 08 AM](https://user-images.githubusercontent.com/21222704/76114781-b8031200-5f9b-11ea-8f63-56ad6d373a03.png)

![Screen Shot 2020-03-06 at 11 14 44 AM](https://user-images.githubusercontent.com/21222704/76114786-b9343f00-5f9b-11ea-9327-42c42541efd8.png)

Some quotes from round 10 of research to keep in mind:

> “It says last saved at 12:07, then it says some data was not saved. Those two statements seem incongruent to me.”

> “Why would it say “some data is not saved” if saving is not my responsibility?”

> “Out of the range of what? I think you should be more specific than that. Say what you mean.”

> “I think “save failed” feels like a total meltdown failure -- something really bad. Something like a data range was off -- is there less sensitive verbiage that could be used?”

### This task is done when...
 - [ ] There is clear messaging for errors 
 - [ ] Product approves
 - [x] Dev issue has been added

**Comment by lauraponce** [comment]
For an unexpected error to prevent autosave from working, what is the path forward for what users need to do? Should they refresh their browser (while knowing they might lose very recent edits that couldn't get saved) or try something else first? If they are still seeing it, is there a step two/three? @mgwalker @pphillips-fearless 

cc @jeromeleecms

**Comment by mgwalker** [comment]
Once #2088 is in, the only predictable unexpected errors would be related to the user's browser being unable to reach the API, like their internet connection goes down or the server craps out. (We've never seen it crash in production but anything is possible!) They could also have a moment where they try to save while a deployment is happening. There are a couple of scenarios there that could cause momentary failures.

I'm wondering if in the case of the unexpected error, we might show an explicit save button and suggest that the user try again in a few minutes. I would hope most unexpected errors would resolve themselves soonish.

I guess if that doesn't work, having them reload again is the only option. Longer-term, we could have unsaved changes persisted to the browser's local storage so it isn't lost. Then when the APD loaded, we could immediately apply the unsaved changes. That's risky though because if they've made changes in a different browser in the meantime, those could be overwritten by the old changes. 🤔

**Comment by lauraponce** [comment]
Okay got it. Thanks for helping me understand the scenarios, that makes sense.

Since it seems like we need to convey a little bit more information than the one line of text in the skinny error message from testing, I tried to combine the best of both versions while using the alert component from the design system. 

The alert would slide down from the header (pushing down the APD content) and would persist as long as autosave isn't able to save the APD because of one of those edge case errors. 

When the save button is clicked, it'd turn into `Saving` and then would go back to `Save` if it wasn't able to save. If it does successfully save, the alert would disappear, the content would move back up, and the save messaging in the blue header would get updated.

## A

![1](https://user-images.githubusercontent.com/21222704/76652486-e9dc2180-6523-11ea-9c07-45816271092e.png)
____

## B

![2](https://user-images.githubusercontent.com/21222704/76652498-efd20280-6523-11ea-8e72-fc379b8d184f.png)

I'd love to hear any input/feedback on the content of the message and the layout/interaction. @jeromeleecms @mgwalker

**Comment by mgwalker** [comment]
This is only for the unexpected error case, right?

I think the animation + push down can be done with just CSS by toggling a class on and off, so that should be a relatively light dev lift, I think (making some assumptions about already knowing the code, etc.).

**Comment by lauraponce** [comment]
Yes, just for unexpected errors. So hopefully no one would actually end up seeing this. Would an error like this get logged so that we can see how often people are running into a problem?

**Comment by lauraponce** [comment]
**There's been an unexpected error.** 
We weren't able to save your latest changes. Try saving in a few minutes. If you continue to see this message, refresh your browser. New changes may be lost if you continue to make edits before this issue is resolved.

👀 @jeromeleecms?

**Comment by lauraponce** [comment]
How that would look in the UI:

![Screen Shot 2020-03-17 at 10 36 23 AM](https://user-images.githubusercontent.com/21222704/76884595-2b7a0e80-683b-11ea-9a3c-497dc6ad2d7b.png)

**Comment by jeromeleecms** [comment]
Just a slight tweak/thought @lauraponce:

**There's been an unexpected error.**
We weren't able to save your latest changes. Try saving in a few minutes. If you continue to see this message, refresh your browser. New changes may be lost if you continue to make edits or _refresh your browser_ before this issue is resolved.

Also, just summarizing what the expected behavior will be:

1) Unexpected error occurs
2) This alert will push existing content down.
3) User would have the option to select save, which if click will show "Saving" and disappear if successful and update at the top. If it fails, than it will change back to Save and the alert will remain.
4) If a user decides to keep working with the error in place, if the autosave does occur, the alert will slide back up and content will move to it's normal/expected position.

Is that correct?

**Comment by lauraponce** [comment]
Yes, that's correct.

Slight tweak to your tweak?:

We weren't able to save your latest changes. Try saving in a few minutes. If you continue to see this message, refresh your browser. Before this issue is resolved, new changes may be lost if you continue to make edits or if you refresh your browser.

**Comment by jeromeleecms** [comment]
Tweak accepted :)

**Comment by lauraponce** [comment]
@mgwalker this is ready for dev:

Unexpected error message:

![Screen Shot 2020-03-17 at 11 27 01 AM](https://user-images.githubusercontent.com/21222704/76889122-456b1f80-6842-11ea-971c-0ef6abf68d6b.png)

**Comment by mgwalker** [comment]
Dev issue is #2112
