### ISSUE TITLE
Explore options for the best phrasing of the save messaging

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#2094]
There is more than one way to let users know their information has been saved and when that took place. For example, you can say "last saved 30 minutes ago" or "last saved 2/24/2020 12:08 pm." We should look into the different ways to say this and figure out which makes the most sense for eAPD.

### This task is done when...
 - [x] There is a mock-up/ recommendation for how to say the info has been saved
 - [x] Product approves
 - [x] Dev issue has been added

**Comment by lauraponce** [comment]
There are three options for how we could display the last saved messaging. The hybrid version feels like the best option in my opinion:

## Absolute timestamp

`Last saved March 11, 2020`

**Pros**: This would work really well for users when they are wanting to look back at a certain time period in an older version of their APD (and versioning is one of the issues in our backlog for the future).

**Cons**: APD editing usually happens in the short timeframe of a few months so users would have to mentally calculate how long ago it was edited/saved with the absolute timestamp.

## Relative timestamp

`Last saved 22 minutes ago`

**Pros**: This would work well for users when they are actively editing the APD and need to know _quickly_ when the last change was. (It would especially be helpful for them to know if multiple people are editing simultaneously, another future item in our backlog.) 

**Cons**: The more time that passes since the last save, the more distant the relative timestamp becomes which makes it less useful especially when/if states need to refer back to the exact time a change was made.

## Hybrid (absolute + relative)

Less than 24 hours: `Last saved 10:05 am (22 minutes ago)`

More than 24 hours: `Last saved March 10 (1 day ago)`

More than 30 days: `Last saved March 10 (3 months ago)`

More than a year: `Last saved March 10, 2019 (1 year ago)`

**Pros**: Combines the best of both and gives users the most information without relying on their mental calculations for how long ago the edit was.

**Cons**: It will take up a little more space on the page, but there should be enough room for it. It will also likely be more complex for dev to implement (?).

![Screen Shot 2020-03-11 at 9 55 11 AM](https://user-images.githubusercontent.com/21222704/76442621-70ef9500-637e-11ea-94ed-2bab3eee09e4.png)

Questions: Should we use the local time for the state in their timestamp?

@jeromeleecms 💭 ?

Reference link: https://uxmovement.com/content/absolute-vs-relative-timestamps-when-to-use-which/

**Comment by lauraponce** [comment]
Open questions:

Does the minute ticker continue to go up? (similar to how Slack does it)
Do we add in time zone?

**Comment by jeromeleecms** [comment]
@lauraponce - thoughts on this (also open to feedback from the rest of the team as well):

**Short Answer:** 
1) Yes, the minute ticker should go up when the user is inactive (see thinking below)
2) Yes, lets add the time zone relative to the user (maybe an engineering question for level of effort)

**Longer Answer:**
After staring at Slack and Google Drive for about an hour, processing our conversation from Parking lot time, and ALSO looking at #2088 - what do you think about this behavior for the auto save and when to use this messaging (we can also push this to another issue as well depending on the outcome of this):

1) **While user is actively using the application:** System only shows "Saving" and then "Saved." (Google uses "All changes saved to Drive."
2) **When the user is inactive (this ties to a comment I think Sara made):** System then uses this messaging to report when the last save activity was completed.

So the rationale:

1) Since we are now autosaving (and once #2088 goes in), the absolute and relative time becomes less of an issue because the user will receive feedback immediately that a save is occurring with the animated circle -> check mark (i.e. save complete). If we are updating the absolute and relative times and the user is active working in the APD, the absolute time will reflect the current time and the relative time will essentially be 0 seconds (since we are saving in 300 ms increments).

2) The messaging becomes most relevant when the user is idle and/or no change has been made to the APD. Then this messaging will address the concern raised during user testing about when the save last occurred. If a user is idle for > 1 minute, than we can display the save message content as the hybrid format we agreed upon and time can tick up according to your heuristic in your comment above.

**Comment by lauraponce** [comment]
This makes a lot of sense to me! So to make sure I'm following, this is what you're proposing, correct?

**Actively saving**: `↻ Saving`

**Less than 1 minute**: `Saved`

**Less than 24 hours, more than 1 minute since last edit**: `Last saved 10:05 a.m. PDT (1 minute ago)`

(one minute later, no new activity): `Last saved 10:05 a.m. PDT (2 minutes ago)`

**More than 24 hours**: `Last saved March 10 (1 day ago)`

**More than 30 days**: `Last saved March 10 (3 months ago)`

**More than a year**: `Last saved March 10, 2019 (1 year ago)`

**Comment by jeromeleecms** [comment]
Exactly! This will also scale nicely when we start thinking about locking down APDs with electronic submissions too. 

I would also be OK with just putting PT or ET if it's an extra lift to identify the PST/PDT or EST/EDT.

**Comment by lauraponce** [comment]
I'm good with PT/ET too, that seems like one less thing to think about. Assigning this over to @mgwalker for the dev issue.

**Comment by mgwalker** [comment]
Dev issue is #2104!
