### ISSUE TITLE
"Create new APD" button -> 401 Unauthorized response, no UI update

### ISSUE THREAD

**Issue by radavis** [18F/cms-hitech-apd#2146]
### Steps to reproduce

* Login as a user without the ability to create a new APD
* Click the "Create new" button
* UI is stuck at "Loading your APD", 401 unauthorized response in JavaScript console.

Slack thread: https://gsa-tts.slack.com/archives/C8E5EJK9V/p1585667481136400

![Screen Shot 2020-03-31 at 11 46 51 AM](https://user-images.githubusercontent.com/1299034/78053296-63f70d80-734e-11ea-895d-7214d3395488.png)

### This task is done when...
 - [ ] "Create new" button is hidden for users who cannot perform this action
 - [ ] Or, come up with another way to handle this bug.

**Comment by jjames521** [comment]
@lauraponce @beparticular After having thought about this, "Create New" being disabled as suggested might be a better solution, thoughts?  The modal interaction we had talked about I think would be an inferior one as it's just an extra step for the user.

We could have a situation were the user wants to contact the administrator for access privileges though right?

**Comment by beparticular** [comment]
I'm fine with the button being disabled as long as there is something shared that lets them know why the button is disabled. 

@jeromeleecms for Jesse's last question - I'm assuming yes, that it isn't just an internal issue we might encounter, but wanted to double check with you to verify.

**Comment by pphillips-fearless** [comment]
I'mplementation-wise, it's easier to hide the button than to disable it and add an explanation.  It seems like it's less confusing/frustrating to the user as well.

**Comment by beparticular** [comment]
@jeromeleecms 

Addressing 2) This does bring up the question - do we want admins to be able to hide the button in the future? 

Will this be an issue until we have multi-user access? 

What problem are we trying to solve here? Is this a bug or a feature? :)

**Comment by jeromeleecms** [comment]
So.. the way I see it is BOTH! :) 

1) The bug: Users without permission to create an APD should not be able to create a new one. The system should not offer them the option to create a new one and/or if they attempt to manually trigger that request through the API , the system should error them out and redirect them to the appropriate page (in this case, the dashboard) with an error.

2. The function: Based on these permissions: https://github.com/18F/cms-hitech-apd/wiki/Auth-roles-and-activities, we would have to have a broader discussion about how permissions are applied. Does every react component need to have a permission in order to display to the user (something like that)? We wouldn't need Admin to do anything but select the correct user role and their view should be displayed according to that. Long term, this discussion around multi-user access will sort itself out since some people will have the ability to view/not edit (i.e. a Federal user should not be able to edit a state submission).

**Comment by beparticular** [comment]
Haha! 
Ok, so, I think based on this, we're saying it's ok for the button to not be there, and the user who doesn't have the button doesn't need to know that there could be a button there. 

If that's true, let's just hide the button if they don't have the permission.

**Comment by jjames521** [comment]
@beparticular @pphillips-fearless 

I've spun off the feature section of this ticket to #2196 and maintained the bug portion of this.

**Comment by pphillips-fearless** [comment]
The new dev issue is #2198
