### ISSUE TITLE
Plan, conduct, and synthesize round 11.5 (tables) of user research

### ISSUE THREAD

**Issue by beparticular** [18F/cms-hitech-apd#2164]
High Level Goal of Round 11.5 (Tables) 
Do users understand how their numbers make it into the tables, and do our labels and calculations provide the right information that they need to plan their projects? 

Research Plan (in progress)
https://docs.google.com/document/d/1pjYS9B4Pa40IP1SiflP2RP8AzJq_zm14lkhLZyD16ag/edit#heading=h.m956192bfsk6

Potential dates for testing: Week of May 4

### This task is done when...

- [x] We have a research plan and protocol
- [x] We have the designs/prototype to be tested
- [x] Participants are recruited and sessions are scheduled
- [x] Sessions have been conducted
- [x] Results have been synthesized/analyzed
- [x] Findings have been shared and discussed with the team  
- [x] Next steps are identified and new issues have been created
- [x] Findings have been added to the wiki

**Comment by CSwartzHMA** [comment]
Draft outreach language has been reviewed and approved by the team. A Google form has been created to capture availability from volunteers. The email distribution list which includes previous testers was updated to include volunteers from the February 2020 sessions. This list was used for this round of outreach, rather than the All-States distribution list. Will watch for responses and schedule sessions.

**Comment by CSwartzHMA** [comment]
Sessions are scheduled with 4 states.

**Comment by beparticular** [comment]
Protocol in progress: 
https://docs.google.com/document/d/1FJ3KMCAI5v-QJmsDilngH2yOFh4T4KMeD9WfFExRxw4/edit#heading=h.9cel3dv2sp4c
