### ISSUE TITLE
Review Alternative Consideration's help content to assess the level of clarify around risk assessment

### ISSUE THREAD

**Issue by nicholeweems** [18F/cms-hitech-apd#2171]
As noted in #2168, it could be helpful to have states consider potential risks of their planned activities. As an enabler, review of the current help text will inform the team if 2168 should be added to the roadmap as the long-term solution and the more immediate mitigation path may include updating 'Statement of alternative considerations and supporting justification' help text.

### This task is done when...
 - [x] 'Statement of alternative considerations and supporting justification' help text has been reviewed 
 - [ ] A suggestion to modify existing content is made to add context regarding assessing risks or confirmation that the existing text provides the proper level of clarity around risk assessment

**Comment by CSwartzHMA** [comment]
Current help text does not address risk specifically, but rather it asks for a description of alternative considerations and supporting justification made before selecting implementation strategy. The following is a suggestion for rewording to highlight this aspect.
**Header:** Statement of alternative considerations and supporting justification
**Description:** _Provide a description of the analysis of possible alternatives conducted before selecting the final approach, including any risks identified with the selected implementation strategy.  Verify that the selected approach supports an efficiently and effectively administered program._
**Help Text:** If substantive changes have not been made, include a statement of alternative considerations from the previous version of the IAPD.

**Comment by nicholeweems** [comment]
@jeromeleecms, ready for review

**Comment by jeromeleecms** [comment]
@CSwartzHMA Looking at the existing help text + your suggestions, def. needs to be updated, so I expanded this a "bit" - would appreciate some feedback too:

Header: Statement of alternative considerations and supporting justification

Description: Provide a brief description of each alternative considered for the implementation of this activity. The description should include considerations for costs/benefits/risks for each option. Indicate which option was finally selected and why the final selection was made. As applicable, include how the selected approach supports the economic and efficient management of the Medicaid program. 

If this is a previously approved activity, only use this section to discuss alternative considerations made for substantive changes / decisions made during the implementation of the project. Do NOT include the alternative analysis conducted when justifying the original activity.

Help Text: 

Example: Explain and justify the decision to build a custom software solution instead of using a COTS or SaaS option.

Example: Explain and justify the decision to conduct a contract modification instead of doing a fully competitive procurement.

**Comment by CSwartzHMA** [comment]
@jeromeleecms I really like these edits and the fact that the Help Text is now examples, rather than additional instructions, which flow better as part of the description. I say we go with this!

**Comment by jeromeleecms** [comment]
@pphillips-fearless Ready for a dev task!

**Comment by pphillips-fearless** [comment]
this is dev issue #2185
