### ISSUE TITLE
Review Key Personnel and Program Management page for flow of instructions and help text

### ISSUE THREAD

**Issue by CSwartzHMA** [18F/cms-hitech-apd#2250]
During content review we decided a deeper dive into this page was needed to determine whether information is in the right area of the page.

### This task is done when...
- [x] We have an understanding of why things are the way they are on this page, what is regulation, what can be removed. 
- [x] Additional acceptance criteria is listed here 
- [x] A mockup of an updated page is created
 - [x] Team has approved changes
 
![Screen Shot 2020-06-02 at 10.16.20 AM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/cd499790-9e4e-46e1-bcdb-1ab54077bfb2)

**Comment by CSwartzHMA** [comment]
Consider #1558 in this update.

**Comment by CSwartzHMA** [comment]
@beparticular - Do we need a conversation for this one to determine decisions and next steps?

**Comment by beparticular** [comment]
From our discussion in design sync - 

This help text is here because - 90/10 rule was confusing to states, were including folks who were not part of the project, don’t need to put the medicaid director for instance. 

For changing the text, we talked about this in design sync. @CSwartzHMA please let me know if these are good options or if you'd like to write anything else up. Once I have your ok, I'll re-do the mock up and send over to dev. 

Points 1.2.3. Need to be outside the blue box. Use the “Instruction details” styling

1. Text Remains the same
2. Can remove second sentence
3. “Key personnel costs are included in Activity 1, Program Administration, at the 90/10 split.” was the proposed text. 

In th eBlue box - show an example - We would need this to be created. 

Verify against styling in OKRs section?

**Comment by CSwartzHMA** [comment]
@beparticular I agree with points 1-3 and that the style from the OKR section should be consistently applied here and don't have any additions at this time. I would like to see how this looks in a mockup.
As an example for the blue box, consider "Example: HIT Directors who will oversee all activities described in this APD would be included here. State Medicaid Directors who are not proving direct oversight should not be included in this section. "

**Comment by beparticular** [comment]
@CSwartzHMA how does this look? 

![Screen Shot 2020-06-18 at 3 25 17 PM](https://user-images.githubusercontent.com/5957354/85063293-ed60f380-b177-11ea-9203-f8896f495437.png)

**Comment by CSwartzHMA** [comment]
This is much more clear to me. Two thoughts:
1 - Do we even need the example anymore? It is fine as written, if we agree that it is helpful.
2 - Suggestion for rewording #2 - Personnel whose responsibilities apply only to specific activities should be included within Program Activities, rather than in this section.

**Comment by beparticular** [comment]
@CSwartzHMA I was wondering about the example. I think it could be useful to show an example of someone who might be in the activities, rather than the Medicaid Director since we'll have just asked for that?

Agree on 2. I can update that in the mockup. 

Let me know about the example.

**Comment by CSwartzHMA** [comment]
@beparticular I agree. How is this example, as a starting point?

Example: Program Managers and Directors who provide oversight to all projects would be included here. Personnel who support individual activities, even if they support more than one activity,should be included within the State Cost Categories section for each associated activity.

Too lengthy?

**Comment by beparticular** [comment]
@CSwartzHMA how about this? 

Example: Program Managers and Directors who provide oversight to all projects would be included here. Personnel who support individual activities should be included in the State Cost Categories section for each associated activity or activities.

**Comment by CSwartzHMA** [comment]
@beparticular This looks great. It is clear and concise.

**Comment by beparticular** [comment]
@pphillips-fearless this is ready for dev. 

Change log:
- Moved help text starting "Personnel listed in this section..." to below the "Primary APD Point of Contact" header inside the "edit" area (or when adding a new person) on Key Personnel section
- Changed the text on all bullet points within the ordered list and moved it out of the blue example box
- Changed the text within the example box to be an example

Here's the new text for copying and pasting. Any other text already exists and just needs to be moved. 
1. Key personnel are individuals involved with all activities within this APD, or are directly involved with governance, coordination, stakeholder decision-making, oversight, and/or performance of the activities as they affect the state’s Medicaid program.

2. Personnel whose responsibilities apply only to specific activities should be included within Program Activities, rather than in this section.

3. Key personnel costs are included in Activity 1, Program Administration, at the 90/10 split.

Example: Program Managers and Directors who provide oversight to all projects would be included here. Personnel who support individual activities should be included in the State Cost Categories section for each associated activity or activities.

![Screen Shot 2020-06-30 at 1 22 09 PM](https://user-images.githubusercontent.com/5957354/86156979-b7efca80-bad4-11ea-8a90-9e2cfdbe5338.png)

Let me know if you have any questions!

**Comment by pphillips-fearless** [comment]
This is new dev task #2325
