### ISSUE TITLE
Update Activity Schedule Summary for better user understanding

### ISSUE THREAD

**Issue by CSwartzHMA** [18F/cms-hitech-apd#2253]
Question from content review: What do states need to be able to use this page?  Use Case: Where a state is using this a PM tool, the dates should be more descriptive. Dates of activities should bookend milestone dates. 

### This task is done when...
 - [ ] Make sure that folks can meet the use case of knowing that the milestone dates on this page should fall within the Activity Dates
 - [ ] Make sure that folks understand what all of these dates are (are they end dates, a range, etc)
 - [ ] Makes sure that folks understand they are looking at Milestones
 - [ ] Make sure we do this through the table vs through the content 
 - [ ] Changes have been agreed upon and documented 
 
Use Case: Where a state is using this a Project Management tool, the dates should be more descriptive. Dates of activities should bookend milestone dates. What should states do with ongoing activities, such as open ended, or auto-renewing vendor contracts or onboarding efforts?

**Comment by CSwartzHMA** [comment]
@jeromeleecms @beparticular 
For the display of dates on this page, do you agree that we should include start and end date for Activities and the target completion date for milestones, with labels for each?
Also, @jeromeleecms - what are your thoughts on open ended/ongoing activities and/or milestones? Should we instruct users to enter end of funding request and update annually?

**Comment by jjames521** [comment]
@beparticular 

I broke this out into two tables as there is a need to call out specific ranges and target completion dates with their own headers.  I figured this would be a cleaner and clearer solution than trying to have everything on one table.  The call outs for Activity Date Range and then dialing down into a target Completion Date for each milestone on the second table.

![ActivityScheduleSummary.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/482bcdcc-e189-4374-9f94-9c2d4db0f44c)

**Comment by jeromeleecms** [comment]
@CSwartzHMA I don't know how I missed your comment in this issue! Did you all think through a little more about use cases for open-ended/ongoing milestones?

The only one that comes to mind at this point is program/project admin related work. In that context, couple use cases:

1) End Date for Admin for the HITECH program could be the end date of the entire program. 
2) End Date for admin related to specific project, can tie to the end date of the project (i.e. complete registry). At that point, M&O would need to be done under a separate request anyway.

Were there other cases where this might apply?

**Comment by beparticular** [comment]
From Design Sync - 

We discussed that use case is seeing milestones by activity vs across the APD.

Design changes from the proposed above - 
- Try breaking this out more by activity, rather than a table of aggregated activities. The info across activities isn’t dependent. Consider condensing within the activity, but condensing across activities is not as important.

- Try an accordion style for each activity so folks can open it when they need to see the summary of milestones per activity. 

- Explore what would the export view look like? - All expanded.

**Comment by jjames521** [comment]
@beparticular 

Here are the new changes to the design layouts for Export, Print Format and Builder View.  

I was able to condense the tables into an accordion style interaction.  We would need the italic text and bolds to define the hierarchy, but it works in my opinion and would be extremely compact given a ton of activities added.

I have another variant where I've broken it down into separate tables as well to show how that would look. This variant showcases a summary of activity date ranges with a more comprehensive table breakdown.  I was thinking another option would be to get rid of the summary all together and combine both variant 1 & 2.  The change is shown in variant 3.

In all variants for the most part the export and print views are the same in my mind.

**Builder**

![ActivityScheduleSummaryVarAccordion.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/e56357a8-0f17-4d19-aa46-6a34102ff4f0)


**Print**
![ActivityScheduleSummaryPrintExport.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/e5fffc41-464d-47e7-95c4-cb86bb6b190d)


**Export**

![ActivityScheduleSummaryVarAccordionExport1.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/c67b27de-882f-458c-8c25-42487a97a1eb)

**Variant 2**

![SummaryActivityScheduleSummaryMilestoneTableVer.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/82cb1370-9d9f-4b70-8c01-dca1068b22b3)

**Variant 3**

![ActivityScheduleSummaryVar3Accordion.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/d6cca95e-dc9c-43df-8d3d-993ce9bf4f46)

**Comment by jeromeleecms** [comment]
Per discussion on #2170, the title for this one table should be "Summary Schedule by Activity" -- this will ensure consistency with the  table headers.

**Comment by jjames521** [comment]
@beparticular @pphillips-fearless 

After our design sync discussion, a follow up summary

Decided that variant 2 would be the best to go with this can be seen above but with the top title changed to Summary Schedule by Activity to maintain consistency within the app.  The print and export/executive summary views are below.

**Builder**
![SummaryActivityScheduleSummaryMilestoneTableVar2.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/ca7dde7a-bde5-41de-a442-06584331df80)

**Export**
![ActivityScheduleSummaryVar2AccordionExport1.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/bc8a1b90-b67e-471f-8033-a3c06733d0a1)

**Print**
![ActivityScheduleSummaryPrintExportvar2.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/fcef0820-6d51-4397-b581-c97862452f3a)

This would break the table into two separate tables with summary on top and a dial down by activity on the bottom.

The arrows you see on the bottom section is for an accordion interaction.  The user upon seeing this table for the first time would have the first activity opened up to invite the user and let them realize how that interaction would work.  On navigation out from the page if any activities are opened it would be nice to keep those tabs open if possible for quick nav out and nav back to the table for reference.  If this isn't possible defaulting to the activity 1 open could suffice.

For the style of the tables we can keep consistent with the current styling as we still haven't deployed the new styles.  The hierarchy would work the same as was done with the Summary Budget by Activity table.

**Comment by beparticular** [comment]
For the nav @pphillips-fearless what's the lift for doing the accordion the way @jjames521 described? 

(For general priority, this is a do it when we can, but not necessarily a priority to finish before release if we have other work.)

**Comment by pphillips-fearless** [comment]
I just took a look at the design system site and don't see an accordion control.  It does look like the vertical navigation control could be used (because the vertical nav item control types can be specified, we could specify a table as the nav item).  This would need to be tested as it's probably not a typical use case for that control.  If it doesn't work (or is undesirable because of styling limitations) we'd need to pick out another control.  Overall the task is a medium because it breaks a single table into two, so adding the accordion control might make it a large.

**Comment by jjames521** [comment]
I spoke with Bernard from the design system team and he provided this insight. @beparticular @pphillips-fearless 

"There’s been talk in the past of providing an implementation and design for a accordion component, but we haven’t gotten the chance to prioritize that yet. When that is implemented, we will likely borrow from USWDS’s example, and consult existing implementations in medicare.gov or healthcare.gov
designsystem.digital.govdesignsystem.digital.gov
Accordion | U.S. Web Design System (USWDS)
An accordion is a list of headers that hide or reveal additional content when selected."

**Comment by beparticular** [comment]
cc @jeromeleecms 

Per conversations in 1:1s/syncs etc - 

1) We'll move forward on this ticket without the accordion style for now since it would be custom-ish and not in the cms design system. (If we did use it, the USWDS system is a good place to pull from.) 
2) We'll put this page on the roadmap for use case feedback and usability testing. If the accordion style is needed, we can consider it then. 
3) We'll table the accordion style as an option to discuss and potentially use for the app where needed/if needed in the app as a whole. (I'll put a note in the forthcoming UX Strategy doc)

@pphillips-fearless I will have @jjames521 update the mockup and remove the accordion info from 
https://github.com/18F/cms-hitech-apd/issues/2253#issuecomment-648285644 and that will be the source of truth summary for this issue. 

And then I believe it will be ready to go.

**Comment by jjames521** [comment]
@beparticular all set with the updated https://github.com/18F/cms-hitech-apd/issues/2253#issuecomment-648285644

**Comment by pphillips-fearless** [comment]
the new dev issue is #2318
