### ISSUE TITLE
Identify Security POC for CMS and 18F

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#345]
We need to have a point of contact for our ISSO to interact with, and can help construct the SSP. This should have a CMS and 18F person identified.

### This task is done when...
 - [x] CMS business owner is identified
 - [x] 18F POC is identified

**Comment by NAretakis** [comment]
I'll nominate myself for CMS person. @jeromeleecms for any objections.

**Comment by jeromeleecms** [comment]
@NAretakis I have no objections. Divide and conquer!

**Comment by NAretakis** [comment]
Check! Up next is the lucky 18F'er that gets to join the fun, right @nkkl ?

**Comment by nkkl** [comment]
I'm working on it!

**Comment by nkkl** [comment]
I've got a POC from 18F who will support our team! 🎉 

I need to do a little bit of internal stuff to make sure it's documented properly and all of that, but that shouldn't take much time. Our person is a little busy through the next week, but I'll try to get him into our Slack channel sooner rather than later.
