### ISSUE TITLE
Wireframe v1 of the budget section for the state submission

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#404]
### This task is done when...
 - [x] wireframe has been designed
 - [x] wireframe has been shared with the team

**Comment by lauraponce** [comment]
![screen shot 2018-04-23 at 9 16 05 am](https://user-images.githubusercontent.com/21222704/39128896-0479e10c-46d7-11e8-87e7-1a430871240b.png)

**Comment by jeromeleecms** [comment]
@lauraponce This is for the final summary proposed budget section, right? I like the feel of this -- some initial thoughts:

1) What would this look like if we had 50% or 75% FFP match (MMIS may have this now) + it would be helpful for scaling this concept if we took this to MMIS/E&E in the future and not have to rework budget tables in a future iteration of the product. For the MVP, most MMIS requests will be 90%, so if time is an issue, open to tabling this.

2) If you scroll/hover all the way to the right, would there be a total column (i.e. the totals from FFY 2017+FFY 2018 in this example)? Could the FFYs in the "Two-Year Budget"  be clickable and it would move to that section of the table instead of relying on a hover behavior (thinking from a 508 standpoint, would this be compliant or could we replicate that hover with a right/left arrow on the keyboard)? Alternatively, could the initial view of this table be just the total computable for the FFYs + the total of all FFY columns and when you click on the table header, it would expand the FFY to show the Federal and State share? Not sure what makes sense quite yet, but just throwing that out there as food for thought.

3) Small thing - Two-year budget should read FFY 2017 - FFY 2018 (for coherency in the wireframe)

4) Instead of the HIT administrative budget, would this be the sum of all HIT activities? If a user selects HIT/HIE/MMIS in the activities listing at the beginning of the app, how would that translate into this table? Maybe this is less of a design issue as opposed to understanding how the business/logic components of the app trickle down.

Happy to talk through this more, if needed!

**Comment by lauraponce** [comment]
Here is an updated version based on our conversation! The changes in v2 are:

1. For the v2 of the table, if you were to hover over the second cell in FFY 2017, it would pop out like that with the info icon to expand with the additional info. 
2. Added asterisk in title text to indicate it's 90/10
3. Added viewing selection at the top to select which sections they want to see, if they only selected two, one of them would collapse
4. Added scroll bar to see what that would look like 
5. Added color to indicate groupings
6. Added way to collapse and expand rows
7. Added shadows to make it more obvious that the left column would lock in place

Let me know if I missed anything that we talked about. Feedback/thoughts on this iteration @jeromeleecms @NAretakis?

**Comment by lauraponce** [comment]
V2
<img width="740" alt="screen shot 2018-04-25 at 12 09 30 am" src="https://user-images.githubusercontent.com/21222704/39225942-4e6fbad8-481d-11e8-97a2-fe336f413ae4.png">

**Comment by jeromeleecms** [comment]
I like the changes. I know you haven't mocked this up yet, but for hovering over the cell, were you thinking that would display the 75% and 50% FFP? In that case, it would probably be better to place a "+" next to the line item's column header, i.e Project State Staff (+), since the different FFP would affect the entire line item. Clicking the plus would show the different rates (Total, Federal and State share) for the entire row.

For this image, is this how would imagine it being on screen or the scroll bar would let you move between FFY 2017 -> Two Year Total as a scroll and this image is just a big picture of the entire budget table?

Also, something for consideration -- for the MVP when displaying this for the user, if there are no costs tied to an area (i.e. MMIS, HIE) should we hide that category (or maybe default it to collapsed) ? Could potentially reduce noise for the user.

**Comment by lauraponce** [comment]
That makes sense about moving the + to the column header instead of on an individual cell basis since it affects the whole row. I'll update that!

And yes, to your second note, this is just a zoomed out version of everything, but only part of this would fit on the screen and they would scroll to see more. By default, I picture all 3 sections being selected to view, but if someone just wants to see the two year total, they can uncheck the other two to jump to that one. Does that match what you would expect?

Agreed about the third point that we can definitely hide MMIS/HIE for the MVP if they aren't relevant to reduce the noise.

**Comment by NAretakis** [comment]
v2 looks fantastic! Point of clarification, for MVP, we'll still need the MMIS and HIE sections, but they should only show up if an MMIS or HIE activity was specified within the Activity List section.

**Comment by jeromeleecms** [comment]
@lauraponce I think the budget table should show the entire funding request and clicking on the hyperlink would jump them to the applicable FFY in the scroll area. Effectively, it would do the same thing as hiding it, but the user could still scroll within the window to see the different FFYs and maybe(?) save a few button clicks from having to redisplay the information by reselecting it. Any best practice surrounding this?

@NAretakis Were you thinking the dropdown would only show the allowable FFP match? I.e. if HITECH, 90/10 is set, if MMIS, then the rest of the options are unlocked?

**Comment by lauraponce** [comment]
V3 ![screen shot 2018-04-26 at 2 59 42 pm](https://user-images.githubusercontent.com/21222704/39326295-7fc51c9a-4962-11e8-9b0b-7abfe98a2713.png)

**Comment by lauraponce** [comment]
This would be if they hovered over project state staff and selected the right arrow to view the other levels

**Comment by lauraponce** [comment]
cc @jeromeleecms @NAretakis

**Comment by jeromeleecms** [comment]
@lauraponce Looks good! Last few thoughts (hopefully)

1) Hover behavior: How does that work with 508 compliance? Is just tabbing over the row header arrow and it would show the expanded view?

2) For consideration: Hover vs. clicking and keeping the expanded section open. Thoughts?

2) For consideration: For the hover behavior, can the top row be the total, followed by the various FFP rates (here's my crude rendition): 

![image](https://user-images.githubusercontent.com/34279968/39329812-6839d54c-4954-11e8-8c0b-ae7df2fe3ce6.png)

I do like the look of the circles, so the rectangles I drew was just for a visual reference.  Also I'm wondering if we should list the % for each cell, or will there be an assumption that if the FFP is listed at 75%, then the remainder should be 25%.

**Comment by lauraponce** [comment]
@jeromeleecms thanks for the quick feedback! :)

1. For the hover behavior, if you hover over any cell on the left column, it would pop out to show there are additional actions (i.e. the right arrow would appear) –– then you can click the arrow and the stuff on the right would show up. Does that make sense? 

3. For the top row to be total, do you mean the subtotal HIT or which number goes in the top?

I like the idea of having the percentage by each one so it's clearer, I can plug that in and will post the update!

One other thought is that I think I should add some shadowing over the other sections when the percentages are popped out so it doesn't look like they apply to the items on the left.

**Comment by jeromeleecms** [comment]
@lauraponce 

1) As long as you can do it with a keyboard/voice/meets compliance, I'm good :)
2) I'm thinking that when you hover, the row's total would be the same, but underneath would show the various FFP rates.

For example in the Federal State Share column when you hover:
A) Project State Staff: $100 <-- this would be the overall total for the Federal Share column and what would be displayed normally without hovering
B) 90%: $65 (part of the pop-up)
C) 75%: $35 (part of the pop-up)

**Comment by lauraponce** [comment]
@jeromeleecms 1. Love that you're already one step ahead thinking about this! I'll make sure to check in with @brendansudol when he's building it out to make sure it's tab-able to get it to pop out, good call out.

2. So in your example is the default state the 90/10 values and then when you click into it, it would show the 75/25 and 50/50? Or is the default state the 100%? I don't think I'm fully understanding. 

Is it this?
A) 100% default
B) 90% (only shows in the pop-up)
C) 75% (only shows in pop-up)
D) 50% (only shows in pop-up)

or this?
A) 90% default (or it could be 75% or 50% depending on the activity)
C) 75% (only shows in pop-up)
D) 50% (only shows in pop-up)

or something else?

**Comment by jeromeleecms** [comment]
@lauraponce 

So just to make sure we lay out both use cases:

1) One level of Federal Match. For HITECH it's 90%. Then no pop-up.
2) Multiple levels of Federal Match. Then pop-up with this model:

A) 100% default
B) 90% (only shows in pop-up)
C) 75% (only shows in pop-up)
D) 50% (only shows in pop-up)

That way its clear how the totals for 100% were calculated.

Does that make sense?

**Comment by lauraponce** [comment]
Is this what you mean, @jeromeleecms? (By the way, my math for the percentages doesn't add up, it's just random numbers).

![screen shot 2018-04-27 at 10 57 46 am](https://user-images.githubusercontent.com/21222704/39369299-e3ce446c-4a09-11e8-898c-670479d083a7.png)

**Comment by jeromeleecms** [comment]
@lauraponce Almost -- here's one with the sample math filled in:

![image](https://user-images.githubusercontent.com/34279968/39371162-b9fbbc6e-49f5-11e8-8435-50f2e2b46f7c.png)

The change is that the top row should be a sum of the lower rows. I removed the 100% since it would be misleading (since we are not matching at 100% FFP). Maybe including something that shows that it's the total?

I'd also be curious to see in testing if people want the pop-up or if they want the item to persist and push the other rows down.

**Comment by lauraponce** [comment]
Yeah, we will definitely want to test this to see if it's something users want to persist on the page or not, great point! It will be helpful to understand when they would want to see this information and how it will be used so that we can make sure it meets their needs.
