### ISSUE TITLE
[Certify and Submit] Design frontend for certify and submit section

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#471]
Need to have a certify and submit section that completes the APD creation and submission process.

### This task is done when...
 - [x] Wireframe for certify and submit section is constructed
 - [x] Design hands task off to Development.

**Comment by NAretakis** [comment]
Lightweight. Envisioned to have a checkbox, or maybe one of those _type your name_ to certify the submission as complete.

It also needs a bit of language letting the users know that after submitting, the APD will be locked for editing until CMS responds. Then maybe a big green submit button. 

Big green button is what should trigger the versioning thingy that @mgwalker has been working on.

**Comment by quarterback** [comment]
Working on this week.

**Comment by quarterback** [comment]
I've sent up a PR address this and #611. What I'll need is for @mgwalker / @brendansudol to convert the check boxes in assurances and compliance from text to actual check box options since I couldn't do that in the yaml file. (I just did them as text so you'd know what should be in that space.) Also write the copy headers for those sections. Will address submit/certify in that one.
