### ISSUE TITLE
Design HIE activities section

### ISSUE THREAD

**Issue by quarterback** [18F/cms-hitech-apd#497]
Design the sections of HIE specific content after the walkthrough of HIE is done. Related to issue #473 

### This task is done when...
 - [x] Write content for each of the HIE sections.
- [x] Write activity specific content
- [x] Create a related issue on design of these sections once content is implemented in prototype to decide whether it can exist as-is or needs more design refinement.

**Comment by NAretakis** [comment]
@quarterback so, Jerome and I talked this through and I think we have a good, low LOE, approach for getting this coded. Basically, what we'd like to do is use the "HIE Checkbox" 
![image](https://user-images.githubusercontent.com/34281281/40516906-0d204740-5f70-11e8-974d-5b7a80e3d2ec.png)

to drive a special rich text box that appears within the Activity Description section of the corresponding activity.

How this would work is that when a user checks the "HIE" box, a special chunk of helptext appears for "Detailed Activity Description" section. And this special helptext addresses [these HIE questions (link to MU, Value Proposition, & Sustainability)](https://app.mural.co/t/gsa6/m/gsa6/1524714012930/d34a6666c3cb4db8dfee9cfadc5e4c13e7a88f72?wid=0-1524756276698)

![image](https://user-images.githubusercontent.com/34281281/40516978-5b83111a-5f70-11e8-9ca2-45453e54cfa6.png)

The special helptext only needs to appear when the "HIE" checkbox is used, otherwise, the default description is just fine. Does this make sense?

**Comment by quarterback** [comment]
@NAretakis @jeromeleecms yes, this makes sense!

**Comment by quarterback** [comment]
I created a dev issue #607

**Comment by quarterback** [comment]
(HIE specific text above HIE detailed activity section)

**Detailed Activity Description** (section title)
(help text draft)
If you list HIE activities below, describe the activity in detail to include links to meaningful use, value proposition to providers, and a sustainability plan. Additionally, include diagrams as needed if they provide more context for how you'll complete the activity outlined.

_What I need here, is for @NAretakis to take a look and make sense of this from an analyst perspective, then I'd be able to refine it more clearly. Do we need more detail than above?_

**Comment by quarterback** [comment]
I need to talk to @brendansudol @NAretakis about this particular issue, so we can get the check boxes added.

**Comment by quarterback** [comment]
@brendansudol @mgwalker we need a section for HIE activities. Rather than do a "toggle", the idea is just to add this as another subsection under activity list. 

<img width="951" alt="screenshot 2018-06-08 12 41 21" src="https://user-images.githubusercontent.com/4461062/41170197-47ce490a-6b19-11e8-830e-77d014f543a7.png">
