### ISSUE TITLE
Wireframe incentive payments table

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#503]
### This task is done when...
 - [x] The table had been wireframed
 - [x] Design concept has been shared with the team

**Comment by lauraponce** [comment]
V1 of the incentive table. The numbers are inputted so that we can see how the formatting would work, but users would be entering these in themselves and the totaling would happen automatically.
![screen shot 2018-05-08 at 10 53 16 am](https://user-images.githubusercontent.com/21222704/39764572-e95d606e-52ad-11e8-8962-dbef7f8f9cba.png)


V1 of editing one of the cells in the table
![screen shot 2018-05-08 at 10 53 05 am](https://user-images.githubusercontent.com/21222704/39764563-e42d34ca-52ad-11e8-911b-a5cc01b9c004.png)

@NAretakis @jeromeleecms

**Comment by jeromeleecms** [comment]
@lauraponce Looks good to me. Mirrors the sample table very well -- does this issue also cover the quarterly breakdown of the incentive payments intended for the proposed budget section? I was scanning the issues and didn't see a separate one for that content.

Maybe one item for Nick and I to noodle through -- next comment for legibility.

**Comment by jeromeleecms** [comment]
@NAretakis Thinking about consistency + decision making here. 

**Consistency**: Our compendium guide have different versions of the tables which shows one with the # of payments vs. just the total. Do we want to enforce that states provide some estimates... which would lead to...

**Decision Making**: Would we want to have the system calculate whether the estimated request is "reasonable?" Since we are past AIU (logic might be easier), would it make sense for the system to do a rough estimate for the range of what the State's would put in here? For example, if the state's estimated 10 payments for an EP, the system could ballpark that the cost should not exceed $X dollars (... or may be not for the MVP?). The reviewers would still need to assess it at some point anyway.

**Comment by lauraponce** [comment]
Here is a V2 based on our conversation: 

![screen shot 2018-05-10 at 12 10 54 pm](https://user-images.githubusercontent.com/21222704/39880250-370c8d50-544b-11e8-8aa1-5bb23319df2d.png)
