### ISSUE TITLE
Where to store external documents

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#522]
As part of the App experience, the user may have to attach documents to their submissions. We need to decide how/where the documents will be stored.

### This task is done when...
 - [ ] Decision made on where the attached documents will be stored
 - [ ] Decision has been documented in the Wiki

**Comment by NAretakis** [comment]
Will update this issue with information from the CMS AWS team on file storage.

**Comment by mgwalker** [comment]
Pending a decision on storage, we have some options:

1. We can assume that we'll be storing files in S3 and start building towards that.  We can use a tool like [localstack](https://github.com/localstack/localstack) for dev and testing, but we'll run into problems uploading in staging until we actually have S3 access.  Lowish risk, since S3 seems likely, but if we end up using something other than S3, all this work goes down the tube.

2. We can use a storage abstraction library (something like [abstract-blob-store](https://github.com/maxogden/abstract-blob-store) and its plugins with a big of a configurator on top would work well) to let us quickly switch out where we store files - we could just throw them away for now and easily switch to S3 in staging later with just a config change and restart.  Also lowish risk, since we should be able to adapt to whatever storage mechanism we're given, but we may end up having to take on some of the development/maintenance of the abstraction plugins.

I lean towards the second option personally, but I'm a proponent of reasonable abstraction layers - they keep us from being too tightly tied to any particular service (just like we should be able to switch out our database to MySQL or something else, we could also switch from S3 to another storage system).

**Comment by NAretakis** [comment]
Quick convo with folks, S3 is definitely an option available to us as is NFS. We can dig in more on Thursday, but does this help point you to option 1 or 2?

**Comment by NAretakis** [comment]
OBSOLETE
