### ISSUE TITLE
Connect with the design lab for visual refinements

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#573]
Reach out to the design lab for help with polishing the design

### This task is done when...
 - [x] Issue has been created
 - [x] Visual designer has been assigned
 - [x] Designer has made recommendations
 - [x] Recommendations have been shared with the team
 - [ ] Design lab issue has been closed

**Comment by lauraponce** [comment]
Issue has been created! https://github.com/18F/design-lab/issues/12

**Comment by lauraponce** [comment]
I'm super excited to share the screens that Aviva worked on for the visual style refinements of the app! 

The main changes to call out are:

- The new color palette
- Wider nav bar
- Extra whitespace on both sides of the main content area
- Shifting from everything on one long page to separating by sections
- And other updates like consistent fonts, spacing, etc.


![cms-design_program-overview_1](https://user-images.githubusercontent.com/21222704/41066691-929482ac-6997-11e8-997e-d25f075b2fe8.png)


![cms-design_program-overview_2](https://user-images.githubusercontent.com/21222704/41066747-d9dc87fe-6997-11e8-9fc6-b8bb32707378.png)

**Comment by lauraponce** [comment]
@NAretakis @jeromeleecms what do you think? 

@mgwalker @brendansudol does this seem manageable from a dev perspective (e.g. not too much throw away and start over work)? 

@quarterback @nkkl other thoughts?

**Comment by NAretakis** [comment]
These look great. I am on-board with everything except maybe the individual sections. I know our original pivot had us move from separate screens to a single long form. And now that I think about it, this is a bit of a hybrid where we're not doing individual screens for each box, but rather individual screens for each major section (Overview, Previous Activities, Program Activities, Proposed Budget, etc.). 

Maybe we start with all the other recommendations, except keep it in the long form for now? However, I could be convinced on some sort of multi-page hybrid.

**Comment by jeromeleecms** [comment]
These look really nice and clean. Is the contract between the white and aqua color at least 4.5 (thanks @nkkl)? Drop shadows in the boxes are a nice touch to help make the sections standout more. 

Other thoughts: 

- I don't know if the top left title content is going to remain as "2018 HITECH APD" (since it looks like there was great care making sure the title lined up with the state height!). We had some discussions on tracking versions based on feedback in our user testings... so it might become:

> HITECH APD
> Original Submission: October 10, 2018
> Version; 1.0

- I was always partial to breaking up the content into manageable components, so I can get on board with this concept (but I would want to set up some A/B testing since the long form seemed to get some really positive feedback once we pivoted this way). Also, if we break up the components into smaller sections, do we treat each activity as its own set of "screens" or is the thought to lump all the program activities in one long screen? 

- Not specifically related to this design, but if the user has 2-3 pages of text to enter into the text box, is the plan for the boxes to grow with the text (or add scroll bars as it is now). Breaking it into "modules" might allow the user an easier view of the entire content for the page as well.

**Comment by mgwalker** [comment]
My instinct is this is doable from a dev perspective - looks like it'd primarily be style changes, which shouldn't be too bad.  But @brendansudol has implemented all the styling so I'd be interested in his thoughts.

**Comment by nkkl** [comment]
Good news, Jerome – it's 4.69:1! Not that I doubted Aviva.

![image](https://user-images.githubusercontent.com/766654/41111946-5742f06c-6a32-11e8-8929-8d34ad8a2c3a.png)

**Comment by nkkl** [comment]
Although the teal on the grey background is not quite 4.5:1, it has sufficient contrast for large text (the large text ratio is 3:1, for text that is 14pt or larger).

**Comment by lauraponce** [comment]
I know we received feedback early on about the single page vs. step-by-step, but we also had some other variables mixed in (non-working navigation, placeholder content, missing styles, etc) so I would be curious to retest the two options we have now: **hybrid version** (separated by sections) and the **single page scroll version**. 

It could definitely be as simple as @jeromeleecms mentioned as an A/B test where we show/explain both concepts and see how people react. @NAretakis I know you're leaning towards the single page for now, but does it seem worth it to test again and get that feedback based on the current iteration?

@jeromeleecms to your question about entering the 2-3 pages of text, the way I'm picturing that is all the large text areas are the same size and there is a way to drag the bottom right corner to make it longer. If they are entering 2-3 pages worth of text, they could drag it out so that ~1 page max can fit on the screen and then they can scroll within that. If they leave it in the default size and don't drag the corner, then the scrollbar would show up there as well. We'll definitely want to put it in front of users and see how they interact with it.

**Comment by lauraponce** [comment]
Tying this to #674 and #675 to make these updates

**Comment by lauraponce** [comment]
Adding a couple more design iterations from Aviva for the tables:

<img width="825" alt="screen shot 2018-06-13 at 5 58 37 pm" src="https://user-images.githubusercontent.com/21222704/41427311-5de42eac-6fbb-11e8-9bb4-409ec61ddf5b.png">

<img width="619" alt="screen shot 2018-06-13 at 5 59 51 pm" src="https://user-images.githubusercontent.com/21222704/41427319-626ab2a2-6fbb-11e8-811b-a2fd779fdd3c.png">
