### ISSUE TITLE
Rework 280 character limit phrasing in Program Activities

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#748]
280 character limit prompted questions and created anxiety – need to re-work the phrasing of that character limitation

**Comment by NAretakis** [comment]
We changed the helptext a bit, but the section is still limited to 280 characters. This still might create some anxiety, but I think we can help by explaining that the brief summary is supposed to be very short because we are going to use the Brief Summary in other section. While the activity details section can be  big as states need it to be.

**Comment by quarterback** [comment]
I'll re-work this again beyond what I changed last week on the fly during sprint planning.
