### ISSUE TITLE
FFY Summary Budget Table: State Costs and Contractor costs as only two line items

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#783]
In MBES and the HIT IAPD template, state staff and contractor costs are only two line items:

![image](https://user-images.githubusercontent.com/34279968/42398408-9c88228e-811e-11e8-97d8-8bf16adcc63c.png)

vs

![image](https://user-images.githubusercontent.com/34279968/42398452-c666f36e-811e-11e8-8429-6e9c3a026079.png)

Checking with @NAretakis to see if we had come to a different conclusion about how to represent this.

### This task is done when...
 - [ ] Decision made to combine or not combine these tables
 - [ ] Appropriate issue is spun up.

**Comment by brendansudol** [comment]
has a decision been made here @NAretakis @jeromeleecms ?

**Comment by NAretakis** [comment]
I am in favor of just combining Project State Staff with Non-Personnel costs, because that is what gets reported on the HIT Implementation and Operation In-house Costs line. And then contracted remains the same. Doing this will make financial reporting that much easier. @jeromeleecms you good with this?
