### ISSUE TITLE
Wireframe withdrawal experience

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#812]
When a state user wants to withdraw their submission, they will do so through the main APD page.

The 'Certify and Submit' button should switch to a 'Withdraw' button with messaging around confirming their withdrawal.

**Comment by lauraponce** [comment]
How does this seem for the flow? I'm thinking we can also just keep in the withdraw button like this on the submission page to act as the quick undo if they submitted too soon like you mentioned on the other issue @jeromeleecms. + @NAretakis to thread 

This is what they see when they come back to their APD:

![screen shot 2018-07-23 at 10 59 03 am](https://user-images.githubusercontent.com/21222704/43094351-805423c8-8e67-11e8-909e-de6288c14f43.png)

If they click the withdraw button:

![screen shot 2018-07-23 at 10 59 10 am](https://user-images.githubusercontent.com/21222704/43094370-867fffb0-8e67-11e8-944f-776bb90450f0.png)

Continuing to withdraw:

![screen shot 2018-07-23 at 10 59 18 am](https://user-images.githubusercontent.com/21222704/43094375-88dddde0-8e67-11e8-97c9-f801da434aa3.png)

**Comment by jeromeleecms** [comment]
- The "Withdraw after submission experience" is good. After you added the sign name to the submission process, do you think it's still necessary? Trying to think of "must haves" to move the MVP along and we could potentially add this functionality as a future request.
- @quarterback What do you think about making the language more generic? Since a contract may also need to be withdrawn -- or do you think it's better to call out the actual descriptor of the submission that is going to be withdrawn?
- For the "Withdraw" from the dashboard screen, where would the withdraw button appear (screenshot is from the current dashboard in the app)? Would it be a dropdown for the button circled?

![image](https://user-images.githubusercontent.com/34279968/43095934-46933408-8e6c-11e8-8b9b-42cdc312052b.png)

**Comment by lauraponce** [comment]
@quarterback can you help with writing the content for the withdrawal experience here? 

Basically, we need to update the first screen I posted ^ to add another blurb under **What to expect next**  for **Withdrawing your request** (or however it makes the most sense to phrase it) and tell people what to expect before they click the withdraw button. They need to know what it means to withdraw, what will happen after they do it, etc, etc.

Once they click the button, then it would take them to the next screen making them confirm, then the confirmation screen (both pages are posted above, but could use your 👀 on the content).

Let me know if you want to chat about this or anything!

**Comment by quarterback** [comment]
@lauraponce @jeromeleecms Agreed on simpler language. 

[ON SUBMISSION]
“Your California 2018 HITECH APD was submitted on [date, time].”

[NEXT STEPS]
To track the status of your request or start a new document, visit the state dashboard. Any questions from the CMS reviewer will also be routed through the dashboard.

[Go To Dashboard]

*Not sure we need a withdraw request button, because what would prompt someone to immediately withdraw after submitting the request, especially since they can’t see it?

**Comment by quarterback** [comment]
* What about "lock your APD to submit" so when they want to "withdraw" they'd "unlock" the APD submission? Withdrawal makes sense as the word here, but I'm wondering if it's something people would. When they submit now, it's printed and sent away in print so there wouldn't be a similar parallel to this in the existing workflow.

**Comment by lauraponce** [comment]
@quarterback sorry, I realized this issue wasn't super clear. This is the screen that people see when they select **View** from their state dashboard for a particular APD. Then they would go to the Submission section and instead of Certify and Submit, they would have the option to withdraw (since they've already submitted). This isn't something that very many people would need to do, most of the time it's just a back and forth between CMS and the state, but there are some cases where they need to withdraw their request and make changes to it. 

On this screen, they would see the info about their submission, what to expect next, and then what to do if they need to withdraw their request. So what we're looking for here is some language around that messaging. It could go right under "What to expect next" and could be something like "Withdrawing your request". It could say something about what it means to withdraw, what the effects of that are, and what they can do after they withdraw, etc. @NAretakis and @jeromeleecms and I chatted about it yesterday and thought it would be good for people to have that info before they click the button so they have a heads up.

**Comment by lauraponce** [comment]
@NAretakis @jeromeleecms how does this look? This has the latest content from @quarterback: 

<img width="419" alt="screen shot 2018-07-25 at 4 43 49 pm" src="https://user-images.githubusercontent.com/21222704/43233268-f1701b70-9029-11e8-9e5f-14a756a81a5e.png">

<img width="424" alt="screen shot 2018-07-25 at 4 41 29 pm" src="https://user-images.githubusercontent.com/21222704/43233205-a1944770-9029-11e8-9069-1d45c24aeffe.png">

**Comment by jeromeleecms** [comment]
Looks good. Two suggestions:

1) Under next steps, instead of “start a new document,” I would suggest “start a new submission” to be more generic.  
2) Under withdraw submission, “... will reset the review process upon resubmission.”

**Comment by lauraponce** [comment]
Here's an updated version <img width="426" alt="screen shot 2018-07-25 at 8 44 53 pm" src="https://user-images.githubusercontent.com/21222704/43240488-9981c8b0-904b-11e8-8e20-e0eccf387298.png">

**Comment by lauraponce** [comment]
#849 has the dev work for this
