### ISSUE TITLE
Wireframe the federal review experience

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#815]
The review experience should include:

- Commenting
- Viewing
- Sending back to state
- Approval
- Attaching approval letter
- Move executive summary to the top
- Final comment summary (maybe)
- Add a general comment at the end

**Comment by NAretakis** [comment]
Moved this issue into this GH milestone because I think it made sense. That said, @lauraponce already worked up the commenting stuff, which should leave us these things to do:

- Sending back to state
- Approval
- Attaching approval letter
- Move executive summary to the top
- Final comment summary (maybe)
- Add a general comment at the end

**Comment by jeromeleecms** [comment]
This will continue to roll into Milestone 7, Sprint 2.

**Comment by NAretakis** [comment]
closing this one out. We'll break this issue into several smaller epics.
