### ISSUE TITLE
Client Side Validation for MVP

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#831]
What still needs to be done for Client Side Validation to Complete MVP

@mgwalker to update this or add additional issues where needed, please!

Reference #330 

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
 ** don't forget to fill out the LABEL, MILESTONE, and PROJECT sections before submitting (then delete this line) **

**Comment by mgwalker** [comment]
One thing we'd need is to walk through all the fields and figure out which ones need validation and what constitutes valid data.

@hbillings: We have a validating input component at `components/InputsWithValidation`, but it only does local validation (and we're not using it anywhere 🎉).  Should we look into hooking that up to redux somewhere to track which fields are invalid so we can have a rollup view somewhere (like when they try to save it or something)?

@lauraponce: Bren posted a [demo video](https://cl.ly/t8LW) of the validating input field he built.  Do you like the way it behaves?  It looks like it responds to every change after the first blur but I'm not 100% sure.

**Comment by lauraponce** [comment]
@mgwalker For the error message, it is possible to reset it (or just not display the error) when they click back into it and the field is active? In this example, that's when it says Name is required. That way the validation would just happen on blur and display any errors at that point, but if they click into it presumably they are fixing any errors.

Also as far as what we're checking for, maybe just check that it's not blank since character count would be difficult since people can have one letter names? (Though I do like Bren's causal error message 😄 )

**Comment by hbillings** [comment]
Hmm, my first instinct is to just use [HTML5 form validation](https://pageclip.co/blog/2018-02-20-you-should-use-html5-form-validation.html) if we want pure client-side validation, but I also don't have the best grasp of what we're trying to do here. Is there a list of things that need to be validated and when the validation should occur somewhere?

**Comment by NAretakis** [comment]
For @hbillings and @mgwalker 's consideration. I think this can basically be tabled (and closed out) for MVP, because we are going to have federal users doing manual validation (during review) for each field for the MVP. That said, down the road we might want to come back to this, but right now Jerome and I talked it over and think it might be safe to close out. Do y'all see any issues with this approach?

**Comment by mgwalker** [comment]
So far the app doesn't crash when users input weird stuff (as far as we know), so...  should be fine from a technical perspective, I think.

**Comment by NAretakis** [comment]
Awesome. So, I think then we’re good with it as is, as long as you’re good with it as is. If we find something that breaks the app, then we fix it. But that’s a bridge down the road.

**Comment by NAretakis** [comment]
Closing this issue because we are going to use manual validation once an APD is submitted for review.
