### ISSUE TITLE
Recruit user research participants

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#84]
- [x] Draft a recruiting mail
- [x] Contact potential participants
- [x] Schedule time slots for participants

**Comment by NicolasAretakisCMS** [comment]
All state meeting on 1/22. We want to introduce this, and solicit some state interest. We'll still march forward with our list of states, but this is a good/natural engagement point.

**Comment by lauraponce** [comment]
Thanks for the update on the upcoming state meeting! That sounds like a great way to increase the visibility of this effort and hopefully get some more state contacts who are interested in participating in the research. 

What we're thinking about for the research at this stage is to use the list of contacts that was provided and start by reaching out to the states with the highest complexity and the ones that have been noted to be an important use case. Nicole, Meg, and I talked about using MA, OH, and NY as the starting points for the conversation and then going from there, but we're still thinking through the logistics.

**Comment by lauraponce** [comment]
@NicolasAretakisCMS and @jeromeleecms – we are in a good place now to start reaching out to some of our state contacts to set up the interviews for next week. It would be great to start with MI, AK and IA for the remote interviews. Are either of you be able to help with making the introductions to the state contacts so that we can get the conversations started about setting up interviews? If so, let me know what you need from me – I'm happy to draft an email or anything you need.

**Comment by jeromeleecms** [comment]
@lauraponce MI is willing to participate. I spoke with them on a separate topic today and brought this up (good timing!). On a related note, they participated in the 18F/MMIS project last year, so they are fairly familiar with 18F.

I don't have any specific contacts in AK or IA, so we can check in with @NicolasAretakisCMS and see "who he knows!" :)

**Comment by nicoleslaw** [comment]
We are pulling our in-person research plan together, but we'd like to go ahead and schedule some interviews for next week in the meantime. Since we have a contact via @nkkl in Vermont, we are wondering if we can talk to MI (already a yes!), AK, and VT (instead of IA).

I drafted a [recruiting email template](https://docs.google.com/document/d/1QlHnm_-TtXbr0HsDhLZIEub-8_CbRe8AjMxWRme48RE/edit#heading=h.c4w8mw9tgmau) with some time slots that work for us. Are y'all up for reaching out and introducing us today?

**Comment by jeromeleecms** [comment]
Sent a note to MI -- @NicolasAretakisCMS plans on being on the stand-up today, so I'll check in with him if he has time to send the intro email to AK, if he's tied up, I will take care of it.

**Comment by nicoleslaw** [comment]
Thank you so much @jeromeleecms!

@nkkl Would it make sense for you to introduce us to our Vermont contact, or should we still lead with CMS asking for help?

**Comment by nkkl** [comment]
If @jeromeleecms and @NicolasAretakisCMS know Denise, they can intro. Otherwise it's probably faster/easier for me to do it. :)

**Comment by jeromeleecms** [comment]
Spoke with @NicolasAretakisCMS during our stand-up time about this and sent the intro email to Alaska (removing the time that Michigan already nabbed).

@nkkl I don't know Denise, so I'm good with you reaching out to them. Thank you!

@nicoleslaw As an aside - not sure if you were planning on inviting @NicolasAretakisCMS or I to these interviews, but if you think there is a risk that having a CMS presence could skew the results, we are good with not attending.

**Comment by nkkl** [comment]
Just sent an email to Vermont!

**Comment by nicoleslaw** [comment]
@jeromeleecms @NicolasAretakisCMS It would be great to have you observe and listen in! A couple of quick thoughts, but we can chat more before the first session:

- We'll share our questions ahead of time in case there's anything else you'd like us to ask about.
- I find that having one person lead the interview and one person taking notes helps build rapport with the interviewee. Since we're all in Slack, you're welcome to ping us during an interview if you want us to dig into anything in particular. We could also leave a few minutes at the end of the call to see if anyone listening in has questions.
- If you need to miss any sessions, we will take notes and share highlights afterwards.

@lauraponce may have more to add—I am a strong researcher but she is the expert!
