### ISSUE TITLE
Office Hours for State Testers 

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#866]
We've talked about this, but if we are doing a refinement sprint, let's take advantage of this to also offer office hours so State's interested in logging into a web conference can play with the app with CMS/18F on the line.

### This task is done when...
 - [ ] Time is scheduled
 - [ ] Office Hours Held
 
cc: @lauraponce @quarterback

**Comment by quarterback** [comment]
Let's talk about this the first part of next week and how we'd like to handle it. I imagine we can let folks know in the emails after we schedule the latest round, and since it's just drop-in, I guess really all we need is for us to be available for people to talk to? @NAretakis @jeromeleecms @lauraponce

**Comment by NAretakis** [comment]
Yeah, we can have a WebEx for screen sharing too. Folks can come in, try some stuff, talk about it, get feedback. We’ll also probably want to just record the session to make note taking easier.
