### ISSUE TITLE
Refine instructions/help text styles

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#962]
It came up in usability testing that it's difficult to tell which text is part of the instructions and what is part of the area where they have to input something. Maybe there is a way to better delineate that boundary?

I know you're already working on the spacing and related things to the help text in #861, so tagging that here. 

For example:

<img width="706" alt="screen shot 2018-08-22 at 10 00 19 am" src="https://user-images.githubusercontent.com/21222704/44478393-692c9c00-a5f2-11e8-8e21-28e37f9024ae.png">

**Comment by AvivaOskow** [comment]
Considerations:
- [ ] Better differentiations between instructions and help text
- [ ] Try to delete or combine duplicative instructions

**Comment by quarterback** [comment]
@quarterback

**Comment by AvivaOskow** [comment]
**Updated styles**

![help text styles](https://user-images.githubusercontent.com/21244661/44937799-203ebb00-ad49-11e8-803c-07c0b3aaf6c0.png)

**Comment by AvivaOskow** [comment]
To differentiate between instructions and help text, instructions should be details on how to actually fill out the section, "fill out XYZ" while help text should be additional contextual information that would help the user understand background or specific points to remember.

Implement a folded corner or triangle tab icon to a Light blue #DAE9F7 background instead of the yellow, which seems more like an alert or something wrong.

**Be aware of:**
- **Remove bolding** of any instructional text
- Be aware of what should go in what style in terms of i**nstructive text vs useful context/help text.**

**Comment by mgwalker** [comment]
On the text styling, what does the "Reg. 20/30" refer to?  :learning:

**Comment by AvivaOskow** [comment]
@mgwalker that is shorthand for referring to the font weight and size/leading. So it's Source Sans Regular (not bold or italic) and it's size 20 with 30 leading between lines. 

I generally try to do line height (leading) that is either 1.3 or 1.5x the font size itself because I know the way it's coded is using rem I believe? So instead of the actual type size written in, one of the sizes is equal to 1rem, 2rem, etc? Learned this from @brendansudol back in the day :)

<img width="341" alt="screen shot 2018-08-31 at 6 36 09 pm" src="https://user-images.githubusercontent.com/21244661/44938378-7d883b80-ad4c-11e8-8b15-b1e201d218d8.png">

**Comment by quarterback** [comment]
@mgwalker (I believe) regular (as opposed to bold or italic) and type size.

**Comment by mgwalker** [comment]
Nifty!  Thanks for the explainer!  😄

**Comment by NAretakis** [comment]
not sure the next follow-up here. This info seems great, do we need an issue to implement some of these refinements?

**Comment by lauraponce** [comment]
Created #1034 for the dev work on this
