### ISSUE TITLE
Determine if any sort of libraries exist that allow us to export to PDF and RTF (word)

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#974]
We need to figure out what happen when a user clicks the "export" button. Also, there should be an "export" button. 

We can use this issue to document any libraries we can use for this effort. And/or figure out if we need to make something ourselves.

**Comment by mgwalker** [comment]
Bren had begun working on a print view, which we may or may not want to follow through on.  The downside to it is that it's a pretty considerable amount of work to turn those input boxes into just text fields, and there's a lot of help text that presumably wouldn't need to be in a PDF.

That said, if the point of the PDF is to essentially be a safety blanket for folks nervous about using the new system, maybe all the help text is fine, and it's okay that the text fields look like input boxes instead of just being paragraphs of text?  If we stick with the print view and accept the limitations with it, we might be able to use `jsHTML` to capture the DOM elements we want and build a PDF directly in the browser.

The only reasonable alternative I can think of is to build a static HTML version of the APD styled with printable settings and use `html-pdf` to create the PDF from that.  I'd probably recommend Mustache or Handlebars templates and then some massaging of the APD data to accommodate the "logic-less" nature of those template engines.

This approach is a pretty big time investment in building all the template pieces, but it might be easier than all the code changes to fix up the text and stuff with the print view.  Here's an example of what that might look like (but without any good styling yet):

[out.pdf](https://github.com/18F/cms-hitech-apd/files/2497002/out.pdf)

The biggest concern I have with creating a PDF in either situation is dealing with page breaks.  We could build the PDF completely manually, in which we compute the height of text areas and figure out where to put in page breaks and all of that, but that is incredibly painful and would take forever and probably be wrong anyway.  😛  If we generate a PDF from a HTML, we can use the `page-break-` CSS properties to hint to the PDF renderer that we don't want it to break tables into multiple pages, for example.  We still don't have complete control, but the hinting might be good enough for our needs.

So the two big options for PDF:
- try to capture the DOM elements from the print view and use jsPDF in the browser
- build a static HTML page for an APD and use html-pdf to turn it into a PDF

## For Word...

There's really nothing out there.  Not even the (relatively) simpler RTF format.  There's a library called html-rtf, but it has limited formatting support - notably it can't do lists.  I'll keep looking around.  The closest thing I've found is a hacky way of convincing the browser to open Word and magically pasting HTML into it, and then Word does the formatting for you.  That would be really hard to develop on our end because, AFAIK, none of us have Word.  😬

**Comment by NAretakis** [comment]
There have been a few conversations on this. Looking for the lightest weight option, @mgwalker suggest of page-break- CSS properties might get us the closest. @hbillings also suggested that we do some landscape printing for embedded tables which I think can also be handled through CSS. 

All that said, @mgwalker @hbillings , is page-break and some CSS formatting tricks on the "print preview" page seem like smallest LOE for this? Asking in case I missed some sort of magical API to PDF exporting library.

**Comment by mgwalker** [comment]
So the potential workflow is:

1. click the "print preview" button
2. click the browser's "print" button (we could also initiate this with some Javascript)
3. save/print to PDF

Is that okay?

**Comment by NAretakis** [comment]
I think for MVP this is good. It gets the job done of getting a paper copy of the eAPD. While it might not look great, it will all be there. This could be something that we refine quite a bit in the post MVP world.

**Comment by NAretakis** [comment]
Probably good to close this issue, I think? As we have an MVP plan.

**Comment by mgwalker** [comment]
Sounds good to me.  👍

**Comment by NAretakis** [comment]
closing as we have an MVP plan. An MVPP, so to speak.
